### ISSUE TITLE
[BUG] GitHub fails to execute tests with chromium does not exist error

### ISSUE THREAD

**Issue by ladeak** [microsoft/playwright#12150]
**Context:**
- Playwright Version: 1.18.1
- Operating System: windows-latest (GitHub action, Windows Server 2019)
- Node.js version: 14.18.3
- Browser: chromium
- Extra: GitHub environment

GitHub fails to execute tests with chromium does not exist error:

**Code Snippet**

```
Error Message:
   Microsoft.Playwright.PlaywrightException : Executable doesn't exist at C:\Users\runneradmin\AppData\Local\ms-playwright\chromium-9[56](https://github.com/[path]/runs/5214076314?check_suite_focus=true#step:9:56)323\chrome-win\chrome.exe
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     playwright install                                                  ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
  Stack Trace:
     at Microsoft.Playwright.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args)
   at Microsoft.Playwright.Core.BrowserType.LaunchAsync(BrowserTypeLaunchOptions options)
```

**Describe the bug**

Using the following GitHub Action:

```yaml
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Test
      run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-build
```

After having playwright installed on GitHub, it still fails and shows me to install playwright.
