### ISSUE TITLE
Failed: browserType.launch: Browser closed on github action

### ISSUE THREAD

**Issue by vickyrathee** [microsoft/playwright#12176]
**Context:**
- Playwright Version: 1.19.1
- Operating System: Linux
- Node.js version: 14
- Browser: All
- Extra: Angular

**Code Snippet**

My github action to run the angular `e2e` tests

```
name: Node.js CI

on:
  pull_request:
    branches: []

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Update webdriver
      run: npm run webdriver-update
    - name: Run your tests
      run: npm run e2e
```

Error

![image](https://user-images.githubusercontent.com/6106479/154444270-17f58d15-d626-4edc-9fba-d09f9256875d.png)

```javascript
import { Browser, chromium, firefox, Page, webkit } from 'playwright';

for (const browserType of [chromium, firefox, webkit]) {

  describe(`(${browserType.name()}): Login page`, () => {
    let browser: Browser;
    let page: Page;

    beforeAll(async () => {
      browser = await browserType.launch({ headless: false });
      page = await browser.newPage();
    });

    it('Should display the correct page title', async () => {
      await page.goto('http://localhost:4200/login');
      expect(await page.title()).toBe('Login - DaySchedule');
    });
 }
}
```

**Describe the bug**

Getting error: Failed: browserType.launch: Browser closed on github action while everything working fine on local windows machine. Already tried to add ` npx playwright install --with-deps` and `driver-update`
