### ISSUE TITLE
[Question] Create Custom Image starting from maven:3-jdk-8-alpine - Gitlab CI

### ISSUE THREAD

**Issue by gianluca1606** [microsoft/playwright#12979]
Hello,

like mentioned above we need for our Java Application the following image: maven:3-jdk-8-alpine.

How would it be possible to create a custom Docker Image for our CI and the Dockerfile(Kubernetes) itself:

Here is a cutout of our CI:

```
build:
  stage: build
  image: maven:3-jdk-8-alpine
  variables:
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/repository -Djava.awt.headless=true"
  script:
    - mvn $MAVEN_CLI_OPTS clean verify
    - cat target/jacoco/index.html | grep -o '<tfoot>.*</tfoot>'
    - 
 ```
