### ISSUE TITLE
[BUG] npx playwright install does not install appropriate browsers

### ISSUE THREAD

**Issue by unlikelyzero** [microsoft/playwright#13188]
**Context:**
- Playwright Version: 1.19.2
- Operating System: ubuntu-latest, windows-latest
- Node.js version: 12,14,16,17
- Browser:  Webkit, Chrome
- Extra: Github Workflows

**Code Snippet**

https://github.com/nasa/openmct/blob/ae553e2b82eea88e26c78a23abc8664f2a412e95/.github/workflows/e2e-pr.yml

```yaml
     - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
      - run: npx playwright install
      - run: npm install
      - run: npm run test:e2e:full
```

**Describe the bug**

`npx playwright install` Does not appear to download necessary browsers if using an older playwright/test version.

```
browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium-965416/chrome-linux/chrome
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝
```

Note that specifying npx playwrigh@1.19.2 works.
