### ISSUE TITLE
[Question] How to Configure the sharding in the Azure Devops

### ISSUE THREAD

**Issue by FahadRS** [microsoft/playwright#13979]
We are using the Azure DevOps to execute our tests,  my question is there any way I can configure the sharding as described here https://playwright.dev/docs/test-parallel in the azure DevOps to run the tests on the multiple machines.

I have searched on the internet the only option I am able to find is that distribute the tests across multiple machines using parallel jobs https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml but there is no article that explains how to configure the sharding.

**Comment by rwoll** [comment]
Assuming you want 3 shards, your yaml will end up looking something like:

```yml
jobs:
- job: shard-1
  pool:
    vmImage: 'ubuntu-20.04'
  container: mcr.microsoft.com/playwright:v1.21.0-focal
  steps:
  - script: npm ci
  - script: npx playwright test --shard=1/3 
- job: shard-2
  pool:
    vmImage: 'ubuntu-20.04'
  container: mcr.microsoft.com/playwright:v1.21.0-focal
  steps:
  - script: npm ci
  - script: npx playwright test --shard=2/3 
- job: shard-3
  pool:
    vmImage: 'ubuntu-20.04'
  container: mcr.microsoft.com/playwright:v1.21.0-focal
  steps:
  - script: npm ci
  - script: npx playwright test --shard=3/3 
```

NB: From the Azure Docs:

> Each agent can run only one job at a time. To run multiple jobs in parallel you must configure multiple agents. You also need sufficient [parallel jobs](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops).

So make sure that requirement is also met! Also, ⚠️ be sure to update the version number of the docker container to match your Playwright version. 

References:
- Section titled **_Example jobs that build in parallel (no dependencies)_** in https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml
- Playwright Sharding Docs: https://playwright.dev/docs/test-parallel#shard-tests-between-multiple-machines
- Playwright Azure Docs: https://playwright.dev/docs/ci#azure-pipelines
