### ISSUE TITLE
[Feature] Add new flag `--report-only-tests-in-shard` to omit skipped test not part of the current shard for GitLab test report consolidation across shards

### ISSUE THREAD

**Issue by danvim** [microsoft/playwright#14137]
- Playwright version: 1.21.1

### Background

I'm trying to parallelize Playwright tests in GitLab CI using `--shard` and generate JUnit reports for displaying on GitLab. However, since the part of the tests not included in the current shard are considered to have been **skipped**, these skipped tests are still included in the final JUnit report.

**.gitlab-ci.yml (For illustration only. Untested)**

```yaml
Playwright:
  image: mcr.microsoft.com/playwright
  parallel: 3
  variables:
    PLAYWRIGHT_JUNIT_OUTPUT_NAME: junit.xml
  artifacts:
    reports:
      junit: junit.xml
  script:
    - yarn
    - yarn serve
    - npx playwright test --shard $CI_NODE_INDEX/$CI_NODE_TOTAL --reporter=junit
```

Let's say I only have one test file with 5 `test()`s, then that only test is only run in shard `1/3`, the `junit.xml` would say each `test()` either passed or failed. But that test file is skipped in shard `2/3` and `3/3` and those `junit.xml` would report each `test()` as having been skipped.

After GitLab collects the various `junit.xml` from each parallel worker, it would generate a test report. Now it would say there are a total of 10 tests instead of the original 5, with 5 cases from shard `1/1` being passed or failed, and the other 5 (combining shard `2/3` and `3/3`) skipped.

This desired behavior in the above scenario would be that only shard `1/3` would generate a `junit.xml` containing the test results and the other shards would generate empty `junit.xml`s

### Feature Request

Can we have a new flag like `--report-only-tests-in-shard` that would cause the resulting test report to contain only tests intended for the current shard?
