### ISSUE TITLE
[BUG] Firefox Timeout in docker image when using inside Jenkins

### ISSUE THREAD

**Issue by Majdoub90** [microsoft/playwright#14792]
**Context:**
- Playwright Version: [1.22.2]
- Operating System: [Linux]
- Node.js version: [14.2]
- Browser: [Firefox]
- Extra: []

**Code Snippet**
DOCKER FILE : 
```
FROM mcr.microsoft.com/playwright:v1.22.0-focal
WORKDIR /client
COPY . /client/
EXPOSE 3000 1880
RUN ["chmod", "+x", "/client/entrypoint.sh"]
ENTRYPOINT [ "./entrypoint.sh" ]
```

**Describe the bug**
I'm trying to run my playwright test in my docker image. Everything works fine in local. But when I run the test in the docker image firefox always timeout. I tried some other playwright images and noticed that for example playwright:v1.15.0-focal and playwright:v1.10.0-focal work perfectly fine. Running the tests in the bitbucket CI also works perfectly. I also tried playwright install --with-deps but the same issues persist. I'm not sure if what I'm doing is valid or the problem is with the dependencies installation?

**Comment by pavelfeldman** [comment]
Let me keep it open to collect more repros. So far, there has not been any complaints.

**Comment by Majdoub90** [comment]
I'm not too sure if it's totally a bug but this is what I found. After multiple trials, I understood that If I run a fresh docker like this 
`docker run -it --rm --ipc=host mcr.microsoft.com/playwright:v1.22.2-focal /bin/bash`
and I do `npm init playwright@latest new-project`
Only then would the test work. The problem is, if I create the set of test with
`npm init playwright@latest new-project`
in local and let's say we name the project Hello_world. Then when I run 
`sudo docker run -it --rm --ipc=host -v $(pwd):/hello_world  mcr.microsoft.com/playwright:v1.22.2-focal /bin/bash`
and then run the tests, The firefox ones timeout.

**Comment by Majdoub90** [comment]
UPDATE : I succeded in making firefox tests work with a command like this in the docker file
WORKDIR /
ADD . hello_world
now all my client is copied to a new folder named hello_world. If I run my tests in client firefox fails. If I run them in hello_world the firefox tests work. I really don't know why this works. Does anyone have any idea? I guess it is somewhat a work around the issue. I would still love to get insight about why this works.

**Comment by morepe** [comment]
I got the same issue. with playwright 1.23.2 on WSL2 Ubuntu image

My steps to reproduce: 

```
mkdir visual-comparison
cd visual-comparison

npm init playwright@latest
```

Now I created a directory visual-comparison/ci containing a docker-compose file where I reference the project as volume: 

```
version: '3'
services:
  tests:
    image: mcr.microsoft.com/playwright:v1.23.2-focal
    ipc: host
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    working_dir: /visual-comparison
    cap_add:
      - SYS_ADMIN
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npx playwright test
    volumes:
      - ..:/visual-comparison
```

When doing a `docker-compose -f ci/docker-compose.yaml run tests` I got the same timeout error.  However, when I add a Dockerfile containing just these lines: 

```
FROM mcr.microsoft.com/playwright:v1.23.2-focal
ADD visual-comparison visual-comparison
```

and change the docker-compose to use my image where the folder is already part of the build instead of mounted as volume it works:
```
version: '3'
services:
  tests:
    build:
      dockerfile: visual-comparison/ci/Dockerfile
      context: ../../
    ipc: host
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    working_dir: /visual-comparison
    cap_add:
      - SYS_ADMIN
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npx playwright test
```

I don't know the difference, I would bet on some permission issue.
