### ISSUE TITLE
[BUG] New Playwright releases break GitHub Actions cache

### ISSUE THREAD

**Issue by ericmatthys** [microsoft/playwright#15998]
**Context:**
- Playwright Version: Latest (14.1 now)
- Operating System: Linux (GitHub Actions Ubuntu runners)
- Node.js version: 16x
- Browser: Chromium

**Code Snippet**

GitHub Actions setup steps:

```yml
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event_name != 'pull_request' }}

      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.7

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Install Playwright
        run: pnpx playwright install --with-deps chromium
```

**Describe the bug**

When a new Playwright version is released, it seems like we run into problems with our GitHub Actions cache. Maybe the timing is coincidental and it's not actually related, but I think it probably is. We'll see errors like this:

> browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium-1012/chrome-linux/chrome%0A

If I delete cache entries via the GitHub API and retry, this will fix the issue. If I upgrade Playwright to the latest, this will also fix the issue until a new version comes out again. I think this could be more of a GitHub Actions issue / question, but I'm asking here in case there's a problem with the setup steps that someone can spot. It is strange that the cache could be seemingly affected by a new release before we ever even open up a PR with that upgrade.
