### ISSUE TITLE
[BUG] `playwright: not found` Command failed with exit code 127

### ISSUE THREAD

**Issue by KirillGalimov** [microsoft/playwright#16879]
**Context:**
- Playwright Version: **1.25.1**
- Operating System: **Linux**
- Node.js version: **16.14.2**
- Browser: **All**
- Yarn version: **1.22.4**

**Describe the bug**

When I try to add Playwright to an existing project locally I get an error on start:
```
./node_modules/.bin/playwright: not found
error Command failed with exit code 127
```
_The error doesn't occur in fresh project._

**Steps to reproduce:**
1) `yarn create playwright`
2) `yarn playwright test`

**The problem also reproduced using GitHub Actions:**
<details>
  <summary>playwright.yml</summary>

  ```
  name: 'Playwright'
on: push

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node and Dependencies
        uses: ./.github/actions/node-deps

      - name: Install Playwright
        run: yarn create playwright --yes -- --quiet --browser=chromium --browser=firefox --browser=webkit --install-deps

      - name: Start Playwright
        run: yarn playwright test
  ```
</details>
