### ISSUE TITLE
[Feature] Add launch steps to documentation about Azure Pipelines integration

### ISSUE THREAD

**Issue by svdHero** [microsoft/playwright#17012]
In the [Azure Pipelines section](https://playwright.dev/docs/ci#azure-pipelines) the code snippet is missing the actual steps to launch the tests.

I have tried the following Azure Pipeline Job:

```yaml
jobs:
    - deployment: Run_Smoke_Tests
      pool:
        vmImage: ubuntu-20.04
      container: mcr.microsoft.com/playwright:v1.25.0-focal
      environment: testing
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: Bash@3
              displayName: 'Run E2E tests'
              inputs:
                workingDirectory: 'my-e2e-tests'
                targetType: 'inline'
                failOnStderr: true
                script: |
                  export CI=true
                  npm install
                  npx playwright test
```
Is this the best way to run tests in Azure Pipelines?
If so, I would be happy to open a PR and extend the code snippet in the documentation.
