### ISSUE TITLE
[Question] Playwright component github CI set up

### ISSUE THREAD

**Issue by westwai** [microsoft/playwright#17694]
I'm having an issue trying to run component tests on Github CI with configuration shown below. 

Issue with installing playwright component part in github:
```
Run npm init playwright@latest -- --ct-react
npm WARN exec The following package was not found and will be installed: create-playwright@1.1[7](https://github.com/project/project/actions/runs/3152040369/jobs/5126822667#step:5:8).119
Getting started with writing end-to-end tests with Playwright:
Initializing project in '.'
25l25l? Where to put your end-to-end tests? ‣ tests25h25h
```
**github pipeline component tests part:**

```
    componentTests:
    name: Component tests
    runs-on: ubuntu-20.04
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v1
      - name: "📦 install dependencies"
        uses: ./.github/actions/prepare
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Install dependencies
        run: npm install
      - name: "📦 install playwright"
        run: npm init playwright@latest -- --ct
      - name: "🔍 run component tests"
        run: npm run test:components
        continue-on-error: true
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report

```

**select.test.tsx**
```
import * as React from "react";

import { test, expect } from "@playwright/experimental-ct-react";
import Select from "react-select";

test("should work", async ({ mount }) => {
    const component = await mount(<Select></Select>);
    await expect(component).toContainText("Select...");
});

```

**playwright-ct.config.ts**

```
import type { PlaywrightTestConfig } from "@playwright/experimental-ct-react";
import { devices } from "@playwright/experimental-ct-react";

const config: PlaywrightTestConfig = {
    testMatch: /.*\.test\.tsx/,
    snapshotDir: "./__snapshots__",
    timeout: 10 * 1000,
    fullyParallel: true,
    forbidOnly: !!process.env.CI,
    retries: process.env.CI ? 2 : 0,
    workers: process.env.CI ? 1 : undefined,
    reporter: "html",
    use: {
        trace: "on-first-retry",
        ctPort: 3100,
    },
    projects: [
        {
            name: "chromium",
            use: {
                ...devices["Desktop Chrome"],
            },
        },
        {
            name: "firefox",
            use: {
                ...devices["Desktop Firefox"],
            },
        },
        {
            name: "webkit",
            use: {
                ...devices["Desktop Safari"],
            },
        },
    ],
};

export default config;

```
**package.json:** 

```
"scripts": {
        "test:components": "playwright test -c playwright-ct.config.ts",
    },
"dependencies": {
        "classnames": "^2.3.2",
        "date-fns": "^2.14.0",
        "fullcalendar": "^5.4.0",
        "polished": "^4.2.2",
        "print-js": "^1.6.0",
        "react-datepicker": "^4.3.0",
        "react-onclickoutside": "^6.9.0",
        "react-select": "^3.2.0",
        "react-tooltip": "^4.2.21",
        "units-css": "^0.4.0"
    },
    "devDependencies": {
        "@commitlint/cli": "^8.3.5",
        "@commitlint/config-angular": "^8.3.4",
        "@fullcalendar/core": "^5.4.0",
        "@fullcalendar/daygrid": "^5.4.0",
        "@fullcalendar/react": "^5.4.0",
        "@playwright/experimental-ct-react": "^1.25.1",
        "@rollup/plugin-alias": "^3.1.9",
        "@rollup/plugin-commonjs": "^22.0.2",
        "@rollup/plugin-node-resolve": "^14.1.0",
        "@rollup/plugin-url": "^7.0.0",
        "@storybook/addon-essentials": "^6.5.10",
        "@storybook/addon-links": "^6.5.10",
        "@storybook/addons": "^6.5.10",
        "@storybook/react": "^6.5.10",
        "@storybook/testing-react": "1.3.0",
        "@svgr/rollup": "^6.3.1",
        "@svgr/webpack": "^5.3.1",
        "@testing-library/jest-dom": "^5.15.0",
        "@testing-library/react": "^12.1.2",
        "@testing-library/user-event": "^13.5.0",
        "@types/faker": "^4.1.12",
        "@types/lodash": "^4.14.155",
        "@types/react": "^16.9.36",
        "@types/react-datepicker": "^3.0.2",
        "@types/react-dom": "^16.9.8",
        "@types/react-onclickoutside": "^6.7.3",
        "@types/react-router-dom": "^5.1.5",
        "@types/react-select": "^3.0.13",
        "@types/react-test-renderer": "^16.0.1",
        "@types/styled-components": "^5.1.0",
        "@typescript-eslint/eslint-plugin": "^5.35.1",
        "@typescript-eslint/parser": "^5.35.1",
        "babel-preset-react-app": "^10.0.1",
        "chromatic": "^6.9.0",
        "crypto-browserify": "^3.12.0",
        "css-loader": "^2.1.1",
        "eslint": "^8.22.0",
        "eslint-import-resolver-typescript": "^3.5.1",
        "eslint-mdx": "^1.17.1",
        "eslint-plugin-import": "^2.26.0",
        "eslint-plugin-import-alias": "^1.2.0",
        "eslint-plugin-mdx": "^1.17.1",
        "eslint-plugin-react": "^7.31.0",
        "eslint-plugin-storybook": "^0.6.4",
        "faker": "^4.1.0",
        "generate-source-map": "^0.0.5",
        "gojs": "^2.1.42",
        "gojs-react": "^1.0.10",
        "husky": "^4.3.8",
        "jest": "^27.3.1",
        "jest-styled-components": "^7.1.1",
        "lint-staged": "^10.2.10",
        "lodash": "^4.17.15",
        "mini-css-extract-plugin": "^0.7.0",
        "moment": "^2.26.0",
        "plop": "^3.1.1",
        "postcss-loader": "^3.0.0",
        "postcss-preset-env": "^6.6.0",
        "react": "^16.13.1",
        "react-avatar": "^5.0.1",
        "react-dom": "^16.13.1",
        "react-router-dom": "^5.2.0",
        "react-test-renderer": "^16.0.0",
        "react-use": "^15.3.2",
        "rimraf": "^2.6.3",
        "rollup": "^2.79.0",
        "rollup-plugin-copy-assets": "^2.0.3",
        "rollup-plugin-peer-deps-external": "^2.2.4",
        "rollup-plugin-postcss": "^4.0.2",
        "rollup-plugin-require-context": "^1.0.1",
        "rollup-plugin-typescript2": "^0.34.0",
        "semantic-release": "^19.0.3",
        "storybook": "^6.5.10",
        "storybook-addon-pseudo-states": "^1.15.1",
        "style-loader": "^0.23.1",
        "styled-components": "^5.1.1",
        "ts-jest": "^27.1.5",
        "ts-loader": "^6.0.2",
        "ts-node": "^10.9.1",
        "tsconfig-paths-webpack-plugin": "^4.0.0",
        "typescript": "^3.9.5",
        "url-loader": "^2.0.0"
    },
    "sideEffects": false,
    "husky": {
        "hooks": {
            "pre-commit": "npm run lint:check",
            "pre-push": "npm run build && npm run test:ci",
            "commit-msg": "commitlint --verbose -e"
        }
    },
    "browser": {
        "crypto": false
    },
    "peerDependencies": {
        "gojs": ">=2.1.42",
        "gojs-react": ">=1.0.10",
        "react": ">=16.0.0",
        "react-use": ">=15.3.2",
        "styled-components": ">=5.1.1"
    }
}

```

Please let me know if I should add anything else for context, thank you in advance!
