### ISSUE TITLE
[BUG] Invalid method when connecting to Selenium Grid using http and proxy

### ISSUE THREAD

**Issue by wodyjowski** [microsoft/playwright#17707]
**Context:**
- Playwright Version: v1.26.1
- Operating System: Linux
- Node.js version: 16.13.1
- Browser: Chrome
- Extra: Selenium Grid

**Describe the bug**

When connecting to Selenium Grid using http and proxy, playwright fails by sending GET instead of POST.
You forgot to pass `method` in your "proxied" case in `common/netUtils.ts`.
I've created a [PR](https://github.com/microsoft/playwright/pull/17706) with a fix.

**Comment by wodyjowski** [comment]
Can be reproduced by running docker-compose:
```
services:
  selenium-hub:
    image: selenium/hub:4.2.1
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_TIMEOUT=30
      - GRID_BROWSER_TIMEOUT=600

  selenium-node-chrome1:
    image: selenium/node-chrome:4.2.1
    shm_size: 2g
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://XXX.XXX.XXX.XXX:4444

  squid:
    image: ubuntu/squid
    ports:
      - "9921:3128"
    environment:
     - TZ=UTC
```
Where XXX.XXX.XXX.XXX must be a loopback interface or PC's LAN network IP (can't use localhost due to squid being hosted in container).
Running Playwright tests with variables:
```
set SELENIUM_REMOTE_URL=http://XXX.XXX.XXX.XXX:4444
set DEBUG=*
set http_proxy=http://localhost:9921
```
will result in: `browserType.launch: Error connecting to Selenium at http://XXX.XXX.XXX.XXX:4444/session: Unable to find handler for (GET) /session`
