### ISSUE TITLE
[Question] How to properly setup GitHub Actions with a React App

### ISSUE THREAD

**Issue by Addison-Dalton** [microsoft/playwright#17842]
I'm trying to setup a GitHub Actions workflow to run my playwright tests against a react app. It's a fairly standard setup, as far as I can tell, yet I keep getting `Error: Process from config.webServer exited early.` whenever the action gets to the `yarn playwright test` step.

Here's the workflow file:
```yml
name: 'End to End Tests'
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
jobs:
  playwright-run:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      github.event.pull_request.draft == false
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:3001
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5
```

And here is the relevant `webServer` config from the `playwright.config.ts` file:
```typescript
  /* Run your local dev server before starting the tests */
  webServer: {
    command: 'yarn start',
    url: process.env.PLAYWRIGHT_BASE_URL,
    // wait at least 10 minutes
    timeout: 600 * 1000,
    reuseExistingServer: !process.env.CI,
  },
};
```

The `webServer` config works fine when ran locally. It's only with the workflow that I get that error mentioned above. I've also tried running the workflow locally, with `act`, while having the react app running (setting `reuseExistingServer` to true), and yet I get the same error.

Any thoughts are appreciated!
