### ISSUE TITLE
[Question] Playwright Timeout Exceeded in Github Actions

### ISSUE THREAD

**Issue by dlarroder** [microsoft/playwright#17874]
I am getting a `Test timeout of 30000ms exceeded.` error in my Github Actions but in local dev server all tests pass,

I am currently running the following commands in both CI and local dev server:

`DEBUG=pw:api yarn playwright test --workers=1  --max-failures 1`

Is there a way to have it fail locally? It is really hard to debug the error in CI

![Screen Shot 2022-10-06 at 9 36 48 PM](https://user-images.githubusercontent.com/52998821/194327487-025ae357-55d1-4f17-b33f-7ac83e2d0c43.png)

Configs -- 

```
jobs:
  E2E:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright/
          key: ${{ runner.os }}-browsers

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Install Playwright Dependencies
        run: npx playwright install-deps

      - name: Install Playwright
        run: npx playwright install

      - name: Run E2E Test
        run: DEBUG=pw:api yarn test:e2e --max-failures 1
```

```
const config: PlaywrightTestConfig = {
  testDir: './tests',
  timeout: 30 * 1000,
  expect: {
    timeout: 5000,
  },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    actionTimeout: 0,
    trace: 'on-first-retry',
    launchOptions: {
      slowMo: 500,
    },
    headless: true,
  },
  webServer: {
    url: 'http://localhost:3000/',
    command: 'yarn start',
    timeout: 240 * 1000,
    reuseExistingServer: !process.env.CI,
  },
}
```
