### ISSUE TITLE
[BUG] Fails in Github Actions workflow

### ISSUE THREAD

**Issue by fi5u** [microsoft/playwright#17947]
**Context:**
- Playwright Version: 1.26.1
- Operating System: Ubuntu (latest)
- Node.js version: 16
- Browser: Chromium, Firefox, WebKit
- Extra: 

**Code Snippet**

```
import { expect, test } from '@playwright/test'

test('homepage has Playwright in title and get started link linking to the intro page', async ({
  page,
}) => {
  await page.goto('https://playwright.dev/')

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/)

  // create a locator
  const getStarted = page.locator('text=Get Started')

  // Expect an attribute "to be strictly equal" to the value.
  await expect(getStarted).toHaveAttribute('href', '/docs/intro')

  // Click the get started link.
  await getStarted.click()

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*intro/)
})
```

**GitHub Action Workflow**

```
name: Playwright Tests
on:
  # workflow_dispatch
  push:
    branches: [main, testing]
  pull_request:
    branches: [main, testing]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
```

Using the basic examples for both Playwright and the GitHub Actions integration, I get the following errors when set up on my repository:

```
Run npx playwright test
[4](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:5)

[5](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:6)
Running 4 tests using 1 worker
[6](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:7)
××F××F××F××F
[7](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:8)

[8](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:9)
  1) [chromium] › example.spec.ts:3:1 › homepage has Playwright in title and get started link linking to the intro page 
[9](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:10)

[10](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:11)
    TypeError: Cannot read properties of undefined (reading 'mode')
[11](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:12)

[12](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:13)

[13](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:14)

[14](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:15)
    Retry #1 ---------------------------------------------------------------------------------------
[15](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:16)

[16](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:17)
    TypeError: Cannot read properties of undefined (reading 'mode')
[17](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:18)

[18](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:19)

[19](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:20)

[20](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:21)
    Retry #2 ---------------------------------------------------------------------------------------
[21](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:22)

[22](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:23)
    TypeError: Cannot read properties of undefined (reading 'mode')
[23](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:24)

[24](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:25)

[25](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:26)

[26](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:27)
  2) [firefox] › example.spec.ts:3:1 › homepage has Playwright in title and get started link linking to the intro page 
[27](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:28)

[28](https://github.com/<ORG>/<REPO>/actions/runs/3217010188/jobs/5259500022#step:6:29)
    TypeError: Cannot read properties of undefined (reading 'mode')
    ...
    ...
```

When I create a new repository and use the exact same test with the same GitHub Action workflow, it works perfectly. Because of this, I understand this is probably not a bug specifically with Playwright, however, I'm looking for some advice on how I can diagnose the issue.

Where is the error: `Cannot read properties of undefined (reading 'mode')` coming from, and what can possibly cause it to happen in my repository when it doesn't happen in a new repository with the exact same code?

Thanks in advance.
