### ISSUE TITLE
[Question] Github Actions test compatibility check failed mitigation?

### ISSUE THREAD

**Issue by hongkiulam** [microsoft/playwright#17955]
I have `"@playwright/test: "^1.26.1"`, defined in my package json and the following in my GHA

```yaml
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: 📦 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: ⏬ Install Dependencies
        run: pnpm install

      - name: 🌐 Install Playwright Browsers
        run: pnpx playwright install --with-deps

      - name: Test
        run: pnpm test
```

But I get this error when installing the browsers

```
╔══════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Playwright Test compatibility check failed:                                                              ║
║ @playwright/test version '1.26.1' does not match playwright version '1.27.0'!                            ║
```

I was hoping that by running `pnpx playwright` it would run the install deps with playwright cli v1.26.1, but even so it downloads v1.27.1 browsers?
Is there any alternative to simple updating the version in package*.json because I imagine this could continue happening and it would be quite annoying to always have to go back and update the version after it fails in CI
