### ISSUE TITLE
[BUG] Failing on "await mount" - undefined: Target closed

### ISSUE THREAD

**Issue by piotrpalek** [microsoft/playwright#18050]
**Context:**
- Playwright Version: 1.26.1
- Operating System: Mac
- Node.js version: 16.13.0
- Browser: All

## System:
 - OS: macOS 12.6
 - Memory: 481.77 MB / 16.00 GB
## Binaries:
 - Node: 16.13.0 - ~/.asdf/installs/nodejs/16.13.0/bin/node
 - Yarn: 1.22.19 - /opt/homebrew/bin/yarn
 - npm: 8.1.0 - ~/.asdf/plugins/nodejs/shims/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Describe the bug**

I'm mounting my component and the test seems to fail at that point with an `undefined: Target closed` error:

![image](https://user-images.githubusercontent.com/1474323/195544889-5bd5e4e5-9b98-4f37-a7fd-c1c4c6ea5e2b.png)

I'm working on a reproduction for this, but couldn't work one out yet. I'd appreciate any pointers as to what could be going on to help me debug this.

**Comment by RikuVan** [comment]
having the same issue with version 1.27.1

**Comment by RikuVan** [comment]
> undefined: Target closed

Actually I downgraded to 1.24.1 and now these seem run work as expected.

**Comment by piotrpalek** [comment]
@RikuVan I've noticed that when I run my code with the `--debug` flag, and then open the browser console there are some errors related to my code (require statements mixed in with my normal import statements). I'm not sure it's the only issue, but for now I need to take care of this.

Anyway it'd be good to get those errors in the test runner as well, since it wasn't very obvious what's going on.

**Comment by yury-s** [comment]
> I'm working on a reproduction for this, but couldn't work one out yet. I'd appreciate any pointers as to what could be going on to help me debug this.

We need a repro to help you. The error is too generic. Please file a new bug once you have a reproducible example.

**Comment by AdrianMachado** [comment]
@yury-s  I am having this issue as well, except I am running within github actions:

```yaml
jobs:
  run_playwright_shard:
    name: Runs Playwright Component tests
    env:
      GITHUB_NPM_TOKEN: ${{ secrets.package_read_token }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
      - name: Install dependencies
        run: npm install
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.package_read_token }}
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --config playwright-ct.config.ts --grep @ct
        env:
          TEST_ACCOUNT_NAME: fuchsia_implicit_bug
          TEST_USER_NAME: ${{ secrets.user_name }}
          TEST_USER_PASSWORD: ${{ secrets.password }}
          ENVIRONMENT_URL: ${{ inputs.deployment_url }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 7
```
