### ISSUE TITLE
[BUG] Cannot run Component Test in github action

### ISSUE THREAD

**Issue by AdrianMachado** [microsoft/playwright#18076]
**Context:**
- Playwright Version: "@playwright/experimental-ct-react": "^1.26.1", "@playwright/test": "^1.26.0"
- I've also tried @next for both, to no avail
- Operating System: Mac, Linux
- Node.js version: v18.10.0
- Browser: All
- Extra: Github Actions

I've been trying to run component tests within Github Actions but I keep running into the same issue on every run
```
1) [chromium] › components/controls/Survey.spec.tsx:6:1 › Survey question flow @ct ===============

    Test timeout of 10000ms exceeded.

    undefined: Target closed

      38 |     },
      39 |   ];
    > 40 |   const component = await mount(
         |                           ^
      41 |     <Survey questions={questions} completionMessage="Survey Complete"></Survey>
      42 |   );
      43 |   // Check survey rendered correctly

        at /home/runner/work/portal/portal/src/components/controls/Survey.spec.tsx:40:27
```

**My Test**

```typescript
import { expect, test } from "@playwright/experimental-ct-react";
import Survey from "./Survey";

test.use({ viewport: { width: 1920, height: 1080 } });

test("Survey question flow @ct", async ({ mount, page }) => {
  const questions = [
    {
      question: "Question 1",
      answers: [
        {
          text: "Option One",
          code: "Q1_ONE",
        },
      ],
    }
  ];
  const component = await mount(
    <Survey questions={questions} completionMessage="Survey Complete"></Survey>
  );
  // Check survey rendered correctly
  await expect(component).toContainText(questions[0].question);
});
```

**My Github Action**
This action gets invoked after my React app is built and deployed, running on `ubuntu-latest` and `node-version: "18.x"`
```yaml
name: Run Playwright Test Shard

on:
  workflow_call:
    inputs:
      deployment_url:
        required: true
        type: string
    secrets:
      package_read_token:
        required: true

jobs:
  run_playwright_shard:
    name: Runs Playwright Component tests
    env:
      GITHUB_NPM_TOKEN: ${{ secrets.package_read_token }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.package_read_token }}
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --config playwright-ct.config.ts --grep @ct
        env:
          ENVIRONMENT_URL: ${{ inputs.deployment_url }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 7

```

**My Playwright Config**
```typescript
import type { PlaywrightTestConfig } from "@playwright/experimental-ct-react";
import { devices } from "@playwright/experimental-ct-react";
import react from "@vitejs/plugin-react";
import tsconfigPaths from "vite-tsconfig-paths";

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// eslint-disable-next-line @typescript-eslint/no-var-requires
require("dotenv").config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
const config: PlaywrightTestConfig = {
  testDir: "./src",
  /* The base directory, relative to the config file, for snapshot files created with toMatchSnapshot and toHaveScreenshot. */
  snapshotDir: "./__snapshots__",
  /* Maximum time one test can run for. */
  timeout: 10 * 1000,
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 4 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: process.env.CI ? [["github"], ["html"]] : [["html"]],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: "on-first-retry",
    /* Port to use for Playwright component endpoint. */
    ctPort: 3100,
    /* Screenshots taken when a test failure occurs */
    screenshot: "only-on-failure",
    /* Retain a copy of the test failure video to aid in debugging */
    video: "retain-on-failure",
    ctViteConfig: {
      build: {
        target: "es5",
      },
      plugins: [tsconfigPaths(), react()],
      envDir: "./",
      define: {
        "process.env": process.env,
      },
    },
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
      },
    },
  ],
  /* Folder for test artifacts such as screenshots, videos, traces, etc. */
  outputDir: "./test-results",
};

export default config;
```

**Describe the bug**

This only seems to happen when running on github actions. I can run this fine locally on my Macbook and the test passes.
