### ISSUE TITLE
[BUG] Github actions failed when install `npm ci`

### ISSUE THREAD

**Issue by kthiha-dev** [microsoft/playwright#18311]
**Context:**
- Playwright Version: [1.27.1]
- Operating System: [Mac]
- Node.js version: [18.11.0]
- Browser: [All]
- Extra: [CI/CD Pipeline, Workflow, Github Actions
![Screenshot at Oct 25 11-54-52](https://user-images.githubusercontent.com/3499681/197689631-2958034a-1c7c-477a-9281-7f73ba0cda54.png)
]

**Code Snippet**

I added new step in my existing pipeline

```yml
 playwright-test:
    needs: deploy
    name: Running Playwright's Test
    timeout-minutes: 60
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      # - name: Run Playwright tests
      #   run: npx playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
```

**Describe the bug**

And I got this error on log

```
Run npm ci
  npm ci
  shell: /usr/bin/bash -e {0}
npm ERR! Invalid Version: file:src/tool

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/[2] //my log file path
Error: Process completed with exit code 1.
```
