### ISSUE TITLE
Hook to trigger once HTML report has been created successfully

### ISSUE THREAD

**Issue by bhavarthkandoria** [microsoft/playwright#18951]
Basically, I want to a feature where I can upload my reporting artifacts or full 'playwright-report' directory to some storage where everyone from the team can refer it.

I am looking for the hook which will trigger once HTML report is created successfully. Currently, I am trying to achieve the same by putting the code in teardown script. But it is not working as I want.

**Comment by dgozman** [comment]
@bhavarthkandoria We recommend a separate step in your CI config. For example, playwright CI uploads some artifacts after [test run here](https://github.com/microsoft/playwright/blob/main/.github/workflows/tests_primary.yml#L61-L65).

An example of doing this for GitHub Actions, assuming default `playwright-report` location:

```yaml
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report
```

Let me know if this helps.
