### ISSUE TITLE
[BUG] Playwright 1.28 not working in GitHub actions

### ISSUE THREAD

**Issue by andrico1234** [microsoft/playwright#19234]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Ubuntu-latest
- Node.js version: 16.x
- Browser: Webkit
- Extra:

Here's a snippet of a GitHub action that fails:

```
jobs:
  build:
    name: Verify build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn --immutable
      - run: npx playwright install --with-deps
      - run: yarn test
```

I get the following error when installing:

```
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

When the tests run, both Firefox and Chrome pass, but WebKit fails.

You can view the entire results [here](https://github.com/andrico1234/a2k/actions/runs/3602265109/jobs/6069015110#step:11:59)

When I change the playwright install script to install 1.27, I have no issues. You can view the passing pipeline [here](https://github.com/andrico1234/a2k/actions/runs/3602527759)
