### ISSUE TITLE
[Question] How to run on Github with the same number of workers assigned in my local?

### ISSUE THREAD

**Issue by YusufOzt** [microsoft/playwright#19757]
I don't set any fullyParallel mode and others .I am only using Playwright's default mode.Tests run with default mode according to `npx playwright test` logic.

My main question is: When I run 20 tests in my local, playwright automatically sets 2 workers. But when it works on Github Actions, Playwright sets 1 worker for 20 tests.I want it to work on Github with the same number of workers assigned in my local.

On GitHub  automatically sets only 1 worker, but on my local automatically sets more workers.How to run on Github with the same number of workers assigned in my local?

**My local behaviour;**
`Running 20 tests using 2 workers`

**GitHub behaviour;**
`Running 20 tests using 1 workers`

**My package.json;**
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "pw:test": "ENV=1 NAME=test@gmail.com PASS=test npx playwright test"
  },
  "author": "Yusuf",
  "license": "ISC",
  "devDependencies": {
    "@faker-js/faker": "^7.6.0",
    "@playwright/test": "^1.29.0",
    "allure-commandline": "^2.20.1",
    "allure-playwright": "^2.0.0-beta.21",
    "axios": "^0.27.2",
    "playwright": "^1.24.0"
  },
  "dependencies": {
    "@openapitools/openapi-generator-cli": "^1.0.8-4.2.2",
    "cross-env": "^7.0.3",
    "form-data": "^4.0.0",
    "moment": "^2.29.4",
    "moment-timezone": "^0.5.34"
  }
}
```

**my yml file;**

```
name: Stage - Playwright Regression Tests

on:
  schedule:
    - cron:  '30 19 * * 1-5' 
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       ref: test
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run pw:test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
```

**my playwrgiht.config.ts**

```
import { type PlaywrightTestConfig, devices } from "@playwright/test";
const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./global-setup'),
  globalTeardown: './global-teardown.ts',

  timeout: 30 * 1000,
  expect: {
    timeout: 10000
  },
  reporter: [['html', { outputFolder: 'report' }]],
  use: {
    headless: true,
    baseURL: process.env.ENV === '1' ? 'https://test1' : process.env.ENV === '2' ? 'https://test2' : 'https://test3',
    storageState: 'fixtures/common/state.json',
    ignoreHTTPSErrors: true
  },
  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
        launchOptions: {
          args: ["--disable-web-security"],

        },
        headless:true
        
      },
    },
  ],
};
export default config;
```

**my global-setup.ts**

```
import LgnPageRepository from "./playwright/login"
import { chromium, FullConfig } from '@playwright/test';

async function globalSetup(config: FullConfig) {
    const { baseURL, storageState, headless } = config.projects[0].use;
    const browser = await chromium.launch({ headless });
    const page = await browser.newPage();
    await page.goto(`${baseURL}`)
    await page.locator(LgnPageRepository.emailTextField).type(process.env.NAME!)
    await page.locator(LgnPageRepository.passwordTextField).type(process.env.PASS!)
    await page.locator(LgnPageRepository.loginButton).click()
    await page.waitForTimeout(1000)
    await page.context().storageState({ path: storageState as string });
    await browser.close();

}
export default globalSetup;
```
