### ISSUE TITLE
[BUG]: The webserver in Github Actions does not work because it does not inherit the environment variables by default

### ISSUE THREAD

**Issue by EgonBolton** [microsoft/playwright#19780]
**Context:**
- Playwright Version: "@playwright/test": "^1.28.1",
- Operating System: Windows 11
- Node.js version: 16.13.0
- Browser: All

**Code Snippet**

This is my `playwright.config.ts`

```javascript
import type { PlaywrightTestConfig } from "@playwright/test";
import { devices } from "@playwright/test";

const config: PlaywrightTestConfig = {
  testDir: "./src",
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 1,
  reporter: process.env.CI ? "github" : "html",
  use: {
    baseURL: process.env.VERCEL_URL
      ? `https://${process.env.VERCEL_URL}`
      : `http://localhost:${process.env.PORT ?? 3000}`,
    navigationTimeout: 10 * 1000,
    trace: "on-first-retry",
  },
  projects: [
    { name: "chromium", use: { ...devices["Desktop Chrome"] } },
    { name: "firefox", use: { ...devices["Desktop Firefox"] } },
    { name: "webkit", use: { ...devices["Desktop Safari"] } },
    { name: "Mobile Chrome", use: { ...devices["Pixel 5"] } },
    { name: "Mobile Safari", use: { ...devices["iPhone 12"] } },
  ],
  webServer: process.env.CI
    ? {
        command: "npm run start",
        port: 3000,
        reuseExistingServer: true,
      }
    : undefined,
};

export default config;
```

And this is my GitHub workflow (the one that comes by default):

```yml
name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
```

**Describe the bug**
GitHub Actions throws me this error in the `npx playwright test` command:

> [WebServer] ❌ Invalid environment variables:
> // my env vars...

Based on what I read in the documentation, webserver should inherit environment variables from process.env. So, what is the reason for this error?

EDIT: I am using Vercel's environment variables. I also have the "Automatically expose System Environment Variables" option enabled.

Thanks!
