### ISSUE TITLE
[Question] How to solve github action error?

### ISSUE THREAD

**Issue by YusufOzt** [microsoft/playwright#19941]
I used the GitHub Actions (via containers) to make my code work on CI .But gotting below error every time on GitHub Action.How can I solve?

```
Error: EACCES: permission denied, open 'fixtures/common/state.json'

Error in reporter [Error: EACCES: permission denied, copyfile '/__w/playwright-framework/playwright-framework/node_modules/@playwright/test/node_modules/playwright-core/lib/webpack/htmlReport/index.html' -> '/__w/playwright-framework/pisano-playwright-framework/report/index.html'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'copyfile',
  path: '/__w/playwright-framework/playwright-framework/node_modules/@playwright/test/node_modules/playwright-core/lib/webpack/htmlReport/index.html',
  dest: '/__w/playwright-framework/playwright-framework/report/index.html'
}
Error: Process completed with exit code 1.
```

**This is global-setup.ts**
```
import LoginPageRepository from "./playwright/pages/login"
import { chromium, FullConfig } from '@playwright/test';

async function globalSetup(config: FullConfig) {
    const { baseURL, storageState, headless } = config.projects[0].use;
    const browser = await chromium.launch({ headless });
    const page = await browser.newPage();
    await page.goto(`${baseURL}`)
    await page.locator(LoginPageRepository.emailTextField).type(process.env.NAME!)
    await page.locator(LoginPageRepository.passwordTextField).type(process.env.PASS!)
    await page.locator(LoginPageRepository.loginButton).click()
    await page.waitForTimeout(1000)
    await page.context().storageState({ path: storageState as string });
    await browser.close();

}
export default globalSetup;
```

**This is playwright.config.ts**

```
import { type PlaywrightTestConfig} from "@playwright/test";
const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./global-setup'),
  globalTeardown: './global-teardown.ts',

  timeout: 30 * 1000,
  expect: {
    timeout: 30000
  },
  reporter: [['html', { outputFolder: 'report' }]],
  use: {
    headless: true,
    baseURL: process.env.ENV === '1' ? 'https://test1' : process.env.ENV === '2' ? 'https://test2' : 'https://test3',
    storageState: 'fixtures/common/state.json',
    ignoreHTTPSErrors: true
  },
  projects: [
    {
      name: "chromium",
      use: {
        browserName: "chromium",
        viewport:null,
        launchOptions: {
          args: ["--disable-web-security", "--start-maximized"],

        },
        
      },
    },
  ],
};
export default config;
```

**This is npm-publish.yml file** 

```
on:
  push:
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.29.0-focal
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright tests
      run: npm run pw:test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: report/**
        retention-days: 30
```
