### ISSUE TITLE
[Question] How to generate report in AWS

### ISSUE THREAD

**Issue by mandeepmm1** [microsoft/playwright#20248]
I have executed the scripts on AWS and build run successfully. Could anyone please guide me how can i generate the report or logs in pdf or other format so that i could share it with the client.

Buildspec files which i configured on AWS:

```
version: 0.2

phases:
  build:
    commands:
       - npm install && npx playwright install && npm run test:all 
```

**Comment by yury-s** [comment]
You can configure playwright to generate [HTML report](https://playwright.dev/docs/intro#html-test-reports) of the test run. You'll need to configure your AWS build step to upload the report after running tests, so that it can be shared with others. We have [an example](https://playwright.dev/docs/ci-intro) of how it can be done with GitHub Actions:

```yml
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
```
you'll need to have a similar configuration for AWS build. The html report is a single html file (`playwright-report/index.html`), no other resources needed.
