### ISSUE TITLE
[REGRESSION]: getting page.goto: net::ERR_CONNECTION_REFUSED at http://localhost:3002/ error when running on circleci

### ISSUE THREAD

**Issue by alexkyrylenkoproven** [microsoft/playwright#20343]
**Context:**
Working with playwright 27
Does not work with playwright 28 and 29 

**Code Snippet**

```
await page.goto("https://www.google.com");
```
config.yml
```
executors:
  playwright-image:
    working_directory: ~/repo
    docker:
      - image: mcr.microsoft.com/playwright:v1.27.0-focal
    environment:
      NODE_ENV: development # Needed if playwright is in `devDependencies`
```
package.json
```
    "@playwright/test": "1.27.0"
    "playwright": "1.27.0"
```
playwright.config.js
```
baseURL:  `http://localhost:3002`
...
 webServer: {
    command: `npm run start`,
    port: 3002,
    timeout: 300 * 1000,
    reuseExistingServer: true
  }
```

**Describe the bug**

When running in circleci, all the test that are running after the first failed test are throwing  getting page.goto: net::ERR_CONNECTION_REFUSED at http://localhost:3002/ exception. Working fine with version 27 and bellow. Works fine on a local machine with any version of playwright. Not sure if it works or not on the rest supported ci tools. 
Seems like the server crashes after the first failed test so all the subsequent tests fail with this error
