### ISSUE TITLE
Is visual regression test possible in github action workflow?

### ISSUE THREAD

**Issue by student513** [microsoft/playwright#20391]
Hi, I want to implement test automation with github action ci. After running the first test to create the baseline snapshot, it would be a common process to perform a visual regression test with the comparison snapshot that is generated in the second test. However, baseline snapshot does not exist because a new environment is created every time github action is run. How can I test it?

playwright.config.ts
```
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
  testDir: './tests',
  timeout: 2 * 60 * 1000,
  expect: {
    timeout: 60 * 1000,
  },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  workers: 4, //process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: 'http://localhost:3005',
    trace: 'retain-on-failure',
    video: 'retain-on-failure',
  },

  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],

  webServer: {
    command: 'yarn dev:test',
    port: 3005,
  },
};

export default config;
```

playwright.yml
```
name: Playwright Tests
on: pull_request

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Install Playwright Browsers
        run: npx playwright@1.28.1 install --with-deps chromium
        working-directory: ./apps/siesta-test
      - name: Run Playwright tests
        run: yarn playwright test
        working-directory: ./apps/siesta-test
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: ./apps/siesta-test/playwright-report
          retention-days: 30
```
