### ISSUE TITLE
[BUG] npx playwright test --debug is not working from Gitlab CI

### ISSUE THREAD

**Issue by adarshTS** [microsoft/playwright#20436]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: 18.11.9
- Browser: chrome
- Extra: Im trying to setup a Gitlab pipeline and running my tests from Gitlab CI

**Code Snippet**

This is how my pipeline configuration in Gitlab looks like:

```
stages:         
  - test

tests:       
  stage: test
  image: mcr.microsoft.com/playwright:v1.27.1-focal
  script:
    - curl -sL https://deb.nodesource.com/setup_18.x | bash -
    - apt-get install -y nodejs
    - npm i
    - npx playwright install chrome
    - npx playwright test --debug
```

**This is the log that i see in Gitlab:**

```
browserType.connect: Browser has been closed
      17 |
      18 | test('firstTest',async () => {
    > 19 |   const browser = await chromium.connect({
         |                                  ^
      20 |     wsEndpoint: `wss://cdp.browserstack.com/playwright?caps=${encodeURIComponent(JSON.stringify(caps))}`});
      21 |   const page = await browser.newPage();
      22 |   await page.goto("https://bstackdemo.com/");
        at /builds/adarshTS/playwright-browserstack-sample/tests/firstTest.spec.js:19:34
  1 failed
    firstTest.spec.js:18:1 › firstTest 
```

Im not able to find the entire stack trace, this works fine locally on my device. But fails on Gitlab.
