### ISSUE TITLE
[BUG] How to cache playwright OS binaries in github actions?

### ISSUE THREAD

**Issue by rohitkrishna094** [microsoft/playwright#20603]
### Context:
- Playwright Version: 1.30
- Operating System: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
- Node.js version: v16.19.0
- Browser: default browsers(as installed by running `npx playwright install --with-deps`
- Extra: Running on github actions(using **ubuntu-latest**)

**npx envinfo --preset playwright --markdown**
```bash
## System:
 - OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
 - Memory: 5.92 GB / 6.[7](https://github.com/rohitkrishna094/playwright-test/actions/runs/4079755466/jobs/7031455068#step:4:8)[8](https://github.com/rohitkrishna094/playwright-test/actions/runs/4079755466/jobs/7031455068#step:4:9) GB
 - Container: Yes
## Binaries:
 - Node: 16.1[9](https://github.com/rohitkrishna094/playwright-test/actions/runs/4079755466/jobs/7031455068#step:4:10).0 - /opt/hostedtoolcache/node/16.19.0/x64/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 8.19.3 - /opt/hostedtoolcache/node/16.19.0/x64/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/bin/bash
```

---

### Code Snippet

I created a default project as mentioned in the docs by running `npm init playwright@latest`. The below is one of the code snippets/specs that the above command generates as of today.

```javascript
// @ts-check
const { test, expect } = require('@playwright/test');

test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});

test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*intro/);
});
```

Also consider the below github actions workflow file and also corresponding github actions [logs](https://github.com/rohitkrishna094/playwright-test/actions/runs/4079755466/jobs/7031455068)

```yml
name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Print system info
        run: npx envinfo --preset playwright --markdown

      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Cache Playwright binaries
        uses: actions/cache@v3
        id: cache-playwright
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Playwright Browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
```

---
### Describe the bug
I am trying to cache playwright binaries(which are downloaded as part of the command `npx playwright install --with-deps`. However this doesn't seem to work with OS related files. This is the error that I get when running `npx playwright test`.

<details>
<summary>Expand this to see the full error log</summary>

```
1) [webkit] › example.spec.js:4:1 › has title ====================================================

    browserType.launch: 
    ╔══════════════════════════════════════════════════════╗
    ║ Host system is missing dependencies to run browsers. ║
    ║ Please install them with the following command:      ║
    ║                                                      ║
    ║     sudo npx playwright install-deps                 ║
    ║                                                      ║
    ║ Alternatively, use apt:                              ║
    ║     sudo apt-get install libvpx7\                    ║
    ║         libevent-2.1-7\                              ║
    ║         libopus0\                                    ║
    ║         libwoff1\                                    ║
    ║         libharfbuzz-icu0\                            ║
    ║         libgstreamer-plugins-base1.0-0\              ║
    ║         libgstreamer-gl1.0-0\                        ║
    ║         libhyphen0\                                  ║
    ║         libmanette-0.2-0\                            ║
    ║         libgles2\                                    ║
    ║         gstreamer1.0-libav                           ║
    ║                                                      ║
    ║ <3 Playwright Team                                   ║
    ╚══════════════════════════════════════════════════════╝

    Retry #1 ---------------------------------------------------------------------------------------

    browserType.launch: 
    ╔══════════════════════════════════════════════════════╗
    ║ Host system is missing dependencies to run browsers. ║
    ║ Please install them with the following command:      ║
    ║                                                      ║
    ║     sudo npx playwright install-deps                 ║
    ║                                                      ║
    ║ Alternatively, use apt:                              ║
    ║     sudo apt-get install libvpx7\                    ║
    ║         libevent-2.1-7\                              ║
    ║         libopus0\                                    ║
    ║         libwoff1\                                    ║
    ║         libharfbuzz-icu0\                            ║
    ║         libgstreamer-plugins-base1.0-0\              ║
    ║         libgstreamer-gl1.0-0\                        ║
    ║         libhyphen0\                                  ║
    ║         libmanette-0.2-0\                            ║
    ║         libgles2\                                    ║
    ║         gstreamer1.0-libav                           ║
    ║                                                      ║
    ║ <3 Playwright Team                                   ║
    ╚══════════════════════════════════════════════════════╝

    Retry #2 ---------------------------------------------------------------------------------------

    browserType.launch: 
    ╔══════════════════════════════════════════════════════╗
    ║ Host system is missing dependencies to run browsers. ║
    ║ Please install them with the following command:      ║
    ║                                                      ║
    ║     sudo npx playwright install-deps                 ║
    ║                                                      ║
    ║ Alternatively, use apt:                              ║
    ║     sudo apt-get install libvpx7\                    ║
    ║         libevent-2.1-7\                              ║
    ║         libopus0\                                    ║
    ║         libwoff1\                                    ║
    ║         libharfbuzz-icu0\                            ║
    ║         libgstreamer-plugins-base1.0-0\              ║
    ║         libgstreamer-gl1.0-0\                        ║
    ║         libhyphen0\                                  ║
    ║         libmanette-0.2-0\                            ║
    ║         libgles2\                                    ║
    ║         gstreamer1.0-libav                           ║
    ║                                                      ║
    ║ <3 Playwright Team                                   ║
    ╚══════════════════════════════════════════════════════╝

  2) [webkit] › example.spec.js:[11](https://github.com/rohitkrishna094/playwright-test/actions/runs/4079755466/jobs/7031455068#step:9:12):1 › get started link ============================================

    browserType.launch: 
    ╔══════════════════════════════════════════════════════╗
    ║ Host system is missing dependencies to run browsers. ║
    ║ Please install them with the following command:      ║
    ║                                                      ║
    ║     sudo npx playwright install-deps                 ║
    ║                                                      ║
    ║ Alternatively, use apt:                              ║
    ║     sudo apt-get install libvpx7\                    ║
    ║         libevent-2.1-7\                              ║
    ║         libopus0\                                    ║
    ║         libwoff1\                                    ║
    ║         libharfbuzz-icu0\                            ║
    ║         libgstreamer-plugins-base1.0-0\              ║
    ║         libgstreamer-gl1.0-0\                        ║
    ║         libhyphen0\                                  ║
    ║         libmanette-0.2-0\                            ║
    ║         libgles2\                                    ║
    ║         gstreamer1.0-libav                           ║
    ║                                                      ║
    ║ <3 Playwright Team                                   ║
    ╚══════════════════════════════════════════════════════╝

    Retry #1 ---------------------------------------------------------------------------------------

    browserType.launch: 
    ╔══════════════════════════════════════════════════════╗
    ║ Host system is missing dependencies to run browsers. ║
    ║ Please install them with the following command:      ║
    ║                                                      ║
    ║     sudo npx playwright install-deps                 ║
    ║                                                      ║
    ║ Alternatively, use apt:                              ║
    ║     sudo apt-get install libvpx7\                    ║
    ║         libevent-2.1-7\                              ║
    ║         libopus0\                                    ║
    ║         libwoff1\                                    ║
    ║         libharfbuzz-icu0\                            ║
    ║         libgstreamer-plugins-base1.0-0\              ║
    ║         libgstreamer-gl1.0-0\                        ║
    ║         libhyphen0\                                  ║
    ║         libmanette-0.2-0\                            ║
    ║         libgles2\                                    ║
    ║         gstreamer1.0-libav                           ║
    ║                                                      ║
    ║ <3 Playwright Team                                   ║
    ╚══════════════════════════════════════════════════════╝

    Retry #2 ---------------------------------------------------------------------------------------

    browserType.launch: 
    ╔══════════════════════════════════════════════════════╗
    ║ Host system is missing dependencies to run browsers. ║
    ║ Please install them with the following command:      ║
    ║                                                      ║
    ║     sudo npx playwright install-deps                 ║
    ║                                                      ║
    ║ Alternatively, use apt:                              ║
    ║     sudo apt-get install libvpx7\                    ║
    ║         libevent-2.1-7\                              ║
    ║         libopus0\                                    ║
    ║         libwoff1\                                    ║
    ║         libharfbuzz-icu0\                            ║
    ║         libgstreamer-plugins-base1.0-0\              ║
    ║         libgstreamer-gl1.0-0\                        ║
    ║         libhyphen0\                                  ║
    ║         libmanette-0.2-0\                            ║
    ║         libgles2\                                    ║
    ║         gstreamer1.0-libav                           ║
    ║                                                      ║
    ║ <3 Playwright Team                                   ║
    ╚══════════════════════════════════════════════════════╝


  2 failed
    [webkit] › example.spec.js:4:1 › has title =====================================================
    [webkit] › example.spec.js:11:1 › get started link =============================================
```
</details>

---

### What did I try
According to this Issue [#17975](https://github.com/microsoft/playwright/issues/17975):

> Playwright does not support Mint - only Ubuntu and Debian are supported

But it doesnt work even when I am using ubuntu-latest in my github actions. However the op resolved the issue by removing devices and using channel. But what if I want to use the default devices and make it work?
