### ISSUE TITLE
`Test timeout of 120000ms exceeded while tearing down "context".` in github action ci

### ISSUE THREAD

**Issue by student513** [microsoft/playwright#20648]
version: "@playwright/test": "1.28.1",

Hi, I  tested a visual regression test in github action ci. I wrote the following yml file by referring to the docs.
I want to run the test in macos, not in ubuntu. However, the following error occurs in github action console.
This error does not occur if runner is set to ubuntu in github action. Also, it has never been found in a local environment.
I have read the issues written about the same error, but I have not found any significant results.

How do I solve this problem?

<img width="708" alt="스크린샷 2023-02-06 오후 2 29 35" src="https://user-images.githubusercontent.com/50268619/216891008-7839e730-b075-42a8-8192-686aca6e823c.png">

playwight.yml
```
name: Playwright Tests
on: pull_request

jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Install Playwright Browsers
        run: npx playwright@1.28.1 install --with-deps chromium
        working-directory: ./apps/siesta-test
      - name: Run Playwright tests
        run: yarn playwright test
        working-directory: ./apps/siesta-test
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: ./apps/siesta-test/playwright-report
          retention-days: 30
```

### test code
```
 test('my test', async ({ page }, testInfo) => {
    testInfo.snapshotSuffix = '';
    await drawSinglePolygon(page);
    await page.keyboard.press('Shift+Quote');
    await page.keyboard.press('KeyP');
    await page.keyboard.press('KeyA');

    const fontSizeAdjustments = await page.locator("[aria-label='adjustments item']").nth(5);
    await expect(fontSizeAdjustments).toBeVisible();
    await fontSizeAdjustments.fill('15');

    await expect(await page.locator('canvas').screenshot()).toMatchSnapshot();
```
### config
```
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
  testDir: './tests',
  timeout: 3 * 60 * 1000,
  expect: {
    timeout: 60 * 1000,
  },
  fullyParallel: true,
  forbidOnly: false, //!!process.env.CI,
  workers: 4, //process.env.CI ? 1 : undefined,
  reporter: 'html',

  use: {
    baseURL: 'http://localhost:3005',
    trace: 'retain-on-failure',
    video: 'retain-on-failure',
  },

  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],

  webServer: {
    command: 'yarn dev:test',
    port: 3005,
  },
};

export default config;
