### ISSUE TITLE
[BUG] Error whilst attempting to install Playwright with dependencies using Yarn

### ISSUE THREAD

**Issue by hreynier** [microsoft/playwright#20678]
**Context:**
- Playwright Version: 1.30, with Playwright/experimental-ct-react: 1.30
- Operating System: Ubuntu 22.04 LTS
- Node.js version: 14.19
- Browser: [Chromium, Firefox, WebKit]
- Extra: <This is running fine locally but fails during CI with the Github Action Workflow below>
**Code Snippet**

```yaml
name: Playwright Visual Regression Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches:
      - '*'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set-up node
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          npm install -g yarn && yarn install --frozen-lockfile
      - name: Install Playwright Browsers
        run: yarn playwright install  --with-deps
      - name: Run Playwright Visual Regression Tests
        run: yarn run playwright test -c playwright-ct.config.ts && npx playwright show-report
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
```

**Describe the bug**

This error occurs when trying to install and run these Playwright tests in CI using Github Actions.
The action fails during the *Install Playwright Browsers* step with 
`yarn playwright install --with-deps`.
I get the following error:

```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/libpostproc55_4.4.2-0ubuntu0.22.04.1_amd64.deb  Connection failed [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/q/qrencode/libqrencode4_4.1.1-1_amd64.deb  Could not connect to azure.archive.ubuntu.com:80 (20.106.104.242), connection timed out [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/s/soundtouch/libsoundtouch1_2.3.1%2bds1-1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/s/spandsp/libspandsp2_0.0.6%2bdfsg-2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/libs/libsrtp2/libsrtp2-1_2.4.2-2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/w/webrtc-audio-processing/libwebrtc-audio-processing1_0.3.1-0ubuntu5_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/w/wildmidi/libwildmidi2_0.4.3-1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/w/woff2/libwoff1_1.0.2-1build4_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/z/zbar/libzbar0_0.23.92-4build2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/z/zxing-cpp/libzxingcore1_1.2.0-1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/x/xfonts-encodings/xfonts-encodings_1.0.5-0ubuntu2_all.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
Failed to install browsers
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/x/xfonts-utils/xfonts-utils_7.7%2b6build2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
Error: Installation process exited with code: 100
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/x/xfonts-cyrillic/xfonts-cyrillic_1.0.5_all.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/x/xfonts-scalable/xfonts-scalable_1.0.3-1.2ubuntu1_all.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/x/xorg-server/xserver-common_21.1.3-2ubuntu2.6_all.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/x/xorg-server/xvfb_21.1.3-2ubuntu2.6_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/libd/libdca/libdca0_0.0.7-2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/g/gst-plugins-bad1.0/libgstreamer-plugins-bad1.0-0_1.20.3-0ubuntu1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/sbc/libsbc1_1.5-3build2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/v/vo-aacenc/libvo-aacenc0_0.1.3-2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/v/vo-amrwbenc/libvo-amrwbenc0_0.1.3-2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/g/gst-plugins-bad1.0/gstreamer1.0-plugins-bad_1.20.3-0ubuntu1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libg/libglvnd/libgles2_1.4.0-1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libg/libglvnd/libopengl0_1.4.0-1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

Interestingly, when I remove the `--with-deps` flag, the installation process works but my tests fail because `-webkit` browsers aren't installed.
