### ISSUE TITLE
[BUG]: Playwright doesn't work on github actions failing because  no such file or directory, stat '/home/runner/.cache/ms-playwright/webkit-1767/minibrowser-gtk/lib/libWPEBackend-fdo-1.0.so'

### ISSUE THREAD

**Issue by 0xHexE** [microsoft/playwright#20818]
**Context:**
## System:
 - OS: Linux 6.1 Arch Linux
 - Container: Yes
## Binaries:
 - Node: 19.6.0 - /tmp/xfs-8861711c/node
 - Yarn: 3.3.1 - /tmp/xfs-8861711c/yarn
 - npm: 8.19.2 - /usr/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/bin/bash
 - Playwight: 1.30.0

**Code Snippet**
```yml
name: Playwright Tests
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose -f "PATH_TO_DOCKER_COMPOSE" up -d
      - name: configure host file
        run: |
          # Internal mapping for /etc/hosts
          sudo echo "127.0.0.1 X.X.local" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 X.X.local" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 X.X.local" | sudo tee -a /etc/hosts
      - name: install caddy
        run: |
          # This is temporary installation of caddy
          wget https://github.com/caddyserver/caddy/releases/download/v2.6.3/caddy_2.6.3_linux_amd64.tar.gz
          tar xf caddy_2.6.3_linux_amd64.tar.gz
          sudo mv caddy /usr/bin
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: yarn install --immutable
        name: "Yarn install"
        env:
          NPM_TOKEN: ${{ github.token }}
      - name: package deps
        run: |
          # Tried to fix by installing this packages
          sudo apt update
          sudo apt-get install libegl1\
                        libopus0\
                        libwoff1\
                        libharfbuzz-icu0\
                        gstreamer1.0-plugins-base\
                        libgstreamer-gl1.0-0\
                        gstreamer1.0-plugins-bad\
                        libopenjp2-7\
                        libwebpdemux2\
                        libhyphen0\
                        libgles2\
                        gstreamer1.0-libav\
                        libwpebackend-fdo-1.0-1
      - name: Playwright deps install
        run: |
          yarn playwright-install      # "playwright-install": "pnpify playwright install --with-deps",
          yarn playwright-webkit     # "playwright-webkit": "pnpify playwright install-deps webkit"
      - name: Run Playwright tests
        run: yarn playwright
      - name: Stop containers
        if: always()
        run: docker-compose -f "PATH_TO_DOCKER_COMPOSE" down
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

```

**Describe the bug**

```
    browserType.launch: ENOENT: no such file or directory, stat '/home/runner/.cache/ms-playwright/webkit-1767/minibrowser-gtk/lib/libWPEBackend-fdo-1.0.so'

    Retry #1 ---------------------------------------------------------------------------------------

    browserType.launch: ENOENT: no such file or directory, stat '/home/runner/.cache/ms-playwright/webkit-1767/minibrowser-gtk/lib/libWPEBackend-fdo-1.0.so'

    Retry #2 ---------------------------------------------------------------------------------------

    browserType.launch: ENOENT: no such file or directory, stat '/home/runner/.cache/ms-playwright/webkit-1767/minibrowser-gtk/lib/libWPEBackend-fdo-1.0.so'
```
