### ISSUE TITLE
[BUG] Fails in Github Action Workflow, Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by hreynier** [microsoft/playwright#21048]
**Context:**
- Playwright Version: ^1.30.0
- Operating System: Mac
- Node.js version: 19.5.0
- Browser: All
- Extra: Using npm workspaces in my repository

## System:
 - OS: macOS 13.2.1
 - Memory: 362.36 MB / 32.00 GB
## Binaries:
 - Node: 19.5.0 - /opt/homebrew/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 9.3.1 - /opt/homebrew/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet//Bug Description**
I can run my playwright tests locally using this script in one of my workspaces

```javascript
 "test:web-import-visual": "playwright test -c playwright-visual.config.ts && npx playwright show-report",
```

But when I try to run this in a workflow through github actions, I get a very nondescript error
`Error: Process completed with exit code 1.`

The workflow file.
```yaml
name: Visual Regression Tests
on:
  pull_request:
    branches:
      - '*'
jobs:
  Visual-Regression-Test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set-up node
        uses: actions/setup-node@v3
        with:
          node-version: '19.5.0'
      - name: Install dependencies
        run: |
          npm install
          (cd backend/multiplayer-server && npm install)
          (cd frontend && npm install)
      - name: Install Playwright Browsers
        run: |
          cd shared/document
          npx playwright install --with-deps
      - name: Run Playwright Visual Regression Tests
        run: cd shared/document && npx playwright test -c playwright-visual.config.ts
      - name: Check test output against baseline
        run: |
          total_tests_current=$(grep "Total Tests in Suite:" test-summary/summary.txt | awk '{print $5}')
          failed_tests_current=$(grep "Tests Failed:" test-summary/summary.txt | awk '{print $3}')
          total_tests_baseline=$(grep "Total Tests in Suite:" test-summary/baseline.txt | awk '{print $5}')
          failed_tests_baseline=$(grep "Tests Failed:" test-summary/baseline.txt | awk '{print $3}')
          if [ "$failed_tests_current" -gt "$failed_tests_baseline" ] && [ "$total_tests_current" -eq "$total_tests_baseline" ]; then
              echo "Total tests ran: $total_tests_current, Total ran yesterday: $total_tests_baseline ."
              echo "More tests failed than expected: $failed_tests_current, expected: $failed_tests_baseline ."
              echo "Marked as failed due to regression in passing tests."
              exit 1
          elif [ "$total_tests_current" -ne "$total_tests_baseline" ]; then
              echo "Total tests ran is different that expected: $total_tests_current, expected: $total_tests_baseline ."
              echo "Failed tests: $failed_tests_current, expected: $failed_tests_baseline ."
              echo "Marked as passing due to changed number of tests."
              exit 0
          else
              echo "Total tests ran: $total_tests_current, expected: $total_tests_baseline ."
              echo "Failed tests: $failed_tests_current, expected: $failed_tests_baseline ."
              echo "Marked as passing."
              exit 0
          fi
      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: shared/document/playwright-report
          retention-days: 30
```

My config file is as so:

```javascript
const config: PlaywrightTestConfig = {
  testDir: './testing/import-export/web/',
  /* The base directory, relative to the config file, for snapshot files created with toMatchSnapshot and toHaveScreenshot. */
  snapshotDir: './testing/import-export/web/snapshots',
  /* Maximum time one test can run for. */
  timeout: process.env.CI ? 30 * 1000 : 10 * 1000,
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  // forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 1 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [
    [
      '@skilbourn/playwright-report-summary',
      {
        outputFile: './testing/import-export/web/test-summary/summary.txt',
        inputTemplate: CustomReport,
      },
    ],
    ['html', { open: 'never' }],
  ],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',

    /* Port to use for Playwright component endpoint. */
    ctPort: 3100,
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
    {
      name: 'firefox',
      use: {
        ...devices['Desktop Firefox'],
      },
    },
    {
      name: 'webkit',
      use: {
        ...devices['Desktop Safari'],
      },
    },
  ],
};

export default config;
```

I'm fairly new to Playwright and Github Actions, so forgive me if I'm missing something obvious. Is there a better way to debug? Currently, the html report that is generated by the github action just shows the tests that I'm skipping.
This works fine locally. 
I've also tried to replace the line `cd shared/document && npx playwright test -c playwright-visual.config.ts` with `cd shared/document && npm run test:web-import-visual` but I get the error 
```
npm ERR! Lifecycle script `test:web-import-visual` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @lottielab/document@1.0.0 
npm ERR!   at location: /home/runner/work/lottielab/lottielab/shared/document
```
