### ISSUE TITLE
[Question] Proper Sharding with CircleCI

### ISSUE THREAD

**Issue by NickXitco** [microsoft/playwright#21195]
**Why is CircleCI only using 4/8 shards?**

I'm currently working on improving the speed of our tests running in CircleCI and wanted to try sharding. After following the[ guide here](https://playwright.dev/docs/ci#sharding-in-circleci), I have the following in my test job:
```
  playwright:
    <<: *defaults
    docker:
      - image: mcr.microsoft.com/playwright:v1.23.1-focal
    parallelism: 8
    environment:
      PLAYWRIGHT_BROWSERS_PATH: 0
    steps:
      - checkout
      - restore_cache:
          keys:
            - playwright-deps-{{ checksum "package-lock.json" }}
            - playwright-deps-
      - run: npm install -D @playwright/test
      - run: npx playwright install --with-deps
      - run: SHARD="$((${CIRCLE_NODE_INDEX}+1))"l; npx playwright test --shard=${SHARD}/${CIRCLE_NODE_TOTAL}
```

In our repo we have 2 `.spec.ts` test files, and are running tests on both Chromium and Webkit as defined in our `playwright.config.ts` file. We have `fullyParallel: true` in the config as well. Despite that setting, when I run the test job in CircleCI, I only get 4 shards actually running tests, the other 4 say `Running 0 tests using 0 workers, shard 7 of 8`
![Screenshot 2023-02-24 at 1 13 52 PM](https://user-images.githubusercontent.com/34454344/221270744-ff841d13-5e77-4ed8-bfd4-6c5debcb3c4c.png)

Each shard is only running 1 file, 1 browser, so the other 4 shards have nothing to run on. However, when I run Playwright locally I can run something absurd like `npx playwright test --shard=20/24` and it picks out 2 tests just fine. What's going on here? Is it a limitation with CircleCI? Do I need to split all my tests into individual files?
