### ISSUE TITLE
[BUG] Fails in Github Action Workflow with NPM Workspaces

### ISSUE THREAD

**Issue by hreynier** [microsoft/playwright#21372]
This is follow-up for a previously closed issue -> #21048

### System info
- Playwright Version: ^1.30.0
- Operating System: Mac OS 13.2.1 // Ubuntu
- Browser: [All]
- Extra: Using npm workspaces in my repository
### Binaries:
 - Node: 19.6.1 - /opt/homebrew/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 9.3.1 - /opt/homebrew/bin/npm
### Languages:
 - Bash: 3.2.57 - /bin/bash

### Source code

- [ x ] I provided exact source code that allows reproducing the issue locally.

Github Workflow that doesn't run correctly.

```yaml
name: Web Import Visual Regression Tests
on:
  pull_request:
    branches:
      - '*'
jobs:
  Visual-Regression-Test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set-up node
        uses: actions/setup-node@v3
        with:
          node-version: '19.6.1'
      - name: Install dependencies
        run: |
          npm install
          (cd backend/multiplayer-server && npm install)
          (cd frontend && npm install)
          (cd shared/document && npm install)
      - name: Install Playwright Browsers
        run: |
          cd shared/document
          npx playwright install --with-deps
      - name: Run Playwright Visual Regression Tests
        run: |
          cd shared/document
          npx playwright test -c playwright-visual.config.ts
        env:
          DEBUG: pw:*
      - name: Check test output against baseline
        run: |
          total_tests_current=$(grep "Total Tests in Suite:" shared/document/testing/import-export/web/test-summary/summary.txt | awk '{print $5}')
          failed_tests_current=$(grep "Tests Failed:" shared/document/testing/import-export/web/test-summary/summary.txt | awk '{print $3}')
          total_tests_baseline=$(grep "Total Tests in Suite:" shared/document/testing/import-export/web/test-summary/baseline.txt | awk '{print $5}')
          failed_tests_baseline=$(grep "Tests Failed:" shared/document/testing/import-export/web/test-summary/baseline.txt | awk '{print $3}')
          if [ "$failed_tests_current" -gt "$failed_tests_baseline" ] && [ "$total_tests_current" -eq "$total_tests_baseline" ]; then
              echo "Total tests ran: $total_tests_current, Total ran yesterday: $total_tests_baseline ."
              echo "More tests failed than expected: $failed_tests_current, expected: $failed_tests_baseline ."
              echo "Marked as failed due to regression in passing tests."
              exit 1
          elif [ "$total_tests_current" -ne "$total_tests_baseline" ]; then
              echo "Total tests ran is different that expected: $total_tests_current, expected: $total_tests_baseline ."
              echo "Failed tests: $failed_tests_current, expected: $failed_tests_baseline ."
              echo "Marked as passing due to changed number of tests."
              exit 0
          else
              echo "Total tests ran: $total_tests_current, expected: $total_tests_baseline ."
              echo "Failed tests: $failed_tests_current, expected: $failed_tests_baseline ."
              echo "Marked as passing."
              exit 0
          fi
      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: shared/document/playwright-report
          retention-days: 30
      - name: Upload Report Summary
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-test-summary
          path: shared/document/testing/import-export/web/test-summary/summary.txt
          retention-days: 30

```

**Config file**

```js
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/experimental-ct-react';
import { devices } from '@playwright/experimental-ct-react';
import CustomReport from './testing/import-export/web/utils/CustomSummaryReport';

/**
 * See https://playwright.dev/docs/test-configuration.
 */
const config: PlaywrightTestConfig = {
  testDir: './testing/import-export/web/',
  /* The base directory, relative to the config file, for snapshot files created with toMatchSnapshot and toHaveScreenshot. */
  snapshotDir: './testing/import-export/web/snapshots',
  /* Maximum time one test can run for. */
  timeout: process.env.CI ? 30 * 1000 : 10 * 1000,
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  // forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 1 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [
    [
      '@skilbourn/playwright-report-summary',
      {
        outputFile: './testing/import-export/web/test-summary/summary.txt',
        inputTemplate: CustomReport,
      },
    ],
    ['html'],
  ],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',

    /* Port to use for Playwright component endpoint. */
    ctPort: 3100,
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
    {
      name: 'firefox',
      use: {
        ...devices['Desktop Firefox'],
      },
    },
    {
      name: 'webkit',
      use: {
        ...devices['Desktop Safari'],
      },
    },
  ],
};

export default config;
```

**Steps**
- Open Pull Request to trigger workflow
- Watch as it instantly fails with `Process completed with exit code 1.`

**Expected**

I can run my playwright tests locally using this script in one of my workspaces.
```javascript
 "test:web-import-visual": "playwright test -c playwright-visual.config.ts && npx playwright show-report",
```

**Actual**

But when I try to run this in a workflow through github actions, I get a very nondescript error
`Error: Process completed with exit code 1.`

Following on from some suggestions in the previous issue, I have added `DEBUG=pw:*` env variable to the script and I get this information in the logs. (SEE COMMENT)

I'm really not sure what next steps to take. I have a feeling it could be something to do with NPM Workspaces, as a very similar script was working completely fine a month ago in a non-workspaces repository...
