### ISSUE TITLE
[REGRESSION]: Firefox & webkit timed out in Gitlab CI 

### ISSUE THREAD

**Issue by mahtabnejad90** [microsoft/playwright#21473]
**Context:**
- GOOD Playwright Version: [v1.30.0](https://github.com/microsoft/playwright/releases/tag/v1.30.0)
- BAD Playwright Version: [v1.31.2](https://github.com/microsoft/playwright/releases/tag/v1.31.2)
- Operating System: N/A
- Extra: Gitlab CI
- 
**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```yaml
run-ci-tests-firefox:
  stage: test
  image: mcr.microsoft.com/playwright:v1.31.0-focal
  before_script:
    - npm ci

  script:
    - echo "Starting E2E tests at BASEURL with firefox browser"
    - npx playwright test --project=Firefox --shard=1/3 --grep @CI 
    - npx playwright test --project=Firefox --shard=2/3 --grep @CI
    - npx playwright test --project=Firefox --shard=3/3 --grep @CI
  retry: 1
  
  artifacts:
    when: always
    paths:
      - playwright-report/
      - download/
    expire_in: 1 day
```

**Describe the bug**

I'm running around 70 tests using the sharding run method (code snippet mentioned in the code snippet section) on gitlab, but I'm getting this error without the test suite run completion, I didn't get this issue in previous versions of playwright. On chromium, the execution completes as expected. Not sure this is a regression on the framework version or issue with some config.
