### ISSUE TITLE
[BUG] Webkit not working on Github Actions

### ISSUE THREAD

**Issue by duarten** [microsoft/playwright#21990]
### System info
- Playwright Version: [v1.32.1]
- Operating System: [Ubuntu 20]
- Browser: [WebKit]
- Other info: Github Actions

### Source code

**Config file**

```ts
import { defineConfig, devices } from "@playwright/test"

// See https://playwright.dev/docs/test-configuration.
export default defineConfig({
    testDir: "./e2e",
    // Maximum time one test can run for.
    timeout: 60 * 1000,
    // Global timeout for the whole test run.
    globalTimeout: 5 * 60 * 1000,
    expect: {
        // Maximum time expect() should wait for the condition to be met.
        // For example in `await expect(locator).toHaveText();`
        timeout: 1000,
    },
    // Run tests in files in parallel.
    fullyParallel: true,
    // Opt out of parallel tests on CI.
    workers: process.env.CI ? 1 : undefined,
    // Reporter to use. See https://playwright.dev/docs/test-reporters.
    reporter: process.env.CI ? "github" : "html",
    // Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions.
    use: {
        // Timeout for each navigation action.
        navigationTimeout: 5 * 1000,
        // Maximum time each action such as `click()` can take.
        actionTimeout: 5 * 1000,
        // Base URL to use in actions like `await page.goto('/')`.
        baseURL: "http://127.0.0.1:3000/",
        // Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer.
        trace: "on-first-retry",
    },

    projects: [
        {
            name: "chromium",
            use: { ...devices["Desktop Chrome"] },
        },

        {
            name: "webkit",
            use: { ...devices["Desktop Safari"] },
        },
    ],

    // Folder for test artifacts such as screenshots, videos, traces, etc.
    outputDir: "playwright-results",
}
```

Running a test with this configuration on Github Actions (ubuntu latest) fails on the first `locator.fill:`: `TimeoutError: locator.fill: Timeout 5000ms exceeded.`. This is the debug output:

```sh
pw:browser [pid=14417] <gracefully close start> +4s
  pw:browser [pid=14417] <process did exit: exitCode=0, signal=null> +36ms
  pw:browser [pid=14417] starting temporary directories cleanup +3ms
  pw:browser [pid=14417] finished temporary directories cleanup +4ms
  pw:browser [pid=14417] <gracefully close end> +0ms
  pw:browser <launching> /home/runner/work/umani/umani/node_modules/.pnpm/playwright-core@1.32.1/node_modules/playwright-core/.local-browsers/webkit-1811/pw_run.sh --inspector-pipe --headless --no-startup-window +0ms
  pw:browser <launched> pid=[150](https://github.com/umani/umani/actions/runs/4526843935/jobs/7972265207?pr=1398#step:7:151)75 +22ms
  pw:browser [pid=15075][err] Could not determine the accessibility bus address +2s
  pw:browser [pid=15075] <gracefully close start> +9s
  pw:browser [pid=15075] <process did exit: exitCode=0, signal=null> +15ms
  pw:browser [pid=15075] starting temporary directories cleanup +0ms
  pw:browser [pid=15075] finished temporary directories cleanup +3ms
```

**Comment by mxschmitt** [comment]
Could you provide us your GitHub workfow file?

**Comment by duarten** [comment]
Sure, this is the relevant part:

```yml
    e2e:
        name: E2E

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: ./.github/actions/load-node-modules

            - name: Build
              run: bazel
                  --bazelrc=${{ github.workspace }}/build/bazelrc/ci.bazelrc
                  --bazelrc=${{ github.workspace }}/.github/workflows/ci.bazelrc
                  --bazelrc=${{ github.workspace }}/.bazelrc
                  build //apps/web:dev

            - name: Run e2e tests
              run: DEBUG=pw:browser* PLAYWRIGHT_BROWSERS_PATH=0 pnpm exec playwright test

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 5
```

**Comment by mxschmitt** [comment]
You don't install the Playwright OS dependencies nor the browsers.  Install it via `pnpm exec playwright install --with-deps` and then it should work. The error is most likely caused since you don't have the OS dependencies installed. If you want to install only the OS dependencies, you can do `pnpm exec install-deps`

**Comment by duarten** [comment]
I am installing the dependencies, it's behind the `load-node-modules` composite action:

```yml
<snip>
        - name: Playwright install
          run: PLAYWRIGHT_BROWSERS_PATH=0 pnpm exec playwright install --with-deps
          shell: bash
```

**Comment by duarten** [comment]
Firefox isn't working either:

```sh
  pw:browser [pid=14339] <gracefully close start> +3s
  pw:browser [pid=14339] <process did exit: exitCode=0, signal=null> +35ms
  pw:browser [pid=14339] starting temporary directories cleanup +1ms
  pw:browser [pid=14339] finished temporary directories cleanup +3ms
  pw:browser [pid=14339] <gracefully close end> +1ms
  pw:browser <launching> /home/runner/work/umani/umani/node_modules/.pnpm/playwright-core@1.32.1/node_modules/playwright-core/.local-browsers/firefox-1391/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-shyrW0 -juggler-pipe -silent +0ms
  pw:browser <launched> pid=14638 +4ms
  pw:browser [pid=14638][err] *** You are running in headless mode. +47ms
  pw:browser [pid=14638][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.167166) [GFX1-]: glxtest: Unable to open a connection to the X server +122ms
  pw:browser [pid=14638][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 58: Error: Can't find profile directory. +237ms
  pw:browser [pid=14638][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 58: Error: Can't find profile directory. +10ms
  pw:browser [pid=14638][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 58: Error: Can't find profile directory. +4ms
  pw:browser [pid=14638][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 58: Error: Can't find profile directory. +2ms
  pw:browser [pid=14638][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 58: Error: Can't find profile directory. +11ms
  pw:browser [pid=14638][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.167166) |[1][GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt (t=0.462807) [GFX1-]: RenderCompositorSWGL failed 
```

**Comment by brandonegg** [comment]
Having a related issue:
Our ui-test action config:
```yaml
 test-plugin-ui:
    name: 'Playwright Tests - ${{ matrix.project }} - Shard ${{ matrix.shardIndex }} of ${{ matrix.shardTotal }}'
    needs:
      - ui-test-plugin-deploy
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/playwright:v1.29.0-focal
    strategy:
      fail-fast: false
      matrix:
        project: [chromium, webkit, firefox]
        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8]
        shardTotal: [8]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd test
          npm ci
      - name: Run tests
        env:
          HOSTNAME: ***
          SQUARE_AFTERPAY_EMAIL: ${{ secrets.SQUARE_AFTERPAY_EMAIL }}
          SQUARE_AFTERPAY_PASSWORD: ${{ secrets.SQUARE_AFTERPAY_PASSWORD }}
          CI: true
          WORKERS: 4
          RETRIES: 3
          VIDEOS: true
        run: |
          cd test
          cp .env.example .env
          export HOME=/root
          npx playwright test --project=${{ matrix.project }} --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Archive test report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report-${{ matrix.project }}-${{ matrix.shardIndex }}_${{ matrix.shardTotal }}
          path: test/test-results
```

Tests passes for all browsers (firefox + chromium) except webkit, where all tests fails. It appears to not navigate to the page and fail after the timeout exceeded. I've attached a trace from one of these failed runs if it helps! To reiterate, this behavior is also reproducible on ubuntu's 22.04 webkit, when running these tests locally on MacOS webkit the issue is not present.
[trace.zip](https://github.com/microsoft/playwright/files/11083745/trace.zip)

**Comment by jpanduro-blackbird** [comment]
I have updated node 14 to node 18 (one line change, images from CircleCI) and CI started to hang (only CI timeout killed the job)
Figured out that was `Mobile Safari`, who stopped working. 
Commenting out those lines worked for me:
```
{
      name: 'Mobile Safari',
      use: {
        ...devices['iPhone 12'],
      },
    },
```

Any ideas how to solve it or do I missing some dependency?
**Note**: Looks pretty similar to what is described above. Tests running on MacOS perfectly, while docker image upgrade caused to stop 'Mobile Safari' working.

Thanks

**Comment by brandonegg** [comment]
> 

> Having a related issue: Our ui-test action config:
> 
> ```yaml
>  test-plugin-ui:
>     name: 'Playwright Tests - ${{ matrix.project }} - Shard ${{ matrix.shardIndex }} of ${{ matrix.shardTotal }}'
>     needs:
>       - ui-test-plugin-deploy
>     runs-on: ubuntu-22.04
>     container:
>       image: mcr.microsoft.com/playwright:v1.29.0-focal
>     strategy:
>       fail-fast: false
>       matrix:
>         project: [chromium, webkit, firefox]
>         shardIndex: [1, 2, 3, 4, 5, 6, 7, 8]
>         shardTotal: [8]
>     steps:
>       - uses: actions/checkout@v3
>       - name: Install dependencies
>         run: |
>           cd test
>           npm ci
>       - name: Run tests
>         env:
>           HOSTNAME: ***
>           SQUARE_AFTERPAY_EMAIL: ${{ secrets.SQUARE_AFTERPAY_EMAIL }}
>           SQUARE_AFTERPAY_PASSWORD: ${{ secrets.SQUARE_AFTERPAY_PASSWORD }}
>           CI: true
>           WORKERS: 4
>           RETRIES: 3
>           VIDEOS: true
>         run: |
>           cd test
>           cp .env.example .env
>           export HOME=/root
>           npx playwright test --project=${{ matrix.project }} --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
> 
>       - name: Archive test report
>         if: ${{ failure() }}
>         uses: actions/upload-artifact@v3
>         with:
>           name: playwright-report-${{ matrix.project }}-${{ matrix.shardIndex }}_${{ matrix.shardTotal }}
>           path: test/test-results
> ```
> 
> **Note:** this issue has only begun today, prior it was working fine
> 
> Tests passes for all browsers (firefox + chromium) except webkit, where all tests fails. It appears to not navigate to the page and fail after the timeout exceeded. I've attached a trace from one of these failed runs if it helps! To reiterate, this behavior is only reproducible on ubuntu's 22.04 webkit, when running these tests locally on MacOS webkit the issue is not present. [trace.zip](https://github.com/microsoft/playwright/files/11083745/trace.zip)

As a follow up this, the issue appears to be related to the container image I was using for playwright. With my update runner I use the node action and install the playwright browser manually. I then add a cache for the playwright browser so I don't have to install it everytime:

```yaml
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: test/package-lock.json

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./test/package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: cache-primes
        with:
          path: test/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('test/package-lock.json') }}

      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: /home/runner/.cache/ms-playwright
          key: ${{ runner.os }}-${{ matrix.project }}-playwright-${{ env.PLAYWRIGHT_VERSION }}


      - name: Install dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: |
          cd test
          npm ci

      - name: Install PW browser
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: |
          cd test
          npx playwright install --with-deps ${{ matrix.project }}
```

Installed the browsers like this resolved my webkit issues!
