### ISSUE TITLE
[BUG]: env PLAYWRIGHT_BROWSERS_PATH does not work with webkit

### ISSUE THREAD

**Issue by EgonBolton** [microsoft/playwright#22146]
### System info
- Playwright Version: v1.32.1
- Operating System: macOS-latest (GA)
- Browser: WebKit
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

MRE: https://github.com/johny-ss/actions

or

**Github action file**

```yml
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel current job when pushing new commit into the PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    # timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # keep running other jobs if one fails
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        browser: [chromium, firefox]
        include:
          - os: macos-latest
            browser: webkit
    env:
      # Playwright uses different paths on different OS's. 
      # To make it work cross-platform, we need to set the path manually.
      # Alternatively, `PLAYWRIGHT_BROWSERS_PATH=0` install binaries in node_modules
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/ms-playwright
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # installing dependencies with cache
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      # installing browsers with cache
      - name: Store Playwright's Version
        shell: bash #necessary for it to work on Windows, which uses powershell by default
        run: echo "PLAYWRIGHT_VERSION=$(node -p 'require("@playwright/test/package.json").version')" >> $GITHUB_OUTPUT
        id: playwright-version
      - name: Cache browsers
        id: cache-browsers
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ matrix.browser }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
      - name: Download browsers
        if: steps.cache-browsers.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps ${{ matrix.browser }}

      # running tests
      - run: npx playwright test --project=${{ matrix.browser }}
      - name: Upload Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.browser }}-${{ matrix.os }}-test-results
          path: test-results/
          retention-days: 7
```

**Test file (self-contained)**: It can be any test, it doesn't matter

**Steps**
- Run the github actions of my repository. macOS-webkit throws error, and if you run again ubunto-webkit (now with cache), also throw error.

**Expected**

The test on webkit should succeed even when the browser and its dependencies are cached.

**Actual**

- In ubuntu-webkit, if the browser IS NOT cached, the execution of the tests gives this error:

![image](https://user-images.githubusercontent.com/43938777/229361516-ef5298fe-0c71-447c-80ba-34b64b4f5ed3.png)

- in macOS webkit, the execution of the tests gives the following error:

![image](https://user-images.githubusercontent.com/43938777/229360380-d758f33b-6083-452d-b6b4-d81ce2281b40.png)

My guess is that the PLAYWRIGHT_BROWSERS_PATH environment variable doesn't work well with webkit, because if I remove it and don't cache at all, the tests work fine.

note: If you want to reproduce in another repo, you can change the --project flag to --browser to avoid plawright.config.ts.

**Comment by mxschmitt** [comment]
Yes on Linux there need to be apt dependencies installed and on Windows the Server-Media-Foundation feature. Both you are not able to cache.

Sure it can take longer to download browsers, in my case of https://github.com/mxschmitt/myproject0404 browsers took 12 seconds to download and dependencies 54 seconds. See [here](https://github.com/mxschmitt/myproject0404/actions/runs/4607247624/jobs/8141528861).

If you don't install the dependencies for Google Chrome or Firefox, you might experience issues with e.g. graphics, fonts, video playback etc. Such configurations we are not able to support.

There is no issue with PLAYWRIGHT_BROWSERS_PATH from what I can tell. It looks all expected from my side, so I guess we can close this issue?

**Comment by EgonBolton** [comment]
Thanks, I think I understand it better now. I've decided to go with this:

```yml
      - name: Install Playwright browsers
        if: steps.cache-browsers.outputs.cache-hit != 'true'
        run: npx playwright install ${{ matrix.browser }}
      - name: Install Playwright dependencies
        # Linux and Windows cannot cache deps.
        # See: https://github.com/microsoft/playwright/issues/22146#issuecomment-1495821016
        # if: steps.cache-browsers.outputs.cache-hit != 'true' || runner.os != 'macOS'
        # BUT except for linux-webkit, they already include most of the necessary dependencies.
        # So unless you use things like graphics, fonts, video playback etc. and you run into a problem,
        # You can speed up your CI by using this less strict condition:
        if: steps.cache-browsers.outputs.cache-hit != 'true' || (runner.os == 'Linux' && matrix.browser == 'webkit')
        run: npx playwright install-deps ${{ matrix.browser }}
```
By the way, I don't know if it's possible but it would be great if Playwright could automatically detect the necessary dependencies based on tests.
____

> There is no issue with PLAYWRIGHT_BROWSERS_PATH from what I can tell. It looks all expected from my side, so I guess we can close this issue?

Regarding this, have you tried the macOS-webkit combination using that environment variable?
Right now it's the only problem I'm encountering, and it doesn't seem to be related to the cache:

- [no cache and using PLAYWRIGHT_BROWSERS_PATH](https://github.com/johny-ss/actions/actions/runs/4610502888/jobs/8149171539
) (note that both browsers and dependencies are installed).
- [using cache but not using PLAYWRIGHT_BROWSERS_PATH](https://github.com/johny-ss/actions/actions/runs/4601300394/jobs/8129056735)
