### ISSUE TITLE
[BUG] Unable to run on gitlab ci

### ISSUE THREAD

**Issue by yunseop-dev** [microsoft/playwright#23017]
### System info
- Playwright Version: v1.33.0
- Other info: gitlab ci

### Source code
```
e2e:
  stage: e2e
  image:
    name: mcr.microsoft.com/playwright:v1.33.0-jammy
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - yarn playwright test

```

When running in a gitlab ci environment, the following error occurs.

```
Executing "step_script" stage of the job script
00:01
Using docker image sha[25](https://gitlab.actionpower.kr/platform/daglo/daglo-web/-/jobs/9400#L25)6:b283afc7c58576a4fca2bb86f5641f903e5f62154578b90e4949f31ba4610f4b for mcr.microsoft.com/playwright:v1.33.0-jammy with digest mcr.microsoft.com/playwright@sha256:cd34ca7ca246575e2b3863bd773c1c42077493a5b71a0b846670e8e37cc98838 ...
shell not found
```

It seems to be a shell problem, so I tried changing it to the following syntax, but the following error was printed.

```yml
# fixed ci script
e2e:
  stage: e2e
  image:
    name: mcr.microsoft.com/playwright:v1.33.0-jammy
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - yarn playwright test
  rules:
    - if: $CI_COMMIT_REF_NAME == "feature/NDG-1938-e2e-test-setting"

```

```
Using docker image sha256:b283afc7c58576a4fca2bb86f5641f903e5f62154578b90e4949f31ba4610f4b for mcr.microsoft.com/playwright:v1.33.0-jammy with digest mcr.microsoft.com/playwright@sha256:cd34ca7ca246575e2b3863bd773c1c42077493a5b71a0b846670e8e37cc98838 ...
$ npx playwright test
node[10]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb7a940 node::Abort() [node]
 2: 0xb7a9be  [node]
 3: 0xbe98be  [node]
 4: 0xbe99a1 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xb38f5b node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
 6: 0xb395ab node::Start(int, char**) [node]
 7: 0x7fb158722d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fb158722e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xabbdee _start [node]
sh: line 122:    10 Aborted                 (core dumped) npx playwright test
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```
