### ISSUE TITLE
[Feature] Faster way to install Playwright Browsers and dependencies on GitHub Actions

### ISSUE THREAD

**Issue by dtinth** [microsoft/playwright#23388]
# Problem

The default GitHub Actions workflow generated by Playwright takes quite a lot of time to install Playwright Browsers, and sometimes fail entirely.

- Example 1: It takes 3.5m to run `playwright install --with-deps`

  <img alt="image" src="https://github.com/microsoft/playwright/assets/193136/db21e5ac-9de8-43ed-9e3d-97a9927e3981">

- Example 2: Sometimes `azure.archive.ubuntu.com` is unstable. In most Node.js applications we never have a need to run `apt-get install` except when installing Playwright browsers. This has been one of the most common cause of our build failures.

  <img alt="image" src="https://github.com/microsoft/playwright/assets/193136/901052cf-cc1c-47a9-a3ac-d8e26e5b95f7">

  Since we run our tests on many workers, this Playwright installation failure costed us 10 hours of GitHub Actions billable time.

  <img width="348" alt="image" src="https://github.com/microsoft/playwright/assets/193136/9a14f3cb-1ada-43d5-9bd3-a318e7e49291">

# Request

- ~~Make the default GitHub Actions pipeline not rely on `apt` installs.~~ [**Update:** “It's unfortunately not possible”](https://github.com/microsoft/playwright/issues/23388#issuecomment-1569930053)

- Update the docs to avoid running `playwright install` directly and use a Docker image to run instead, so people who follow the docs get the best testing experience. (Maybe update the template in [create-playwright](https://github.com/microsoft/create-playwright)?)

# For people who face the same issue

I am also exploring solutions as I create this issue, which I will update here as I find more workarounds.

For others who face the same issue: I would like to know how other people work around this problem, so maybe we can find the best one faster. If you have worked around this in some way, please share how you do it.

## Workarounds summary

- [💡 Set `jobs.<job_id>.container.image` to `mcr.microsoft.com/playwright:v1.34.3-jammy`](https://github.com/microsoft/playwright/issues/23388#issuecomment-1569930053)
  - [⚠️ Cannot use CLI tools that come with default GitHub Actions images such as `unzip` or `aws`.](https://github.com/microsoft/playwright/issues/23388#issuecomment-1569989814)
- [💡 Define and use a custom Docker action.](https://github.com/microsoft/playwright/issues/23388#issuecomment-1570005895)
- [⭐ Use Playwright’s Docker image in `jobs.<job_id>.steps[*].uses`.](https://github.com/microsoft/playwright/issues/23388#issuecomment-1570016619)
  - [⚠️ Does not work with Firefox.](https://github.com/microsoft/playwright/issues/23388#issuecomment-1571632249)

(⭐ = I am using this one now.)

**Comment by mxschmitt** [comment]
It's unfortunately not possible to make the GitHub Action unaware of apt. What we recommend instead is using our Docker image, which has all the dependencies preinstalled already: https://playwright.dev/docs/ci#via-containers

To use it, you just add:

```
 container:
      image: mcr.microsoft.com/playwright:v1.34.3-jammy
```

and remove the: `npx playwright install --with-deps`

**Comment by dtinth** [comment]
**Update:** A solution that works for me and improved the build time by 2.5 minutes is to [create a custom Docker container action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action).

First define an action:

```yaml
# .github/actions/playwright/action.yml
name: Playwright Test
description: Run Playwright test
runs:
  using: docker
  image: docker://mcr.microsoft.com/playwright:v1.34.3-jammy
  args:
    - npx
    - playwright
    - test
```

Then run it:

```yaml
      - uses: ./.github/actions/playwright
```

**Comment by dtinth** [comment]
**Update:** Turns out a custom action isn’t needed. [A `docker://` URL can be used with `with:` directive already.](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-docker-hub-action)

```yaml
      - name: Run Playwright tests
        uses: docker://mcr.microsoft.com/playwright:v1.34.3-jammy
        with:
          args: npx playwright test
```

**Comment by thewilkybarkid** [comment]
I've tried to set `$HOME` in https://github.com/PREreview/prereview.org/commit/8f7b96eecdd0c5abca11b634630582c0f364316c, but it didn't apply inside the container (still seeing `Running Nightly as root in a regular user's session is not supported.  ($HOME is /github/home which is owned by uid 1001.)`). Not sure what to do now so will have to revert...

**Comment by dtinth** [comment]
@thewilkybarkid One potential way to work around this may be to prefix the `args` with `env HOME=/root` or use something like `cross-env`. Not sure if it works or not.

**Comment by mxschmitt** [comment]
Looks like there is no action item on our side and you have listed a few workarounds. If you are interested in contributing to your [ci](https://playwright.dev/docs/next/ci) docs and add there another caching strategy to make it on GitHub Actions faster, we would more than appreciate!

Regarding the HOME=/root issue, I closed the linked issue a while ago since I wasn't able to reproduce it. If you help us reproducing this one, we can definitely fix it. 

Thanks for your understanding!

**Comment by thewilkybarkid** [comment]
That worked @dtinth! I'll comment on the other issue @mxschmitt.

**Comment by DivyanshGothwal** [comment]
@dtinth @mxschmitt 
In the below SS I tried creating a custom github action and tried to use it in my workflow, I got error saying playwright is not installed.

![image](https://github.com/microsoft/playwright/assets/13894942/09cd1954-b2a1-44c4-b016-343184ce605a)

**Comment by mxschmitt** [comment]
You still need to do "npm ci" inside of it. Playwright is not installed in the Docker image, only the browsers and browser OS dependencies.

**Comment by DivyanshGothwal** [comment]
I get that the docker image doesn't have playwright installed.
npm ci will clean and install the dependencies.
so where do I need to do this? 
as part of my workflow?


one more thing.
This is what I have in my package.json.(only this @playwright/test dependecy).
do i need to add playwright here as well?
![image](https://github.com/microsoft/playwright/assets/13894942/6fa721c5-f60f-4396-9cb2-9b5c4d827b69)

**Comment by fritzfelix** [comment]
Hey @mxschmitt,

>Playwright is not installed in the Docker image, only the browsers and browser OS dependencies.

I have the following issue regarding this in the docker image. I copy my repository into the official docker image, run `pnpm install` before running my tests, and the package.json obviously also includes `"@playwright/test"`. Now, when running `pnpm exec playwright test` inside the image, it can not find the browsers:

> executable doesn't exist at /ms-playwright/webkit-1883/pw_run.sh

To get around this, I run `pnpm playwright install webkit` after `pnpm install` as well. But I have the strong feeling this is very much beside the point of using the official playwright docker image, which should have this installed already.

My question is how to make sure the existing browsers can be found, and what the recommended approach is here.

**Comment by andig** [comment]
Ended up here with the same issue. Need to install sqlite3 in the container to run our tests. Not sure how/if that would be possible.

**Comment by nace-plesko** [comment]
> Hey @mxschmitt,
> 
> > Playwright is not installed in the Docker image, only the browsers and browser OS dependencies.
> 
> I have the following issue regarding this in the docker image. I copy my repository into the official docker image, run `pnpm install` before running my tests, and the package.json obviously also includes `"@playwright/test"`. Now, when running `pnpm exec playwright test` inside the image, it can not find the browsers:
> 
> > executable doesn't exist at /ms-playwright/webkit-1883/pw_run.sh
> 
> To get around this, I run `pnpm playwright install webkit` after `pnpm install` as well. But I have the strong feeling this is very much beside the point of using the official playwright docker image, which should have this installed already.
> 
> My question is how to make sure the existing browsers can be found, and what the recommended approach is here.

I had the same issue at the beginning and then realized that in the logs there was error:
```
 Error: browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1105/chrome-linux/chrome
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.42.1. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.34.3-jammy               ║
    ║ - required: mcr.microsoft.com/playwright:v1.42.1-jammy               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝
   ```
   
   So the issue was that versions of docker image and Playwright didn't match. After updating the image to `mcr.microsoft.com/playwright:v1.42.1-jammy` the existing browsers were found, without manually installing them.

**Comment by zecka** [comment]
Don't know hot to do that on Github action but on azure pipeline, caching '/home/vsts/.cache/ms-playwright' directory speed up browser installation

```yml
    # Create the directory for Playwright cache
    - script: mkdir -p /home/vsts/.cache/ms-playwright
      displayName: 'Create Playwright cache directory'
      
    # Cache Playwright browsers
    - task: Cache@2
      inputs:
        key: 'playwright | "$(Agent.OS)" | browsers'
        path: '/home/vsts/.cache/ms-playwright'

    # Install dependencies
    - script: |
        yarn install
      displayName: 'Yarn install --frozen-lockfile'
      workingDirectory: '$(build.sourcesdirectory)/tests/e2e'
    - script: npx playwright install --with-deps
      workingDirectory: '$(build.sourcesdirectory)/tests/e2e'
      displayName: 'Install Playwright browsers'
    
```

**Comment by airtonix** [comment]
Came here to say that all I needed to do was two things: 

- accept that i'm running with branded chrome, since [github installs that kind of chrome](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#:~:text=Google%20Chrome%20131.0.6778.139)
- set `channel: "chrome"` in my playwright config


```ts
import { defineConfig, devices } from '@playwright/test';
import dotenv from 'dotenv';

dotenv.config();

export default defineConfig({
  testDir: './e2e',
  timeout: 30 * 1000,
  expect: {
    timeout: 5000,
  },
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [['list'], ['html']],
  use: {
    actionTimeout: 0,
    baseURL: process.env.BASEURL,
    trace: 'on',
    acceptDownloads: true,
    ignoreHTTPSErrors: true,
  },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        channel: 'chrome',
      },
    },
  ],
  webServer: {
    command: 'mise run serve 3000',
    port: 3000,
    timeout: 120 * 1000,
    reuseExistingServer: !process.env.CI,
  },
});
```

**Comment by benjick** [comment]
<img width="499" height="64" alt="Image" src="https://github.com/user-attachments/assets/f92b6d06-735b-4392-989a-2cbcb19fc137" />

Is there no good solution for this? `channel: "chrome"` doesn't work at all for me

**Comment by dtinth** [comment]
I recently learned that Playwright supports exposing local network to the remote browser server using `exposeNetwork` option and that Playwright Test can be configured to use that setup with `PW_TEST_CONNECT_WS_ENDPOINT` + `PW_TEST_CONNECT_EXPOSE_NETWORK`.

With that, I created the [dtinth/setup-playwright-test-docker](https://github.com/dtinth/setup-playwright-test-docker) action, which is a drop-in replacement for `playwright install --with-deps` but is around 2x faster. It does this by launching a Playwright remote server using Docker, and then configures environment variables (`$GITHUB_ENV`) so that Playwright Test automatically connects to it.

<img width="2468" height="620" alt="Image" src="https://github.com/user-attachments/assets/ccce24a5-b944-4de8-9308-bd1404052cd1" />

**Comment by alonbardavid** [comment]
A bit of a late reply, but I have found that just caching the downloads make for a very fast turnaround.
```
      - name: Restore Playwright cache
        id: playwright-cache
        uses: actions/cache/restore@v5
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: <run your install command here>

      - name: Save Playwright cache
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('pnpm-lock.yaml') }}
```
