### ISSUE TITLE
[Question] Running Playwright in Gitlab CI w/official docker image

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#23686]
So the documentation is pretty sparse for gitlab CI examples, however i've seen some examples online that looks like it should be as straightforward as this:

(My sample .gitlab-ci.yaml file)

```yaml
stages:
  - run_tests #test suite automation run stage 

tests:
  stage: run_tests
  image: mcr.microsoft.com/playwright:v1.35.0-jammy #official playwright image from microsoft
  script:
    - npm install ci
    - npm install -D @playwright/test
    - npm ci
    - npx playwright test
  artifacts:
    paths: #assuming deafult playwright artifacts paths 
      - ./playwright-report/
    when: always
    expire_in: 5 days  #artifacts will purged after 5 days of test run
```

However the runner always gives a `shell not found`. I've googled around but haven't seen much in the way of why this would happen? Ill admit im new to CI/CD land but this seems like it should be a pretty basic configuration?

**Comment by aslushnikov** [comment]
@msmith1114 It looks like you'll need to specify the entrypoint for the container, see https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27614#note_517446691

**Comment by msmith1114** [comment]
@aslushnikov Im curious what it expects the entrypoint to be? or is it literally expecting `entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]` (not even sure what the code does)

**Comment by pavlemutic** [comment]
I'm also new to this, but I did it the other way around. I created a new image from the official one, put all the tests inside, and run it that way. Not really sure if this is the way it is imagined to be executed, but it works.

Dockerfile:
```dockerfile
FROM mcr.microsoft.com/playwright:v1.33.0-jammy

WORKDIR /app
COPY ./e2e /app/e2e
COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json
COPY ./playwright.config.js /app/playwright.config.js

RUN npm install
```

.gitlab-ci.yml:
```yaml
e2e-test:
  stage: build-test
  script:
    - docker build -t e2e-pw-docker:1.33.0 .
    - docker run --rm --ipc=host e2e-pw-docker:1.33.0 npx playwright test
```

I face some issues with the `webkit` tho, still figuring it out, but `chromium` and `firefox` work.
