### ISSUE TITLE
[Bug] Possible issue with Docker Container on CI?

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#23787]
So it's possible im doing something wrong, but I've also stumbled across threads with similar issues: https://askubuntu.com/questions/1405417/20-04-vs-22-04-inside-docker-with-a-16-04-host-thread-start-failures for example.

Currently im trying to run the newest Playwright version on gitlab CI with the newest docker container. My current gitlab-ci.yaml:

````yaml
stages:
  - api_tests #test suite automation run stage

tests:
  stage: api_tests
  image:
    name: mcr.microsoft.com/playwright:v1.34.0-jammy #official playwright image from microsoft
    entrypoint:
      ["/bin/bash", "-c", "ln -snf /bin/bash /bin/sh && /bin/bash -c $0"] #Needed for "shell not found" issue
  script:
    - npm install ci
    - npm install -D @playwright/test
    - npm ci
    - npx playwright test
  artifacts:
    paths: #assuming deafult playwright artifacts paths
      - ./playwright-report/
    when: always
    expire_in: 5 days #artifacts will purged after 5 days of test run
````

Currently for whatever reason I HAVE to use `docker pull mcr.microsoft.com/playwright:v1.33.0-focal` for it to work. Due to it being Ubuntu 20.04 and not 22.04. Using the newest image gives me:

```npm install ci
node[11]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb7a940 node::Abort() [node]
 2: 0xb7a9be  [node]
 3: 0xbe98be  [node]
 4: 0xbe99a1 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xb38f5b node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
 6: 0xb395ab node::Start(int, char**) [node]
 7: 0x7f[26](https://scm.qsrautomations.com/test-automation/third-party-api-automation/-/jobs/11533#L26)c00e8d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f26c00e8e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xabbdee _start [node]
sh: line 115:    11 Aborted                 (core dumped) npm install ci
```
Has anyone ran into this?
