### ISSUE TITLE
[BUG?] The test run hangs and loses response at a random test case since v1.35.0

### ISSUE THREAD

**Issue by alex-vungle** [microsoft/playwright#23857]
### System info
- Playwright Version: [v1.35.1]
- Test Env: MacOS 13.4.1, K8S
- Browser: [Chromium]
- Test Runner: Playwright test v1.45.1
- Script language: Typescript

### Source code

**KubernetesPod.yaml**

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: playwright
spec:
  imagePullSecrets:
    - name: vungleregistrykey
  containers:
    - name: playwright
      image: mcr.microsoft.com/playwright:v1.35.1-jammy
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "5Gi"
          cpu: "8"
        limits:
          memory: "10Gi"
          cpu: "12"
      command:
        - cat
      tty: true
    - name: mongo
      image: mongo
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      command:
        - cat
      tty: true
```

**Jenkins Pipeline**
```
......
        stage('Execute regression test on stage env') {
            when {expression {params.ENV == 'STAGE'}}
            steps {
                withCredentials([string(credentialsId: 'MongoDB_URL_SANITIZED_RW', variable: 'MONGODB_URL')]) {
                    echo 'Execute regression test on stage env...'
                    sh 'npx playwright test --workers=10'
                }
            }
        }
......
```

### Repro Steps:
In my test project, I have more than 170+ test cases running in fully parallel mode(worker processes: 10). However, when I upgrade the Playwright version from v1.33.0 to v1.35.1, I notice that the test execution will hang at a random test case and lose response unless you kill the process or stop the Jenkins job, this issue is reproducible on both of my laptop and on k8s env.

If downgrade the playwright to v1.33.0, all test cases can be executed successfully to the end.
