### ISSUE TITLE
[BUG] When script is running on CI/CD, environment variables which are added in 'workflow action' of 'Github' is not getting picked.

### ISSUE THREAD

**Issue by DeeptiSaxena09** [microsoft/playwright#23851]
### System info
- Playwright Version: [v1.32]
- Operating System: [macOS 13.2.1]
- Browser: [Chromium]
- Other info: [N/A]

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**configTypes.ts** : This file is inside folder in which pages, test and configTypes.ts are in same level.
```

import fs from "fs";
import toml from "toml";


const config = toml.parse(fs.readFileSync("./config.toml", "utf-8"));

export default {
  ADMIN_URL: process.env.ADMIN_STAG_URL ?? config.admin_url,
  ADMIN_MOBILE_NUMBER: process.env.ADMIN_PHONE ?? config.admin_mobile_number,
 ADMIN_PASSCODE: process.env.ADMIN_PASSCODE ?? config.admin_passcode,
};

```
**config.toml** : This file is in the main root level.

```
admin_url="https://hello.com/"
admin_mobile_number="9999999999"
admin_passcode = "1234"
```

**Git Hub Repository > > Settings >> Secrets and Variables >> Actions >> Variables >> Repository Variables ** : At this location, I have added URL and Credentials which should be used.

```SANITY=1 CICD=1 ADMIN_STAG_URL="https://test-hello.com/" ADMIN_PHONE=9090909090 ADMIN_PASSCODE=1234```

**GitHub Action Workflow** : 

```
name: Automated Tests
on:
  pull_request:
    branches: [master]
    types: ['opened']
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: admin
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Check out automationtest repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        working-directory: ./automationtest
      - name: Run tests
        run: SANITY=1 CICD=1 npx playwright test --project=admin-sanity
        working-directory: ./automationtest
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./automationtest/playwright-report/
          retention-days: 8
```

**Steps**
- [Run the test]

**Expected**

I am expecting when the script is running through cicd pipeline, it will use the URL and login credentials mentioned in the 'GitHub Actions >> Variables >> Repository Variables'.

**Actual** 

It is using the URL and Credentials mentioned in 'Config.toml' file when running tests through cicd pipelines.

Please help here.

Thanks.
