### ISSUE TITLE
[Question] Error: playwright.config.ts: config.workers must be a number or percentage on GitHub Actions

### ISSUE THREAD

**Issue by siddharth2023** [microsoft/playwright#23933]
### System info
- Playwright Version: [v1.35.1]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ x ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/siddharth2023/playwrightProjects]

or

**Config file**

```js
// playwright.config.ts
workers: process.env.CI ? process.env.WORKERS : 1,
```

**Actions yml**
```yml
name: Playwright Tests
on:
  workflow_dispatch:
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run run:duckduck
      env:
          WORKERS: ${{vars.WORKERS}}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 3

```

**Test file (self-contained)**

```js
import { expect } from "@playwright/test";
import { test } from "./my-test";
// import { test } from "./../fixture";

test("test 2", async ({ page, person, baseURL, userName }) => {
  if (baseURL.includes("wiki")) {
    await page.getByPlaceholder("Search Wikipedia").click();
    await page.getByPlaceholder("Search Wikipedia").fill("apple");
  }
  if (baseURL.includes("spread")) {
    await page.getByRole("link", { name: "Device Privacy Tips" }).click();
    await page.getByRole("heading", { name: "Device Privacy Tips" }).click();
    await page
      .getByRole("menuitem", { name: "Privacy Crash Course" })
      .getByRole("link", { name: "Privacy Crash Course" })
      .click();
    await page.getByRole("heading", { name: "Crash Course" }).click();
  }
});
```

**Steps**
- [Run the test] 
- `npx playwright test --project=duckduck`

**Expected**

[I expected to be able to handle the worker threads via Actions variables]

**Actual**

Actions fails with the error
`Error: playwright.config.ts: config.workers must be a number or percentage`

How can I convert an Actions variable to a number?
