### ISSUE TITLE
[BUG] Running Playwright in Docker via a Github Action will just hang forever if it fails

### ISSUE THREAD

**Issue by tking16** [microsoft/playwright#24154]
### System info
- Playwright Version: v.135
- Operating System: [Ubuntu-latest (Github Actions)]
- Browser: [Firefox]
- Other info:

**Config file**

```js
import { defineConfig, devices } from '@playwright/test';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
    testDir: './tests',
    /* Run tests in files in parallel */
    fullyParallel: true,
    /* Fail the build on CI if you accidentally left test.only in the source code. */
    // forbidOnly: !!process.env.CI,
    /* Retry on CI only */
    retries: process.env.CI ? 2 : 0,
    /* Opt out of parallel tests on CI. */
    workers: process.env.CI ? 1 : 8,
    /* Reporter to use. See https://playwright.dev/docs/test-reporters */
    reporter: 'html',
    /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
    use: {
        // // Emulates the user locale.
        // locale: 'zh-cn',
        // // Emulates the user timezone.
        // timezoneId: 'Asia/Shanghai',
        /* Base URL to use in actions like `await page.goto('/')`. */
        baseURL: process.env.TEST_ENV == 'prod' ? 'http:www.prodSite.com' : process.env.baseUrl ?? 'http://localhost:3000',

        /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
        trace: 'on-first-retry',
    },
    /* Configure projects for major browsers */
    projects: [
        // {
        //   name: 'chromium',
        //   use: { ...devices['Desktop Chrome'] },
        // },

        {
            name: 'firefox',
            use: { ...devices['Desktop Firefox'] },
        },

        // {
        //   name: 'webkit',
        //   use: { ...devices['Desktop Safari'] },
        // },

        /* Test against mobile viewports. */
        // {
        //   name: 'Mobile Chrome',
        //   use: { ...devices['Pixel 5'] },
        // },
        // {
        //   name: 'Mobile Safari',
        //   use: { ...devices['iPhone 12'] },
        // },

        /* Test against branded browsers. */
        // {
        //   name: 'Microsoft Edge',
        //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
        // },
        // {
        //   name: 'Google Chrome',
        //   use: { ..devices['Desktop Chrome'], channel: 'chrome' },
        // },
    ],

    /* Run your local dev server before starting the tests */
    // webServer: {
    //   command: 'npm run start',
    //   url: 'http://127.0.0.1:3000',
    //   reuseExistingServer: !process.env.CI,
    // },
});

```

**Actions file(self-contained)**

```yaml
name: Playwright Tests
on:
  push:
    branches: ["main"]
    paths: ['xxx-xxx/web/**']
  pull_request:
    paths: ['xxx-xxx/web/**', 'testing/xxx-xxx-playwright/**']
env:
  TEST_ENV: prod
  TEST_ENDPOINT: https://zzz-web-xxx.zzz.com/

jobs:
  build:
    if: github.event_name == 'pull_request'
    name: Build Applocally
    runs-on: [self-hosted, Docker]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Build container
        working-directory: testing/xxx-xxx-playwright
        run: docker compose -f docker-compose.yml build

      - name: Run containerized tests
        working-directory: testing/xxx-xxxx-playwright
        run:
          docker compose -f docker-compose.yml up
```

**Steps**
- Set up an actions file so the playwright tests run in Docker
- ensure the test will fail
- Trigger the github action

**Expected**

Docker exits and the Action fails 

**Actual**

The last line in the log says `xxx-xxx-playwright-playwright-1 exited with code 1` but will hang eternally

Extra info

Docker-compose file
```yaml
version: '3.4'
services:
  app-frontend:
    build:
      context: ../../xxx-xxx/web
      dockerfile: ../../xxx-xx/web/docker/frontend/Dockerfile
      target: build
      args:
        - ENV_FILE=./docker/frontend/extra_files/.env.development
    command: npm start
    ports:
      - "3000:3000"

  playwright:
    depends_on:
      - app-frontend
    ports:
      - "9323:9323"
    environment:
      - CI
      - baseUrl=http://app-frontend:3000
    build:
      context: .
      dockerfile: docker/Dockerfile

```

DockerFile
```
FROM registry-mirror.digital.company.com/node:18.16.0-bullseye

WORKDIR /app
COPY package*.json ./
RUN npx playwright install --with-deps
RUN npm install @playwright/test -D

COPY playwright.config.ts /app/
COPY . /app/

CMD npx playwright test

```
