### ISSUE TITLE
[BUG] Github Action doesn't run the webServer.command 

### ISSUE THREAD

**Issue by sunehinz** [microsoft/playwright#26539]
### System info
- Playwright Version: 1.37.1
- Operating System: Github Action:ubuntu-latest
- Browser: [All, Chromium, Firefox, WebKit]
- NextJS: 13.4.9
- Typescript: 5.0.2

### Source code

- This works locally but not in Github Action!

**Config file**

```typescript
import { defineConfig, devices } from '@playwright/test'
import * as dotenv from 'dotenv'

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  /* Run setup script before test suite runs */
  globalSetup: require.resolve('./tests/globalSetup.ts'), // 👈 this does work
  /* Run tests from the tests directory, relative to this configuration file */
  testDir: './tests',
  /* Run tests in files in parallel */
  fullyParallel: false,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: 1, // process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: 'http://localhost:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],

  /* Run your local dev server before starting the tests */
  webServer: {
    command: 'npm run build && npm run start', // 👈 this doesn't seem to be invoked
    url: 'http://localhost:3000',
    reuseExistingServer: false,
    stdout: 'pipe',
    stderr: 'pipe',
    env: !process.env.CI
      ? dotenv.config({ path: '.env.test', override: true }).parsed as { [key: string]: string }
      : undefined,
  },
});
```

**Test file (self-contained)**

```js
test('Can access site', async ({ page }) => {
  await page.goto(`${process.env.BASE_URL}/account/signup`)
  ...
})
```

**Github Workflow**

```yaml
name: Playwright Tests
on:
  push:
    branches: [ main, master ]
    path: apps/client
  pull_request:
    branches: [ main, master ]
    path: apps/client
jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      APP_ENV: ${{ vars.APP_ENV }}
      BASE_URL: ${{ vars.BASE_URL }}
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ vars.DB_HOST }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
```

**Steps**
- Push to github which triggers the workflow.

**Expected**

The test running i Github Actions as they do locally.

**Actual**

- Test starts but immediately fails as the server is never built or started. Throws `Error: page.goto: net::ERR_CONNECTION_REFUSED at http://localhost:3000/account/signup` on test.
- It uses 11 seconds on the test step which tells me it did not build the solution.
- It does run the globalSetup file which prepares a remote database, and I can see this is happening as expected.
- The 2 tests succeeding are the boilerplate that accesses external public websites.

<img width="1477" alt="billede" src="https://github.com/microsoft/playwright/assets/25770935/fbf9d80a-447f-4e26-8ff4-afac73e0cf39">

**What I tried**
- Using `127.0.01` instead of `localhost`
- Using https with `ignoreHTTPSErrors: true`
- Tried starting the server before running `npx playwright test`. It builds and starts fine but is stuck on the step as i doesn't get an exit call (it just starts the server as in production, as expected)
