### ISSUE TITLE
[Question] GitLab CI "Cannot launch Chromium as root without --no-sandbox" has issue even with `--no-sandbox` provided"

### ISSUE THREAD

**Issue by volekerb** [microsoft/playwright#2665]
Using GitLab CI for running playwright tests.
GitLab version: 12.9.2-ee
Stacktrace:
```
Error: Cannot launch Chromium as root without --no-sandbox
 at Object.assert (/builds/online/mvp/online-mvp-qa/node_modules/playwright/lib/helper.js:244:15)
     at Chromium._amendEnvironment (/builds/online/mvp/online-mvp-qa/node_modules/playwright/lib/server/chromium.js:56:18)
     at Chromium._launchServer (/builds/online/mvp/online-mvp-qa/node_modules/playwright/lib/server/browserType.js:147:23)
     at async /builds/online/mvp/online-mvp-qa/node_modules/playwright/lib/server/browserType.js:98:50
     at async ProgressController.run (/builds/online/mvp/online-mvp-qa/node_modules/playwright/lib/progress.js:76:28)
     at async PlaywrightRunner.getTests (/builds/online/mvp/online-mvp-qa/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:48:52)
     at async PlaywrightRunner.runTests (/builds/online/mvp/online-mvp-qa/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:67:30)
     at async TestScheduler.scheduleTests (/builds/online/mvp/online-mvp-qa/node_modules/@jest/core/build/TestScheduler.js:271:11)
     at async runJest (/builds/online/mvp/online-mvp-qa/node_modules/@jest/core/build/runJest.js:382:19)
     at async _run (/builds/online/mvp/online-mvp-qa/node_modules/@jest/core/build/cli/index.js:364:7)
```
Test:
```
beforeAll(async () => {
        browser = await chromium.launch( {
            headless: false, //or true, it doesn't change the picture
            args: [
            `--no-sandbox`,
        ]});
        page = await browser.newPage();
    });
```
Part of .gitlab-ci.yml
```
test:
  stage: test
  image: node:13-slim
  script:
    - npm i
    - npm test
  artifacts:
    paths:
      - screenshots
    expire_in: 15 days
  only:
    - master
  allow_failure: false
  when: manual
```

Can you please assist what could go wrong here?
