### ISSUE TITLE
[Feature] Allow to use custom shard names

### ISSUE THREAD

**Issue by viraxslot** [microsoft/playwright#26994]
Hi team.

**Use case**:
We currently have a CI/CD pipeline structured as follows:
```build -> deploy to dev -> run tests on dev -> deploy to staging -> run tests on staging -> deploy to prod```

I'd like to add sharding in the "run tests" steps and post the results to slack/allure after each run.
Additionally, I want to rerun failed shard jobs and combine results from both the previously successful runs and the current rerun.

To achieve this, I plan to upload results from shard jobs using separate files.
For example, the filenames might follow this pattern: `slack-results-1-3`, `slack-results-2-3`, `slack-results-3-3`. If I need to rerun the first job, I would simply remove `slack-results-1-3` while preserving the results from the other two jobs.

However, there's a challenge with this approach. Playwright only allows shard names in the format of 1/3, 2/3, and 3/3. Unfortunately, filenames can't contain forward slashes, which complicates the logic for saving artifacts. Custom artifact uploading and downloading require extra effort.

**Feature request**: It would be nice if we could use custom shard names like "1-3", "2-3", and "3-3," or even more descriptive names such as "first-shard", "second-shard" and "third-shard".

I know it's a really minor change but probably it'd be also easy to implement.
Thanks in advance!

**Comment by viraxslot** [comment]
I realized that a workaround could be:
```yaml
jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1/3, 2/3, 3/3]

    steps:
      - name: Convert shard name
        id: convert-shard-name
        env:
          shard: ${{ matrix.shard }}
        run: |
          shard_name="${{ env.shard }}"
          final_shard_name="${shard_name//\//-}"
          echo "shard-name=$final_shard_name" >> $GITHUB_OUTPUT

          echo "Shard name: "$final_shard_name

      - uses: geekyeggo/delete-artifact@v2
        with:
            failOnError: false
            name: |
              "slack-results-${{ steps.convert-shard-name.outputs.shard-name }}"
              "allure-results-${{ steps.convert-shard-name.outputs.shard-name }}"
     
      # other steps
```

But maybe there are other use cases or you have a better option.

**Comment by dgozman** [comment]
@viraxslot Another alternative is to change your matrix's shard to not contain the total:

```yml
jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]

    steps:
      - run: npx playwright test --shard=${{ matrix.shard }}/3
      - uses: geekyeggo/delete-artifact@v2
        with:
            failOnError: false
            name: |
              "slack-results-${{ matrix.shard }}"
              "allure-results-${{ matrix.shard }}"
```
