### ISSUE TITLE
suggestion for pnpm default GitHub Actions workflow

### ISSUE THREAD

**Issue by dtinth** [microsoft/playwright#27202]
When using `pnpm create playwright` with GitHub Actions workflow generation, it does not work by default because **GitHub Actions does not ship with pnpm.**

Suggestion: Replace this

```yaml
      - uses: actions/setup-node@v3
        with:
          node-version: 16
```

With this:

```yaml
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
```

Note that `pnpm/action-setup@v2` must be run first in order for `cache: pnpm` to work.
