### ISSUE TITLE
[BUG] Shard feature sends same group of tests to both shards

### ISSUE THREAD

**Issue by itz4blitz** [microsoft/playwright#27254]
### System info
- Playwright Version: 1.37.1
- Operating System: Linux (Ubuntu 22.04 Desktop)
- Browser: N/A
- Other info: We have 2 self hosted runners running Ubuntu Desktop 

The portion of our yml file with sharding:

```yml
jobs:
  ci:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
       shard: [1/2, 2/2]
```

![image](https://github.com/microsoft/playwright/assets/60281870/191cb5d5-500b-4190-855e-6a6f5dd9c018)

When our tests run however we see the same tests running on each shard:

![image](https://github.com/microsoft/playwright/assets/60281870/371d05a6-df8d-465c-871a-b9577bc47455)

Note that it is in fact sending half of our tests, but it's sending the same half to both shards. Any guidance on how we can resolve this is greatly appreciated.
