### ISSUE TITLE
[Feature] Firefox ESR

### ISSUE THREAD

**Issue by bennypowers** [microsoft/playwright#27542]
https://github.com/microsoft/playwright/issues/10284

We need to test Firefox ESR using playwright. Because our customers and users are running Firefox ESR. I hope it's not necessary to elaborate on why this is necessary and helpful to every playwright user.

Please open an escape hatch so we can bring our own version, or even better enable choice of firefox channels when installing browsers via playwright CLI

The ideal solution would be something like this for users running playwright in github actions:

```yaml
  test:
    name: Browser Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        firefox:
          - latest
          - latest-esr
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configures the node version used on GitHub-hosted runners
      - name: Configure node version
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: npm

      - name: Install Firefox ${{ matrix.firefox }}
        run: npx playwright install firefox@${{ matrix.firefox }}

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run tests
        run: npm test
        if: ${{ always() }}
```
