### ISSUE TITLE
[Actions Docker cont] NPM auth token not passed when using Playwright container

### ISSUE THREAD

**Issue by busybox11** [microsoft/playwright#27572]
### System info
- Playwright Version: [v1.39]
- Operating System: Ubuntu (Github Actions)
- Browser: N/A
- Other info: Using `mcr.microsoft.com/playwright:v1.39.0-jammy` container in Actions

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Config file**

```yml
// .github/workflows/playwright.yml
name: Playwright Tests
on:
  issue_comment:
    types: [created]
  push:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v3
      with:
        node-version: 19
        registry-url: "https://npm.pkg.github.com/"
        scope: "@ORGANIZATION"
        cache: 'npm'

    - run: npm ci

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
```

**Test file (self-contained)**

N/A

**Steps**
- Publish and use private NPM package in GitHub
- Run attached GitHub Actions Playwright workflow
- Monitor `npm ci`

**Expected**

The private `@ORGANIZATION/module` should install fine - just like in [this working example](https://playwright.dev/docs/ci-intro#on-pushpull_request).

**Actual**

The module doesn't install. See following log:

```
> Run npm ci
  npm ci
  shell: sh -e {0}
  env:
    NPM_CONFIG_USERCONFIG: /__w/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@ORGANIZATION/module/version/HASH - unauthenticated: User cannot be authenticated with the token provided.

npm ERR! A complete log of this run can be found in: /github/home/.npm/_logs/DATETIME-debug-0.log
Error: Process completed with exit code 1.
```
