### ISSUE TITLE
[BUG] Merged junit report is showed incorrectly in GitLab CI

### ISSUE THREAD

**Issue by EvgenyWas** [microsoft/playwright#27665]
### System info
- Playwright Version: [v1.37.1]
- Operating System: [Ubuntu 20]
- Browser: [All]
- Other info: Node.js LTS

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```yml
// gitlab-ci.yml
tests_e2e:
  stage: tests_e2e
  image: mcr.microsoft.com/playwright:v1.37.0-jammy
  parallel: 4
  before_script:
    - yarn install --frozen-lockfile
  script: yarn run test:e2e --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL
  artifacts:
    when: always
    name: 'all-blob-reports'
    paths:
      - blob-report
    expire_in: 1 day

tests_e2e_junit_report:
  stage: tests_e2e
  needs: ['tests_e2e']
  when: always
  variables:
    PLAYWRIGHT_JUNIT_OUTPUT_NAME: 'junit-report.xml'
  before_script:
    - yarn install --frozen-lockfile
    - yarn add fast-xml-parser
  script:
    - npx playwright merge-reports ./blob-report --reporter=junit > $PLAYWRIGHT_JUNIT_OUTPUT_NAME
    - node tests/e2e/playwright-junit.js
  artifacts:
    when: on_success
    paths:
      - $PLAYWRIGHT_JUNIT_OUTPUT_NAME
    reports:
      junit: $PLAYWRIGHT_JUNIT_OUTPUT_NAME
    expire_in: 10 days
```

**Steps**
- [Run tests with sharding and blob reporter]
- [Merge blob-reports with junit reporter]
- [Check the merged junit report]

**Expected**
All `testsuite` and `testcase` nodes have unique values in the name attribute in the merged junit report.

**Actual**
We use sharding in our GitLab CI for playwright tests. In `playwright.config` we use `blob` as a reporter and after execution of playwright tests we merge all created blob-reports to junit report as shown in the attached source `gitlab-ci.yml` above.

The merged junit report is correct, but because we run it in different browsers there are different `testsuite` nodes with the same names but different hostname attributes with a browser value.  In each `testsuite` there are `testcase` nodes with repeated values in name attributes. It causes GitLab unit test report misses `testsuite` and `tescase` nodes with repeated names (as it's described in [the doc](https://docs.gitlab.com/ee/ci/testing/unit_test_reports.html#how-to-set-it-up): _You cannot have multiple tests with the same name and class in your JUnit report format XML file._). 
As a result, we have 5 times fewer (we run tests for 5 projects) test cases in the shown GitLab unit report than it should be due to repeated names.

As a workaround, we process the merged junit report by ourselves by adding the string `{hostname} > ` to the begging of each name attribute of all `testsuite` and `testcase` nodes. It happens in `playwright-junit.js` script which you can see in the attached `gitlab-ci.yml` above.
