### ISSUE TITLE
[Feature] merge-reports cli ; Add a command line option : --error-on-failed-tests

### ISSUE THREAD

**Issue by rapidroamer** [microsoft/playwright#28124]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Currently merge-reports utility combines report blobs seamlessly, but it exits with a success even if there are failed tests in the merged report.

Since we mostly use the merge-report in pipelines, it would be beneficial to exit with non-zero code, so that the pipeline knows there are test failures.

Let me know if you need more information.

Using Playwright 1.38.1

**Comment by mxschmitt** [comment]
Which continuous integration provider are you using? Usually for GitHub for example, it looks like this. We have our matrix, there were tests failing, and one merge action. The merge action is always passing but the individual tests are failing. And it shows it as red in the GitHub UI.

<img width="619" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/a09e3bc8-d480-45d4-9f39-49caec85d7e7">

This is the main reason the merge-reports action is not failing when you are merging blobs which have failing tests.

**Comment by rapidroamer** [comment]
Hi @mxschmitt ,
I use gitlab. 

- The pipeline was passing with warnings as I had set `allow_failure` as true for the shard jobs. Setting it to false will correctly update the pipeline status as failed, but I think it will prevent the subsequent jobs (merge reports job) from running. [Gitlab allow_failure](https://docs.gitlab.com/ee/ci/yaml/#allow_failure)
- Anyhow from this conversation I got some point, I will ask playwright to generate junit report as well and add a report parser step in the merge_reports job, it will fail the pipeline if there are any failed tests [GitLab Junit Report](https://docs.gitlab.com/ee/ci/testing/unit_test_report_examples.html)
-  Thanks. This ticket can be closed.

Btw, my current gitlab pipeline:
```
image: <node_image>

stages:
  - build
  - sandbox_tests

sandbox_journeys:
  stage: sandbox_tests
  image: mcr.microsoft.com/playwright:v1.38.1-jammy
  parallel: 2
  before_script:
    - npm run preinstall
  script:
    - npm ci
    - npm run test:ci:sandbox
  allow_failure: true    
  artifacts:
    when: always
    paths:
    - blob-report/**
    expire_in: 60 mins 
  tags: [ runner_tag ]

merge_reports:
  stage: sandbox_tests
  needs: ['sandbox_journeys']
  image: mcr.microsoft.com/playwright:v1.38.1-jammy
  before_script:
    - npm run preinstall
  script:
    - npm ci
    - npx playwright merge-reports --config=playwright.config.ts ./blob-report
  allow_failure: false
  artifacts:
    when: always
    paths:
    - html-report
    expire_in: 5 days
  tags: [ runner_tag ] 
  ```
