### ISSUE TITLE
[BUG] Headless: new feature for chrome extension does not work in github actions env 

### ISSUE THREAD

**Issue by yoaaaav** [microsoft/playwright#28575]
### System info
- Playwright Version: v1.39.0
- Operating System: macOS 13.2
- Browser: Chromium 

I am trying to run a test on my chrome extension. Locally on my mac, after changing the to the headless: new option, it worked. When trying to run it in a Github actions environment - it failed as if I ran it as a normal headless: false. Also, works great as headless: true locally.

### Source code

This is the source test:
```
test("Test Create Ticket", async ({ playwright }) => {
  try {
    const browser = await uploadExtension(playwright);
    const page = await browser.newPage();
    ...
    await loginExtension(page);
    ...
  }
});
```
These are the relevant funtions: 
```
export const uploadExtension = async (playwright: {
  chromium: { launch: (arg0: { args: string[]; headless: boolean }) => any };
}) => {
  const pathToExtension = require("path").join(
    __dirname,
    "../../extension/dist"
  );
  const browserContext = await chromium.launchPersistentContext("", {
    headless: false,
    args: [
      `--headless=new`,
      `--disable-extensions-except=${pathToExtension}`,
      `--load-extension=${pathToExtension}`,
    ],
  });
  return browserContext;
};

export const loginExtension = async (page: Page) => {
  try {
    const popupPromise = page.waitForEvent("popup");
    await page.getByRole("button", { name: "Log In" }).click();
    const popupPage = await popupPromise;
    await loginWebapp(popupPage);
  } catch {
    throw new Error(ERRORS.LOGIN_EXT);
  }
};
```

**Steps**
```
name: Run Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v2

      - name: Checkout Extension Repository
        uses: actions/checkout@v2
        with:
          repository: "extension"
          path: "extension"
          token: ${{ secrets.TOKEN }}

      - name: Build Extension
        run: |
          cd extension
          npm install
          npm run build

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Run Test Create Ticket
        run: |
          if npm run test-create-ticket; then
            echo "test_create_ticket=Success" >> $GITHUB_ENV
          else
            echo "test_create_ticket=Failed" >> $GITHUB_ENV
          fi
```

**Expected**
The test passed as when I run it locally :)

**Actual**
```
Error: page.waitForEvent: Page closed
=========================== logs ===========================
waiting for event "popup"
============================================================

Failed worker ran 1 test:
tests/e2e.spec.ts:14:5 › Test Create Ticket

   at tests/extension.ts:27

  25 | export const loginExtension = async (page: Page) => {
  26 |   try {
> 27 |     const popupPromise = page.waitForEvent("popup");
     |                               ^
  28 |     await page.getByRole("button", { name: "Log In" }).click();
  29 |     const popupPage = await popupPromise;
  30 |     await loginWebapp(popupPage);

    at loginExtension (/home/runner/work/e2e/e2e/tests/extension.ts:27:31)
    at /home/runner/work/e2e/e2e/tests/e2e.spec.ts:25:25


  1) tests/e2e.spec.ts:14:5 › Test Create Ticket ───────────────────────────────────────────────────

    Test timeout of 360000ms exceeded.

  Slow test file: tests/e2e.spec.ts (6.0m)
  Consider splitting slow test files to speed up parallel execution
  1 failed
    tests/e2e.spec.ts:14:5 › Test Create Ticket ────────────────────────────────────────────────────
  1 error was not a part of any test, see above for details
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! e2e@1.0.0 test-create-ticket: `npx playwright test -g "Test Create Ticket" `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the e2e@1.0.0 test-create-ticket script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/[20](https://github.com/quack-io/e2e/actions/runs/7126424534/job/19404286144#step:8:21)[23](https://github.com/quack-io/e2e/actions/runs/7126424534/job/19404286144#step:8:24)-12-07T09_53_[34](https://github.com/quack-io/e2e/actions/runs/7126424534/job/19404286144#step:8:35)_159Z-debug.log
```

@aviramroi
