### ISSUE TITLE
[BUG] Error running tests into Codefresh

### ISSUE THREAD

**Issue by agutierrezasapp** [microsoft/playwright#28600]
1

I have the following code to run the playwright tests into codefresh:

```
    test:
        title: 'Run E2E Tests'
        type: 'freestyle'
        image: 'mcr.microsoft.com/playwright:v1.40.0-jammy'
        working_directory: '${{clone}}'
        stage: test
        fail_fast: false
        commands:
            - npx playwright install --with-deps
            - npx playwright test
```
and I opened the browser to the tests like this:

```
   const browser = await chromium.launchPersistentContext('', {
        args: ['--disable-web-security', '--allow-insecure-localhost', '--no-sandbox', '--disable-setuid-sandbox'],
        bypassCSP: true,
        headless: true,
    });
```
But I have this error when the tests try to run:

```
Executing command:  npx playwright test

Running 2 tests using 1 worker
°
Timed out waiting 1000s for the test suite to run

Timed out waiting 1000s for the teardown for test suite to run

  2 skipped
  Timed out waiting 1000s for the entire test run
Reading environment variable exporting file contents.
Reading environment variable exporting file contents.
```
Any idea?
