### ISSUE TITLE
[BUG] Chromium CI tests ending flaky or failed and not being picked up locally

### ISSUE THREAD

**Issue by lattemisa** [microsoft/playwright#28705]
### System info
- Playwright Version: v.1.40.0
- Operating System: macOS 14.2 
- Browser: Chromium
- Other info: CI GitHub Actions producing flaky tests which are not being picked locally, the environments seem to run very inconsistently

### Source code

ci.yml 
```
run-e2e-test:
    name: run-e2e-tests-${{ matrix.shard }}
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Volta
      uses: volta-cli/action@v4

    - name: Install Node.js 18
      run: volta install node@18

    - name: Use Node.js 18
      run: volta pin node@18

    - name: Add private npm registry
      run: ...

    - name: Node Modules Cache
      uses: actions/cache@v3
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-ci-yarn-${{ hashFiles('**/yarn.lock') }}
    
    - name: Run yarn
      run: yarn --frozen-lockfile

    - name: Install playwright dependencies
      run: yarn playwright install --with-deps

    - name: Run yarn test:e2e --shard=${{ matrix.shard }}/${{ strategy.job-total }}
      run: yarn test:e2e --shard=${{ matrix.shard }}/${{ strategy.job-total }}
```

playwright.config.ts
```
import { PlaywrightTestConfig, devices } from '@playwright/test'
import path from 'path'
import 'whatwg-fetch'

const port = 9000
const baseURL = `http://localhost:${port}/trading/`

const config: PlaywrightTestConfig = {
  timeout: 120 * 1000,
  testDir: path.join(__dirname, 'e2e'),
  retries: 0,
  outputDir: 'test-results/',

  fullyParallel: true,
  workers: 1,

  webServer: {
    command: 'npm run dev',
    port,
  },

  use: {
    trace: 'off',
    baseURL,
    timezoneId: 'UTC',
  },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],
}
export default config

```

Example test using Stencil webcomponent eg <BackButton /> testing is to click on a button which will trigger a modal: 

spec.ts
```
test('Change settings fields invokes confirm modal on back button', async ({
  page,
}) => {
   await page.goto('/create')
   await page.waitForLoadState('domcontentloaded')

  await expect(tradeSettingsModal.getSaveButton()).toHaveAttribute(
    'disabled',
    ''
  )
  const name = page.locator('[data-testid="name-input"]')
  await name.fill('A new record')
  await page
      .getByTestId('back-button')
      .filter({ has: page.getByRole('button') })
      .click()
  const modal = page.locator('[data-testid="modal"]')
  await expect(modal).toHaveCount(1)
})
```

**Actual**

This test and many other pass okay without errors in our local setup but when pushing to the remote, it always complains or randomly fails this and similar tests with interaction on buttons, links with `.click()`.
We mock our apis in the local setup same as we do when running in CI. 
We test against Chromium only. 

CI is listing this kinds of errors: 
```
 - retrying click action, attempt #4
      -   waiting 500ms
      -   waiting for element to be visible, enabled and stable
      -   element is visible, enabled and stable
      -   scrolling into view if needed
      -   done scrolling
```

Strangely, the same test sometimes passes and next time it does not. 
Any guidance would be appreciated.
