### ISSUE TITLE
[Feature] Supporting Centos

### ISSUE THREAD

**Issue by YusuffOzt** [microsoft/playwright#28784]
Playwright version: 1.40.1

My centos version;
"8.8 (Sapphire Caracal)"
"almalinux"
"centos fedora"

Hi,

These days, many companies are still using Centos on the CI CD side.Centos support is very important for us .I am waiting for Centos to be supported, as many users are waiting for Centos to be supported. Are you thinking about a development on this soon? If you can take it into consideration as soon as possible, we would be very happy as all users waiting for Centos support. Because of Centos is not supported, other tools are the reason for choice. While Playwright has such features and is extremely successful in every aspect, I do not want to allow it to be compared with other tools only because it does not support Centos.

I have found a temporary solution on my side;

```
jobs:
  install:
    name: 🔨 Install
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Install CENTOS Packages
        run: |
          sudo yum install -y libatk-1.0.so.0 \
                              libatk-bridge-2.0.so.0 \
                              libcups.so.2 \
                              libdrm.so.2 \
                              libatspi.so.0 \
                              libXcomposite.so.1 \
                              libXdamage.so.1 \
                              libXfixes.so.3 \
                              libXrandr.so.2 \
                              libgbm.so.1 \
                              libpango-1.0.so.0 \
                              libasound.so.2 \
                              atk at-spi2-atk cups-libs libxkbcommon libXcomposite libXdamage libXrandr mesa-libgbm gtk3 \
                              libxshmfence-1.3-2.el8.x86_64
      - name: Install Playwright Browsers
        run: npx playwright install 
      - name: 🎬 Tests Run Playwright tests
        run: npx playwright test --grep-invert login.spec.ts
      - name: Upload blob report to GitHub Actions Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: all-blob-reports
          path: blob-report
          retention-days: 1
      - name: 📜 Merge Reports Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v3
        if: ${{ always() }}
        with:
          name: all-blob-reports
          path: all-blob-reports
      - name: Merge into HTML Report
        if: ${{ always() }}
        run: npx playwright merge-reports --reporter html ./all-blob-reports 
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
         name: html-report-${{ github.run_attempt }}
         path: playwright-report
```

Above GitHub yml content worked about a week but today took a warning like below but I don t know how I can I solve this warning? Using only Desktop Chrome in pw config not firefox and Safari? 

    Error: browserType.launch: 
    ╔══════════════════════════════════════════════════════╗
    ║ Host system is missing dependencies to run browsers. ║
    ║ Please install them with the following command:      ║
    ║                                                      ║
    ║     sudo npx playwright install-deps                 ║
    ║                                                      ║
    ║ Alternatively, use apt:                              ║
    ║     sudo apt-get install libasound2                  ║
    ║                                                      ║
    ║ <3 Playwright Team
