### ISSUE TITLE
[BUG] Reporter list with { printSteps: true } setting is not printing steps in Github Actions

### ISSUE THREAD

**Issue by orabovskyi** [microsoft/playwright#29156]
### System info
- Playwright Version: [v1.41.1]
- Operating System: [Ubuntu 20]
- Browser: [Chromium]

### Source code
playwright-tests.yml
```
name: playwright-tests

on:  
  workflow_dispatch:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test
```

**playwright.config.js**
```
const { defineConfig, devices } = require("@playwright/test");

module.exports = defineConfig({
    // ... 
    reporter: [
        ["list", { printSteps: true }],
    ],
    // ... 
});
```

**test.spec.js**
```
const { test } = require("@playwright/test");

test("Check printing test.step", async ({page}) => {;
    await test.step("Step 1", async () => {
        //...
    });
    await test.step("Step 2", async () => {
        //...
    });
    await test.step("Step 3", async () => {
        //...
    });
});
```

**Steps**
- Run the test on local machine
- Run job on github actions

**Expected**

when test is running on local machine, output looks like this and I expected to see the same in gitaction logs:
```
1 [chromium] › test.spec.js › Check printing test.step (300ms)
1.1 Check printing test.step › Step 1 (100ms)
1.1 Check printing test.step › Step 2 (100ms)
1.1 Check printing test.step › Step 3 (100ms)
```

**Actual**
In git actions logs I see only test details, not steps
`1 [chromium] › test.spec.js › Check printing test.step (300ms)`
