### ISSUE TITLE
[Bug]: Github action caching not working for Webkit 

### ISSUE THREAD

**Issue by twalshOG** [microsoft/playwright#29946]
### Version

1.42.1

### Steps to reproduce

1. Create a new [Playwright project](https://playwright.dev/docs/intro#installing-playwright) - my example uses the Yarn version
2. Add caching 
``` yaml
name: Example 
on:
  workflow_dispatch:

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    env:
      PW_VERSION:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PW_VERSION=$(yarn list --pattern '@playwright/test' --depth=0 --json --non-interactive --no-progress | jq -r '.data.trees[].name' | cut -d'@' -f 3)" >> $GITHUB_ENV
      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PW_VERSION  }}
      - run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - name: Run tests
        run: npx playwright test
```
3. Run twice, note that the webkit tests will fail on the second run

### Expected behavior

Caching would work for webkit the way it does for the chromium and firefox browsers

### Actual behavior

Test fails with the following message

```
    Error: browserType.launch: Target page, context or browser has been closed
    Browser logs:

    <launching> /home/runner/.cache/ms-playwright/webkit-1983/pw_run.sh --inspector-pipe --headless --no-startup-window
    <launched> pid=4323
    [pid=4323][err] /home/runner/.cache/ms-playwright/webkit-1983/minibrowser-wpe/bin/MiniBrowser: error while loading shared libraries: libwoff2dec.so.1.0.2: cannot open shared object file: No such file or directory
    Call log:
      - <launching> /home/runner/.cache/ms-playwright/webkit-1983/pw_run.sh --inspector-pipe --headless --no-startup-window
      - <launched> pid=4323
      - [pid=4323][err] /home/runner/.cache/ms-playwright/webkit-1983/minibrowser-wpe/bin/MiniBrowser: error while loading shared libraries: libwoff2dec.so.1.0.2: cannot open shared object file: No such file or directory
```

### Additional context

Example
``` yaml
      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PW_VERSION=$(yarn list --pattern '@playwright/test' --depth=0 --json --non-interactive --no-progress | jq -r '.data.trees[].name' | cut -d'@' -f 3)" >> $GITHUB_ENV
      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PW_VERSION  }}
      - run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
```

Work around is to add logic to just doe the webkit piece
```
      ###### The webkit browser is not cached the same way and must be reinstalled even with caching ######
      - run: npx playwright install --with-deps webkit
        if: ${{ steps.playwright-cache.outputs.cache-hit == 'true' && (inputs.type == 'webkit' || inputs.type == 'all') }}
```

### Environment

```shell
System:
  OS: Linux
  CPU: (8) arm64
  Ubuntu: 22.04.4 LTS
  Image: ubuntu-22.04 (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md)
  Version: 20240310.1.0
Binaries:
  Node: 18.16.0
  npm: 9.5.1
  yarn: 1.22.22
npmPackages:
  @playwright/test: 1.42.1 => 1.42.1
```
