### ISSUE TITLE
[Bug]: GH-Actions: Firefox installed but test run shows executable doesn't exist

### ISSUE THREAD

**Issue by kiranparajuli589** [microsoft/playwright#29960]
### Version

1.42.0

### Steps to reproduce

GitHub Actions like:

```
jobs:
  tests:
    name: Playwright Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # chromium, chrome, chrome-beta, msedge, msedge-beta, msedge-dev, firefox, firefox-asan, webkit
        browser:
          - project: Chromium
            package: chromium
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJS with Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Start Web App
        run: |
          cp .env.ci .env
          cat .env
          yarn dev &
          sleep 10
      - name: Install Browsers
        run: |
          sudo apt-get update
          sudo apt-get install -y wait-for-it
          npx playwright install --with-deps ${{ matrix.browser.package }}
      - name: Run Tests
        run: yarn test --project ${{ matrix.browser.project }}
```

### Expected behavior

Test should be running using the firefox browser.

### Actual behavior

Logs from `npx playwright install --with-deps firefox`
```
Downloading Firefox 123.0 (playwright build v1440) from https://playwright.azureedge.net/builds/firefox/1440/firefox-ubuntu-22.04.zip
|                                                                                |   0% of 84.7 MiB
|■■■■■■■■                                                                        |  10% of 84.7 MiB
|■■■■■■■■■■■■■■■■                                                                |  20% of 84.7 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 84.7 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 84.7 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 84.7 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 84.7 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 84.7 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 84.7 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 84.7 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 84.7 MiB
Firefox [1](https://github.com/Softverse-Technology/ourbuddy-front-users/actions/runs/8299408174/job/22715026638#step:7:1)23.0 (playwright build v1[4](https://github.com/Softverse-Technology/ourbuddy-front-users/actions/runs/8299408174/job/22715026638#step:7:5)40) downloaded to /home/runner/.cache/ms-playwright/firefox-[14](https://github.com/Softverse-Technology/ourbuddy-front-users/actions/runs/8299408174/job/22715026638#step:7:15)[40](https://github.com/Softverse-Technology/ourbuddy-front-users/actions/runs/8299408174/job/22715026638#step:7:41)
```

Logs from test run command:
```
yarn test --project Firefox

Error: browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium-1105/chrome-linux/chrome
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     yarn playwright install                                             ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝
```

### Additional context

Playwright config:

```
import {defineConfig, devices} from '@playwright/test';
import {Environment} from './environment';

/**
 * @see https://playwright.dev/docs/test-configuration
 */
module.exports = defineConfig({
    testDir: './tests',
    /* Fail the build on CI if you accidentally left test.only in the source code. */
    forbidOnly: !!Environment.CI,
    /* Retry on CI only */
    retries: Environment.CI ? 1 : 0,
    /* Reporter to use. See https://playwright.dev/docs/test-reporters */
    reporter: [
        ["list", {printSteps: true}],
        ["html", {outputFolder: 'playwright-report', open: 'never'}],
    ],
    /* Timeouts. See https://playwright.dev/docs/test-timeouts */
    timeout: Environment.PlaywrightTimeout,
    expect: {
        timeout: Environment.PlaywrightExpectTimeout,
        toHaveScreenshot: {
            maxDiffPixels: 100,
        }
    },
    /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
    use: {
        ignoreHTTPSErrors: true,
        /* Base URL to use in actions like `await page.goto('/')`. */
        baseURL: Environment.BaseUrl,
        locale: "en-US",
        permissions: ["camera", "microphone", "geolocation"],
        // Capture screenshot after each test failure.
        screenshot: 'only-on-failure',
        // Record trace only when retrying a test for the first time.
        trace: 'on-first-retry',
        // Record video only when retrying a test for the first time.
        video: 'on-first-retry',
        headless: Environment.PlaywrightHeadless,
        browserName: 'chromium',
        launchOptions: {
            // Slow down Playwright operations by the specified amount of milliseconds.
            slowMo: Environment.PlaywrightSlowMo,
        },
    },

    /* Configure projects for major browsers */
    projects: [
        { name: 'Chromium', use: {...devices['Desktop Chrome']}},
        { name: 'Firefox', use: {...devices['Desktop Firefox']}},
        { name: 'Webkit', use: {...devices['Desktop Safari']}},
        /* Test against mobile viewports. */
        { name: 'MobileChrome', use: {...devices['Pixel 5']}},
        { name: 'MobileSafari', use: {...devices['iPhone 12']}},
        /* Test against branded browsers. */
        { name: 'MicrosoftEdge', use: {...devices['Desktop Edge'], channel: 'msedge'}},
        { name: 'GoogleChrome', use: {...devices['Desktop Chrome'], channel: 'chrome'}},
    ],
});
```

### Environment

```shell
System: Github Action
OS: ubuntu-latest
```
