### ISSUE TITLE
[Feature]: leverage docker container with Bun preinstalled

### ISSUE THREAD

**Issue by kkortes** [microsoft/playwright#30297]
### 🚀 Feature Request

I'm loving the ease-of-use docker images that you are providing. We're running `:v1.43.0-focal` to great success on our CI's.

It would be lovely with one that has Bun pre-installed.

I understand that it's easy to build your own image that either inherits from the ones you are providing or that simply installs playwright manually. However that would mean my team would manually have to create and publish a new such image every time you bump playwright.

### Example

`.github/workflows/playwright.yml`

```
jobs:
  playwright:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.43.0-bun
```

### Motivation

Now that playwright officially supports running in Bun runtime I'd love for there to be a docker image that has Bun preinstalled.

I noticed a bunch of upsides of using Bun for running playwright over Node. It's slightly faster and installation process for packages is way faster.
