### ISSUE TITLE
[Bug]: Corepack eneable pnpm does not work in playwright image 1.43.X anymore

### ISSUE THREAD

**Issue by MurmelStar** [microsoft/playwright#30400]
### Version

1.43.1-focal

### Steps to reproduce

gitlab-ci.yml job:

```
1.43.1 does not work anymore:
    stage: Quality Assurance
    image: $URL/playwright:v1.43.1-focal
    script: 
        - corepack enable pnpm
        - pnpm -v
```

### Expected behavior

Output of the version of pnpm (and a working pnpm version)

### Actual behavior

Gitlab console output:
```
$ corepack enable pnpm
$ pnpm -v
Internal Error: Error when performing the request to https://registry.npmjs.org/pnpm; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
    at fetch (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:22882:11)
    at async fetchAsJson (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:22896:20)
    at async fetchLatestStableVersion (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:22948:20)
    at async fetchLatestStableVersion2 (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:22971:14)
    at async Engine.getDefaultVersion (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:23349:25)
    at async executePackageManagerRequest (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:24207:28)
    at async BinaryCommand.validateAndExecute (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:211[73](https://git.dataport.de/pvog/tests/systemtest_frontend/-/jobs/3647020#L73):22)
    at async _Cli.run (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:22148:18)
    at async Object.runMain (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:24279:12)
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: command terminated with exit code 1
```

### Additional context

We installed pnpm with `corepack enable pnpm` how it is mentioned in the documentation of corepack and pnpm in the newest version:
https://pnpm.io/installation

The same example will work, if the image `playwright:v1.42.1-focal` will be used.

I used this 4 examples to verify, that it broke in the mentioned minor update. I do use a private Artifactory and some Proxys in my before script of the job. The error does exist since 1.43.0 and still in exist 1.43.1
```yaml
1.42.1 Works:
    stage: Quality Assurance
    image: $ARTIFACTORY_URL/playwright:v1.42.1-focal
    script: 
        - node --version
        - corepack enable pnpm
        - pnpm -v

1.43.1 not working:
    stage: Quality Assurance
    image: $ARTIFACTORY_URL/playwright:v1.43.1-focal
    script: 
        - node --version
        - corepack enable pnpm
        - pnpm -v

1.43.1 pnpm installation fails because of existing not working installation:
    stage: Quality Assurance
    image: $ARTIFACTORY_URL/playwright:v1.43.1-focal
    script: 
        - node --version
        - corepack enable pnpm
        - npm install -g pnpm

1.43.1 overwrite pnpm installation and it works:
    stage: Quality Assurance
    image: $ARTIFACTORY_URL/playwright:v1.43.1-focal
    script: 
        - node --version
        - corepack enable pnpm
        - npm install -g pnpm --force
        - pnpm -v
```

### Environment

```shell
$ node --version
v20.12.2
$ pnpm -v
9.0.1
$ npm -v
10.5.0
$ corepack -v
0.25.2
```
