### ISSUE TITLE
[Bug]:  electron.launch: Process failed to launch on Bitbucket pipeline

### ISSUE THREAD

**Issue by Aenardhil** [microsoft/playwright#30412]
### Version

1.41.1

### Steps to reproduce

1. Push my repository with my .yml file with this content:
`#  Configuration for bitbucket pipeline testing

```yml
image: node:18.18.0

pipelines:
  default:
    - parallel:
        - step:
            name: Code test electron
            size: 2x
            script:
              - apt-get update && apt-get install -y curl libglib2.0-dev libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev libasound2-dev && apt-get clean 
              - cd electron-desktop
              - npm install
              - npm run electron:build
              - npm run test:debug:linux
            caches:
              - node
definitions:
  services:
    docker:
      memory: 7128`

test:debug:linux calls this: "test:debug:linux": "DEBUG=pw:browser npx playwright test", 
```

And the test: 
```ts
import { ElectronApplication, _electron as electron } from 'playwright';
const { test, expect } = require('@playwright/test');

let electronApplication: ElectronApplication;

test.beforeAll(async () => {
	// set the CI environment variable to true
	process.env.CI = 'e2e';
});

test.beforeEach(async () => {
	try {
		electronApplication = await electron.launch({
			args: [ 'dist/main.js' ],
			env: {
				...process.env,
			} as any,
		});
	} catch (error) {
		// console.error('Error launching Electron application:', error);
	}

});

test('app should not be packaged', async () => {
	const isPackaged = await electronApplication.evaluate(async ({ app }) => {
		// This runs in Electrone's main process, parameter here is always
		// the result of the require('electron') in the main app script.
		return app.isPackaged;
	});
	expect(isPackaged).toBe(false);
});

test.afterEach(async () => {
	await electronApplication.close();
});
```

2. wait until de execution of the steps in the pipline are finished

### Expected behavior

The test has to be passed.

### Actual behavior

```
> DEBUG=pw:browser npx playwright test
Running 4 tests using 1 worker
  pw:browser <launching> /opt/atlassian/pipelines/agent/build/electron-desktop/node_modules/electron/dist/electron -r /opt/atlassian/pipelines/agent/build/electron-desktop/node_modules/playwright-core/lib/server/electron/loader.js --no-sandbox --inspect=0 --remote-debugging-port=0 dist/main.js +0ms
  pw:browser <launched> pid=2510 +8ms
  pw:browser [pid=2510][err] [2510:0417/152446.821992:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory +66ms
  pw:browser [pid=2510][err] Debugger listening on ws://127.0.0.1:42529/f6329427-510a-4f9c-a49d-7d22e07004bf +41ms
  pw:browser [pid=2510][err] For help, see: https://nodejs.org/en/docs/inspector +0ms
  pw:browser <ws connecting> ws://127.0.0.1:42529/f6329427-510a-4f9c-a49d-7d22e07004bf +1ms
  pw:browser <ws connected> ws://127.0.0.1:42529/f6329427-510a-4f9c-a49d-7d22e07004bf +10ms
  pw:browser [pid=2510][err] Debugger attached. +0ms
  pw:browser [pid=2510][err] [2510:0417/152447.115131:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY +240ms
  pw:browser [pid=2510][err] [2510:0417/152447.115154:ERROR:env.cc(255)] The platform failed to initialize.  Exiting. +0ms
  pw:browser [pid=2510][err] Waiting for the debugger to disconnect... +1ms
  pw:browser <ws disconnecting> ws://127.0.0.1:42529/f6329427-510a-4f9c-a49d-7d22e07004bf +0ms
  pw:browser <ws disconnected> ws://127.0.0.1:42529/f6329427-510a-4f9c-a49d-7d22e07004bf code=1005 reason= +5ms
  pw:browser [pid=2510][err] The futex facility returned an unexpected error code. +0ms
  pw:browser [pid=2510] <process did exit: exitCode=null, signal=SIGABRT> +3ms
  pw:browser [pid=2510] starting temporary directories cleanup +0ms
  pw:browser [pid=2510] finished temporary directories cleanup +12ms
  
  1) pharmac.spec.ts:41:1 › app should not be packaged ─────────────────────────────────────────────
    TypeError: Cannot read properties of undefined (reading 'evaluate')
      40 |
      41 | test('app should not be packaged', async () => {
    > 42 | 	const isPackaged = await electronApplication.evaluate(async ({ app }) => {
         | 	                                             ^
      43 | 		// This runs in Electron's main process, parameter here is always
      44 | 		// the result of the require('electron') in the main app script.
      45 | 		return app.isPackaged;
        at /opt/atlassian/pipelines/agent/build/electron-desktop/testing/e2e-tests/pharmac.spec.ts:42:47
    TypeError: Cannot read properties of undefined (reading 'close')

1 failed
    pharmac.spec.ts:41:1 › app should not be packaged ──────────────────────────────────────────────`
```

### Additional context

This is an  electron application that uses static files from a vuejs project

### Environment

```shell
System:
  OS: Debian GNU/Linux 12 (bookworm)
  CPU: (8) arm64
Binaries:
  Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
  npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
npmPackages:
  @playwright/test: 1.41.1 => 1.41.1
```
