### ISSUE TITLE
[Bug]: `merge-report` does not generate any output for the HTML reporter

### ISSUE THREAD

**Issue by OptimusCrime** [microsoft/playwright#31417]
### Version

1.44.1

### Steps to reproduce

We have copied the blueprint for combining reports into a single report in a GitHub action:

```
      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge into HTML Report
        env:
          CI: true
          PW_TEST_HTML_REPORT_OPEN: never
        run: npx playwright merge-reports --reporter=html ./all-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 14
```

From: https://playwright.dev/docs/test-sharding#github-actions-example

The output:

```
merging reports from /home/runner/path/to/workspace/all-blob-reports
extracting: all-blob-reports/report-1.zip
extracting: all-blob-reports/report-2.zip
extracting: all-blob-reports/report-3.zip
-----
Warning: No files were found with the provided path: playwright-report. No artifacts will be uploaded.
```

### Expected behavior

I expect the report to be in the `playwright-report` directory. 

### Actual behavior

There's no output from the merged report, without any explanation as to why.

### Additional context

This problem seems to happen sporadically, but I can't narrow down when it works and when it does not work. I originally though that it had something to do with rerunning jobs, but I don't think so.

I have also tried to sleep after generating the report, in case this was a timing issue. No luck. I have also tried to `ls` the contents of the work directory and the `playwright-report` directory, but sometimes it is just outright missing.

There is nothing in the `merge-report` output that ever explains what went wrong.

### Environment

```shell
N/A. Running on GitHub Actions.
```
