### ISSUE TITLE
[Bug]: Merge shards report to html doesn't work on azure pipelines and gives error Error: No report files found  however the artifacts downloaded successfully to the path

### ISSUE THREAD

**Issue by MrGeek14** [microsoft/playwright#31550]
### Version

1.44.1

### Steps to reproduce

Run playwright test on azure devops pipeline using shards
merge blob reports generated from shards into single html report

### Expected behavior

Merging blob reports generated from shards to a single html report

### Actual behavior

Gives  Error: No report files found  however the artifacts downloaded successfully to the path

### Environment

```shell
azure devops pipeline yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: playwright_tests
  displayName: 'Run Playwright Tests'
  strategy:
    matrix:
      chromium-1:
        project: Chrome
        shardIndex: 1
      chromium-2:
        project: Chrome
        shardIndex: 2

  steps:
  - checkout: self
  - task: NodeTool@0
    inputs:
      versionSpec: '18'
    displayName: 'Install Node.js'

  - script: |
      npm ci
    displayName: 'Install dependencies'

  - script: |
      npx playwright install --with-deps
    displayName: 'Install Playwright Browsers'

  - script: |
      npx playwright test --project=$(project) --shard=$(shardIndex)/2
    displayName: 'Run Playwright tests'
    env:
      CI: 'true'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'blob-report'
      artifactName: 'blob-report-$(shardIndex)'
      publishLocation: 'pipeline'

- job: merge_reports
  displayName: 'Merge Reports into HTML'
  dependsOn: playwright_tests
  condition: always()

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
  - task: NodeTool@0
    inputs:
      versionSpec: '18'
    displayName: 'Install Node.js'

  - script: |
      npm ci
    displayName: 'Install dependencies'

  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName:
      targetPath: 'all-blob-reports'

  
  - script: |
      npx playwright merge-reports --reporter html ./all-blob-reports
    displayName: 'Merge into HTML Report'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'playwright-report'
      artifactName: 'html-report-$(Build.BuildId)-attempt-$(System.JobAttempt)'
      publishLocation: 'pipeline'
      retention: '7'
```

**Comment by mxschmitt** [comment]
Looks like Azure doesn't support the `merge-multiple` feature like GitHub Actions does. Hence you need to download each artifact manually, this e.g. is working: https://github.com/mxschmitt/azdo-playwright-merge/blob/master/pipeline.yml

**Comment by MrGeek14** [comment]
@mxschmitt  merging and build report working now with me also but the merge task itself took more than one hour and according to that it is failed on agent , do u have any idea why this is happened?
<img width="647" alt="2024-07-08_16h32_34" src="https://github.com/microsoft/playwright/assets/30673179/88767d06-d4a0-4dca-bcb7-46d938416f19">

**Comment by mxschmitt** [comment]
Hard to judge what the reason is. Ideally the merge process should be fast. How many tests do you have? Do you have video enabled? Do you know how large an individual blob is?

**Comment by MrGeek14** [comment]
@mxschmitt run one script has 8 tests, yes enable video in case failure and each blob is about 180 MB and have 2 of them

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.

**Comment by JoepKockelkorn** [comment]
> Looks like Azure doesn't support the `merge-multiple` feature like GitHub Actions does. Hence you need to download each artifact manually, this e.g. is working: https://github.com/mxschmitt/azdo-playwright-merge/blob/master/pipeline.yml

Link to actual intended code: https://github.com/mxschmitt/azdo-playwright-merge/blob/2b805df9a1c68a2c1fc04ef5a0e469894501d80f/pipeline.yml

**Comment by JoepKockelkorn** [comment]
Instead of hardcoding each download task I used a script to move all zip files one level up so `merge-results` works properly:
```yml
parameters:
  - name: parallelTestJobs
    type: number
    default: 3

trigger: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    steps:
      - template: templates/node-and-npm-install.yml

      - script: npm run build
        displayName: 'Build App'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish App artifact'
        inputs:
          targetPath: $(System.DefaultWorkingDirectory)/dist
          artifactName: App

  - job: Test
    dependsOn: Build
    strategy:
      parallel: ${{ parameters.parallelTestJobs }}
    steps:
      - template: templates/node-and-npm-install.yml

      - script: npx playwright install --with-deps
        displayName: 'Install Playwright browsers'

      - task: DownloadPipelineArtifact@2
        displayName: 'Download Build artifact'
        inputs:
          artifact: App
          targetPath: $(System.DefaultWorkingDirectory)/dist

      - script: npx playwright test -c ./e2e/config/playwright.config.ts --shard=$(System.JobPositionInPhase)/$(System.TotalJobsInPhase)
        displayName: 'Run E2E tests'
        env:
          CI: 'true'

      - task: PublishTestResults@2
        displayName: 'Publish JUnit test results'
        inputs:
          searchFolder: 'e2e/artifacts'
          testResultsFormat: 'JUnit'
          testResultsFiles: 'e2e-junit-results.xml'
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: 'E2E Test Run $(System.JobPositionInPhase)/$(System.TotalJobsInPhase)'
        condition: succeededOrFailed()

      - bash: |
          folder=./blob-report
          result=$(test -d $folder && echo true || echo false)
          echo "Folder $folder exists? $result"
          echo "##vso[task.setvariable variable=playwrightArtifactsExists]$result"
        displayName: 'Check if playwright artifacts exist'
        condition: succeededOrFailed()

      - task: PublishPipelineArtifact@1
        displayName: 'Publish playwright artifacts'
        inputs:
          targetPath: blob-report
          artifact: blob-report-$(System.JobPositionInPhase)
          publishLocation: 'pipeline'
        condition: and(succeededOrFailed(), eq(variables.playwrightArtifactsExists, 'true'))

  - job: MergeReports
    dependsOn: Test
    condition: succeededOrFailed()
    steps:
      - template: templates/node-and-npm-install.yml

      - task: DownloadPipelineArtifact@2
        displayName: 'Download playwright artifacts'
        inputs:
          patterns: blob-report-*/**
          targetPath: all-artifacts

      - script: |
          mkdir -p all-blob-reports
          mv all-artifacts/**/*.zip all-blob-reports/
        displayName: 'Copy *.zip files to single folder'

      - script: npx playwright merge-reports --reporter html ./all-blob-reports
        displayName: 'Merge Playwright reports'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish merged Playwright report'
        inputs:
          targetPath: playwright-report
          artifactName: playwright-report

```
