### ISSUE TITLE
[Bug]: connection refused when accessing localhost in github actions

### ISSUE THREAD

**Issue by BuistvoPloti** [microsoft/playwright#31670]
### Version

1.44.0

### Steps to reproduce

here's my github actions file

```
name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: node:18
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Frontend Repo
        uses: actions/checkout@v4
        with:
          repository: repo
          path: frontend

      - name: Install Dependencies for Frontend
        run: npm install
        working-directory: ./frontend

      - name: Start Frontend
        run: npm run start &

      - name: Check if port 3000 is accessible
        run: |
          sleep 7
          curl --fail https://localhost:3000 || exit 1
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Playwright Deps
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
```

FE starts fine, 3000 port is accessible (see curl step), any other url like google.com is accessible either

my simple test file
playwright version 1.44.0

```
import { test, expect } from '@playwright/test';

test.beforeEach(async ({ page }) => {
	await page.goto('https://localhost:3000/admin');
});
```

### Expected behavior

its not related to using http over https or 121.0.0.1 over localhost I guess, I tried switching between these

### Actual behavior

I'm getting this error
```
  1) [chromium] › login.spec.ts:15:5 › Test temp ──────────────────

    Error: page.goto: net::ERR_CONNECTION_REFUSED at https://localhost:3000/admin
    Call log:
      - navigating to "https://localhost:3000/admin", waiting until "load"
```

What am I missing? any help appreciated
I Don't think it is really a bug though, just need someone's fresh view on it

### Environment

```shell
runs-on: ubuntu-latest
    container:
      image: node:18
```
