### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by bachhavdipak** [microsoft/playwright#32152]
### Version

1.42.1

### Steps to reproduce

I am encountering an issue while running my test suite against the Edge browser through my CI/CD pipeline. The error message I am receiving is as follows:

```
browserType.launch: Chromium distribution 'msedge' is not found at /opt/microsoft/msedge/msedge
Run "npx playwright install msedge"
```
I am using the mcr.microsoft.com/playwright:v1.42.1-jammy Docker image, and I have noticed that, unlike Chrome, Edge does not seem to be included by default in this image. I am curious to understand if Edge needs to be installed separately, or if there is a specific configuration required.

I have attempted to install Edge using the following script steps:
```

- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'
- script: npm ci
  displayName: 'npm ci'
- script: npx playwright install msedge
  displayName: 'npx playwright install msedge'
```

However, the process seems to require switching to the root user to install dependencies, which is not feasible in my current setup.

Could you please provide guidance on how to properly configure the environment to use Edge with Playwright in my CI/CD pipeline? Any assistance or recommendations would be greatly appreciated.

### Expected behavior

Unable to trigger execution against edge browser.

### Actual behavior

I am encountering an issue while running my test suite against the Edge browser through my CI/CD pipeline. The error message I am receiving is as follows:

```
browserType.launch: Chromium distribution 'msedge' is not found at /opt/microsoft/msedge/msedge
Run "npx playwright install msedge"
```

### Environment

```shell
Ubuntu
```
