### ISSUE TITLE
[Feature]: Add optional suffix to `🎭 Playwright Run Summary`

### ISSUE THREAD

**Issue by jsoref** [microsoft/playwright#32178]
### 🚀 Feature Request

I'd like to be able to add a suffix to the github step summary

### Example

`.github/workflows/smoke-test.yml`:
```yml
on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

name: Smoke Tests

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  smoke-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        instance:
          - alpha
          - beta
          - gamma
          - delta
          - epsilon
          - zeta
          - eta
          - theta 
          - iota
        playwright-projects:
          - Sigma
        include:
          - instance: kappa
            playwright-projects: Nu Xi Omicron Pi Rho Sigma

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          corepack enable
          yarn install
      - name: Run smoke tests
        env:
          PROJECTS: ${{ matrix.playwright-projects }}
          INSTANCE: ${{ matrix.instance }}
        run: |
          yarn test --project "$PROJECTS" --workers=4 --summary-suffix="$INSTANCE ($PROJECTS)"
```

`package.json`:
```json
{
  "name": "...",
  "version": "1.0.0",
  "main": "index.js",
  "license": "UNLICENSED",
  "scripts": {
    "test": "playwright test",
    "test-headed": "playwright test --headed",
    "test-ui": "playwright test --ui",
    "report": "playwright show-report",
    "codegen": "playwright codegen"
  },
  "devDependencies": {
    "@playwright/test": "1.46.0",
    "@types/node": "20.14.14",
    "dotenv": "16.4.5",
    "prettier": "3.3.3"
  },
  "packageManager": "yarn@4.3.1"
}
```

### Motivation

I'd like to see output that's slightly more descriptive than:
![image](https://github.com/user-attachments/assets/bcbe5ce9-24be-4d41-ba06-e25c44c3747b)
