### ISSUE TITLE
[Bug]: Using--only-changed=$GITHUB_BASE_REF (or --only-changed=main) option to run only changed tests, results in a error in GitHub

### ISSUE THREAD

**Issue by PramodKumarYadav** [microsoft/playwright#32452]
### Version

1.46.1

### Steps:

1. Copy the workflow from as shown in the official playwright docs from here: https://playwright.dev/docs/ci-intro#fail-fast 
2. Paste to your test repository.
3. Change a test file. 
4. Create a pull request with this file to the main branch. 

### Expected behavior

This should trigger the workflow and run changed tests. 

### Actual behavior

We instead get this error. 
[test](https://github.com/PramodKumarYadav/playwright-sandbox/actions/runs/10709495253/job/29694251448#step:6:8)
```
Error: The repository is a shallow clone and does not have 'main' available locally.
Note that GitHub Actions checkout is shallow by default: https://github.com/actions/checkout
```

### Environment

```shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 21.78 GB / 64.00 GB
  Binaries:
    Node: 21.6.2 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.46.1 => 1.46.1
```

**Comment by Skn0tt** [comment]
Thanks for the report! https://github.com/microsoft/playwright/pull/32461 fixes the code snippet that you used. Let me know if it works for you if you use that updated snippet.

**Comment by PramodKumarYadav** [comment]
Hi @`s

> Thanks for the report! #32461 fixes the code snippet that you used. Let me know if it works for you if you use that updated snippet.

Hi SknOtt, Thanks for picking this up! I tried the change and now get another error from git as below.

```
Run CUSTOM_TAG_1="3" npx browserstack-node-sdk playwright test  --shard=$((0 + 1))/3  --grep="@unit-test"  --grep-invert=""  --project=chromium --only-changed=$GITHUB_BASE_REF
2024-09-05 10:54:47 - info: Reading configs from /__w/MercellForms/MercellForms/MercellForms.ComponentTests/browserstack.yml
2024-09-05 10:54:47 - info: Skipping buildIdentifier as BROWSERSTACK_BUILD_NAME is set
Error: Cannot detect changed files for --only-changed mode:
git ls-files --others --exclude-standard

fatal: detected dubious ownership in repository at '/__w/MercellForms/MercellForms'
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/MercellForms/MercellForms
```

I added the command after checkout to see if that makes a difference. 

```
 - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Force a non-shallow checkout, so that we can reference $GITHUB_BASE_REF (needed for the --only-changed option to work)
          # See https://github.com/actions/checkout for more details.
          fetch-depth: 0

      - name: Configure Git safe directory
        run: git config --global --add safe.directory /__w/MercellForms/MercellForms
```

But it didn't. 

 I continue getting the error. Can someone try the change locally and see if it works on their machine?
