### ISSUE TITLE
[Bug]: GitHub action fails - Host system is missing dependencies to run browsers

### ISSUE THREAD

**Issue by dkirrane** [microsoft/playwright#32546]
### Version

1.47.0

### Steps to reproduce

Here is the GitHub action failing. I tried both `ubuntu-latest` and `ubuntu-20.04`

```yaml
name: Playwright Tests

on:
  workflow_dispatch:

jobs:

  Test:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install playwright dependencies
      run: |
        npx playwright install
        npx playwright install-deps

```

### Expected behavior

working install

### Actual behavior

```
Playwright Host validation warning: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Please install them with the following command:      ║
║                                                      ║
║     sudo npx playwright install-deps                 ║
║                                                      ║
║ Alternatively, use apt:                              ║
║     sudo apt-get install libwoff1\                   ║
║         libopus0\                                    ║
║         libwebpdemux2\                               ║
║         libharfbuzz-icu0\                            ║
║         libhyphen0\                                  ║
║         libflite1\                                   ║
║         libegl1\                                     ║
║         libevdev2\                                   ║
║         libgles2\                                    ║
║         gstreamer1.0-libav                           ║
║                                                      ║
║ <3 Playwright Team                                   ║
╚══════════════════════════════════════════════════════╝
    at validateDependenciesLinux (/home/runner/work/playwright/playwright/node_modules/@playwright/test/node_modules/playwright-core/lib/server/registry/dependencies.js:216:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Registry._validateHostRequirements (/home/runner/work/playwright/playwright/node_modules/@playwright/test/node_modules/playwright-core/lib/server/registry/index.js:626:43)
    at async Registry._validateHostRequirementsForExecutableIfNeeded (/home/runner/work/playwright/playwright/node_modules/@playwright/test/node_modules/playwright-core/lib/server/registry/index.js:724:7)
    at async Registry.validateHostRequirementsForExecutablesIfNeeded (/home/runner/work/playwright/playwright/node_modules/@playwright/test/node_modules/playwright-core/lib/server/registry/index.js:[71](https://github.com/avaya/playwright/actions/runs/10797974594/job/29950427027#step:8:72)3:43)
    at async t.<anonymous> (/home/runner/work/playwright/playwright/node_modules/@playwright/test/node_modules/playwright-core/lib/cli/program.js:119:7)
```

### Environment

```shell
Normal `ubuntu-latest` and `ubuntu-20.04` GitHub Action runners
```

**Comment by dgozman** [comment]
@dkirrane I'd recommend following the [getting started guide](https://playwright.dev/docs/ci-intro#setting-up-github-actions) that recommends a single `npx playwright install --with-deps`. Alternatively, you can swap the order of `npx playwright install-deps` and `npx playwright install` commands. Let me know whether that helps.

**Comment by dkirrane** [comment]
@dgozman After banginf my head against this for a few hours, I managed to get it working! Required `sudo` in the GitHub action step for the deps install.

```yaml
    - name: Install playwright dependencies
      run: |
        sudo npx playwright install-deps
        npx playwright install
```

Not sure why this is required but this is probably something that could be called out in the docs here: https://playwright.dev/docs/browsers#install-system-dependencies
