### ISSUE TITLE
[Feature]: allow tracking of skipped/dropped frames, like Chrome's perf recorder does

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/playwright#33080]
### 🚀 Feature Request

It'd be nice if `playwright` could programmatically track dropped frames with and without changes from a commit.

Chrome's performance recorder can do this, but developers have to run it manually.

### Example

```yaml
name: playwright
on: [push]
jobs:
  performance-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Gets the change in dropped frames between the current branch and the main branch
      # (doesn't exist, at the time of this writing)
      - uses: playwright/check-dropped-frames@v1
        with:
          # Post the results as a comment on the commit.
          post-comment: true
```

# Sample Output

Ideally this shows up in CI job output that uses `playwright`, and there's an option to post the this result as a comment on each commit.

```
Saw a 10% increase in dropped frames with this branch
```

### Motivation

This feature would save developers time by automatically showing performance changes from a change without having to run Chrome's performance recorder manually.
