### ISSUE TITLE
[Bug]: Playwright tests are passing locally but failing in GitHub actions (retried for 3 times the same result)

### ISSUE THREAD

**Issue by pavaneeshwar7077** [microsoft/playwright#33091]
### Version

1.36.1

### Steps to reproduce

This is the workflow file we use for installation :

``` yaml
name: CI/CD for Test To Dev

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Create .env File
      run: |
        cd altius-nx
        echo "ENV_REF_NAME=$ENV_REF_NAME" >> .env
        echo "EMAIL=$EMAIL" >> .env
        echo "PASSWORD=$PASSWORD" >> .env
        echo "BASE_URL=$BASE_URL" >> .env
      env:
        ENV_REF_NAME: ${{ secrets.ENV_REF_NAME }}
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        BASE_URL: ${{ secrets.BASE_URL }}

    - name: Install yarn
      run: |
        cd altius-nx
        npm install -g yarn

    - name: Install Project Dependencies
      run: |
        cd altius-nx
        yarn install

    - name: Install Playwright Browsers
      run:  |
        cd altius-nx
        yarn playwright install --with-deps

    - name: Run Playwright tests
      run: |
        cd altius-nx
        yarn test --grep @field

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: altius-nx/playwright-report/index.html
        retention-days: 7

```

### Expected behavior

All the test cases should pass when executed in github actions, they are passing in local 

### Actual behavior

Failing in pipeline ( 1 test case)

### Environment

Node : 18
