### ISSUE TITLE
[Bug]: Error: Process from config.webServer was not able to start. Exit code: 139

### ISSUE THREAD

**Issue by stolinski** [microsoft/playwright#33403]
### Version

1.48.2

### Steps to reproduce

Check https://github.com/syntaxfm/website/actions/runs/11634965150/job/32403313418

Repo here: https://github.com/syntaxfm/website 
Test run fine locally without issue

### Expected behavior

Test to run as they do locally.

### Actual behavior

In the process of 

`pnpx playwright test`

```
[WebServer]     - @babel/preset-typescript
[WebServer]     - @babel/preset-typescript/package.json
[WebServer]   node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/lib/fsevents-handler.js
[WebServer]     - fsevents
[WebServer] Segmentation fault (core dumped)

Error: Process from config.webServer was not able to start. Exit code: 139
```

### Additional context

GH Action code

```
name: Run_Playwright_Tests_on_PRs

on:
  pull_request:
    paths-ignore:
      - 'shows/*.md'

env:
  PUBLIC_GITHUB_ID: ${{ secrets.PUBLIC_GITHUB_ID }}
  GH_SECRET: ${{ secrets.GH_SECRET }}
  DEEPGRAM_SECRET: ${{ secrets.DEEPGRAM_SECRET }}
  PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
  SENTRY_AUTH_TOKEN: ''
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  UPSPLASH_TOKEN: ''
  UPSPLASH_URL: ''
  YOUTUBE_API_KEY: ''

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: pnpm-setup
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Setup DB
        run: pnpm db:generate

      - name: Install playwright browsers
        run: pnpx playwright install --with-deps

      - name: Run Playwright tests
        run: pnpx playwright test

```

### Environment

  System:
    OS: Linux 6.5 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Memory: 14.50 GB / 15.61 GB
    Container: Yes
  Binaries:
    Node: 20.18.0 - /opt/hostedtoolcache/node/20.18.0/x64/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.2 - /opt/hostedtoolcache/node/20.18.0/x64/bin/npm
    pnpm: 8.15.9 - ~/setup-pnpm/node_modules/.bin/pnpm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2
