### ISSUE TITLE
[Bug]: Using Powershell --grep-invert with OR is not working

### ISSUE THREAD

**Issue by omarjyoussef** [microsoft/playwright#33466]
### Version

1.48.2

### Steps to reproduce

In azure pipeline, when running the following task using **powershell**, only the last mention tag will be skipped (@tagTwo):

```
- task: AzureCLI@2
         displayName: Run playwright
         inputs:
             azureSubscription: ${{ parameters.azureSubscription }}
             scriptType: ps
             scriptLocation: inlineScript
             workingDirectory: $(Build.ArtifactStagingDirectory)/frontendProject
             inlineScript: |
                 npx playwright test --shard=${{ worker }}/${{ parameters.maxNumberOfShards }} --grep-invert --% "@tagOne^|@tagTwo"
```

### Expected behavior

I expect tests with any of the mentioned tags to be skipped. In my case, tests with @tagOne and @tagTwo should be skipped.

### Actual behavior

Only tests with the last mention tag will be skipped (@tagTwo).

### Additional context

Using the same pipeline task, but in **Bash**, works fine (tests with @tagOne and @tagTwo are skipped):

```
- task: AzureCLI@2
         displayName: Run playwright
         inputs:
             azureSubscription: ${{ parameters.azureSubscription }}
             scriptType: bash
             scriptLocation: inlineScript
             workingDirectory: $(Build.ArtifactStagingDirectory)/frontendProject
             inlineScript: |
                 npx playwright test --shard=${{ worker }}/${{ parameters.maxNumberOfShards }} --grep-invert "@tagOne|@tagTwo"
```

### Environment

System:
    OS: Windows 10 10.0.20348
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 4.58 GB / 7.00 GB
  Binaries:
    Node: 18.20.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\npm\prefix\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Bash: 5.2.37 - C:\Program Files\Git\bin\bash.EXE
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2
