### ISSUE TITLE
[Feature]: Treat elements as hidden when they are inside an element with height = 0 and overflow hidden

### ISSUE THREAD

**Issue by antti-peltola-refined** [microsoft/playwright#33489]
### 🚀 Feature Request

Elements, that are inside an element that has height 0 and overflow hidden, are treated as visible by playwright. I would like to have them be treated as hidden.

Note: For reasons related to how the transitions should look, I can't have display: none or height: 0, so I can't leverage how the current visibility check works.

### Example

Example html + css:
```html
  <div>
    <div class="wrapper open">
      <div class="content">Should be visible</div>
    </div>

    <div class="wrapper closed">
      <div class="content">Should not be visible, but passes toBeVisible</div>
    </div>
  </div>
``` 

```Css
.wrapper {
  display: grid;
  grid-template-rows: 0fr;
  overflow: hidden;

  &.open {
    grid-template-rows: 1fr;
  }

  &.closed {
    height: 0;
    grid-template-rows: 1fr;
  }
}
``` 
Looks like this:
![Image](https://github.com/user-attachments/assets/b2d14312-c1c0-4577-8108-df1a44ba45c4)

Currently this test passes:

```JS
 await expect(page.getByText('Should be visible')).toBeVisible();
 await expect(page.getByText('Should not be visible, but passes toBeVisible')).toBeVisible();
```

I would like for this to pass instead:
```JS
 await expect(page.getByText('Should be visible')).toBeVisible();
 await expect(page.getByText('Should not be visible, but passes toBeVisible')).toBeHidden();
```

### Motivation

Currently, I need to assert visibility on the wrapper element that has the height 0. I would like to instead be able to assert the actual text element to make my tests more like how the user sees the UI.
