### ISSUE TITLE
[Bug]: Chrome extension test stuck in CI

### ISSUE THREAD

**Issue by BenjaminG** [microsoft/playwright#33928]
### Version

1.49.0

### Steps to reproduce

For any reason I don't manage to make a basic extension test working in our CI (Github Actions)

I followed the example as described here: https://playwright.dev/docs/chrome-extensions with a basic test

playwright.config.ts

```ts
export default defineConfig({
  testDir: './tests',
  // testIgnore: /.*\.(setup|teardown)\.ts/,
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 1 : 0,

  workers: 1,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [
    ['list'],
    ['html', { open: 'on-failure' }],
    ['json', { outputFile: './playwright-report/report.json' }],
  ],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: process.env.MSI_URL,

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on',
  },
  // timeout: 60000,
  /* Configure projects for major browsers */
  projects: [
    {
      name: 'setup auth',
      testMatch: /auth\.setup\.ts/,
      fullyParallel: true,
    },
    {
      name: 'teardown data',
      testMatch: /data\.teardown\.ts/,
    },
    {
      name: 'bootstrap data',
      testMatch: /data\.setup\.ts/,
      dependencies: ['setup auth'],
      teardown: 'teardown data',
    },
    {
      name: 'teardown admin',
      testMatch: /admin\/admin\.teardown\.ts/,
      use: {
        storageState: 'playwright/.auth/admin.json',
      },
    },
    {
      name: 'setup admin',
      testMatch: /admin\/admin\.setup\.ts/,
      dependencies: ['bootstrap data'],
      use: {
        storageState: 'playwright/.auth/admin.json',
      },
      teardown: 'teardown admin',
    },
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        storageState: 'playwright/.auth/user.json',
      },
      dependencies: ['setup admin'],
    },
    {
      name: 'extension tests',
      testMatch: /extension\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        channel: 'chromium',
        serviceWorkers: 'allow',
        bypassCSP: true,
      },
    },
  ],
});
```

exension.fixtures.ts
```ts
import path from 'path';

import { test as base, chromium, type BrowserContext } from '@playwright/test';

export const test = base.extend<{
  context: BrowserContext;
  extensionId: string;
}>({
  context: async ({ context: _ }, use) => {
    const pathToExtension = path.join(__dirname, '../../../web/dist');

    const context = await chromium.launchPersistentContext('', {
      channel: 'chromium',
      args: [
        `--disable-extensions-except=${pathToExtension}`,
        `--load-extension=${pathToExtension}`,
      ],
    });
    await use(context);
    await context.close();
  },
  extensionId: async ({ context }, use) => {
    let [background] = context.serviceWorkers();
    if (!background) {
      console.log('Waiting for service worker...');
      try {
        background = await context.waitForEvent('serviceworker', {
          timeout: 60000,
        });
      } catch (error) {
        console.error('Service worker load error:', error);
        throw error;
      }
    }

    const extensionId = background.url().split('/')[2];
    if (!extensionId) {
      throw new Error('Could not determine extension ID');
    }

    await use(extensionId);
  },
});

export const expect = test.expect;
```

extension.spec.ts
```ts
import { test, expect } from './fixtures/extension.fixtures';

test.describe('Extension', () => {
  test('login flow', async ({ page, extensionId }) => {
    await page.goto(`chrome-extension://${extensionId}/index.html`);

    const emailInput = page.getByLabel('Email address');
    const passwordInput = page.getByLabel('Password');
    await emailInput.click();
    await emailInput.fill(process.env.E2E_EMAIL!);
    await passwordInput.click();
    await passwordInput.fill(process.env.E2E_PASSWORD!);

    const submitButton = page.getByRole('button', {
      name: 'Sign in',
      exact: true,
    });

    await submitButton.click();

    await page.pause();

    await expect(
      page.getByText('To see this section, please extend to wide mode'),
    ).toBeVisible();
  });
});
```

Github Action:

```yaml
name: Playwright Tests
on:
  workflow_call:
    secrets:
       ***

env:
   ***

jobs:
  run-e2e:
    name: Run Playwright tests
    environment: dev
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '20'
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Build extension
        run: pnpm extension extension:build
      - name: Install E2E dependencies
        working-directory: ./apps/e2e
        run: pnpm install
      - name: Install Playwright Browsers
        working-directory: ./apps/e2e
        run: pnpx playwright install --with-deps chromium
      - name: Run Playwright tests
        working-directory: ./apps/e2e
        run: pnpm test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        id: upload-report
        with:
          name: playwright-report
          path: apps/e2e/playwright-report/
          retention-days: 30
      - uses: daun/playwright-report-summary@v3
        if: ${{ !cancelled() }}
        with:
          report-file: apps/e2e/playwright-report/report.json
          job-summary: true
          report-url: ${{ steps.upload-report.outputs.artifact-url }}

```

### Expected behavior

The test should pass.

### Actual behavior

The test suite is passing without any problem in local environment
I also have tested the action in local with [act](https://github.com/nektos/act) and it passes too

In GHA, I have the following error every time:

```
✘  3 [extension tests] › extension.spec.ts:4:7 › Extension › login flow (30.1s)
Waiting for service worker...
Service worker load error: browserContext.waitForEvent: Target page, context or browser has been closed
    at Object.extensionId (/home/runner/work/msi/msi/apps/e2e/tests/fixtures/extension.fixtures.ts:29:36) {
  [Symbol(step)]: {
    stepId: 'pw:api@11',
    location: {
      file: '/home/runner/work/msi/msi/apps/e2e/tests/fixtures/extension.fixtures.ts',
      line: 29,
      column: 36,
      function: 'Object.extensionId'
    },
    category: 'pw:api',
    title: 'browserContext.waitForEvent',
    apiName: 'browserContext.waitForEvent',
    params: { info: [Object] },
    boxedStack: undefined,
    steps: [],
    complete: [Function: complete],
    endWallTime: 1[73](https://github.com/MadKudu/msi/actions/runs/12257750204/job/34196112986?pr=1524#step:9:74)3841148346,
    error: {
      message: 'Error: browserContext.waitForEvent: Target page, context or browser has been closed',
      stack: 'Error: browserContext.waitForEvent: Target page, context or browser has been closed\n' +
        '    at Object.extensionId (/home/runner/work/msi/msi/apps/e2e/tests/fixtures/extension.fixtures.ts:29:36)',
      cause: undefined
    }
  }
}
```

### Environment

```shell
Browser: Chromium 131.0.6778.33
Playwright: 1.49.0
OS: macOS Sequoia 15.1.1 (24B91) (local env) / Ubuntu 22.04 (for CI)
```
