### ISSUE TITLE
[Bug]: Getting expect.soft.toMatchAriaSnapshot: value.startsWith when I try to run on a drop down contains a  dropdown option '- checkbox "[Select all]" [checked]'

### ISSUE THREAD

**Issue by marcusNumminen** [microsoft/playwright#34032]
### Version

1.49.1

### Steps to reproduce

I have a drop down that look like this
![Image](https://github.com/user-attachments/assets/e3a677cc-b3c8-443b-bbf4-42cf939f7402)
and I use codegen to generate the snapshot. Codegen give me this yml:
```
 - textbox
  - list:
    - listitem:
      - checkbox "[Select all]" [checked]
      - text: [Select all]
    - listitem:
      - checkbox "English" [checked]
      - text: English
    - listitem:
      - checkbox "Swedish (Sweden)" [checked]
      - text: Swedish (Sweden)
  ```
When use this in my test I get the following error:
`TypeError: expect.soft.toMatchAriaSnapshot: value.startsWith is not a function`

However if I comment out (or remove) the first listitem it works fine

Sorry I can't give you a better repro than this.....

### Expected behavior

It should work fine with the above drop down content (see picture)

### Actual behavior

When I run the code I get `TypeError: expect.soft.toMatchAriaSnapshot: value.startsWith is not a function` error

### Environment

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 15.84 GB / 31.85 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - C:\Program Files\nodejs\pnpm.CMD
  IDEs:
    VSCode: 1.96.0 - C:\Users\fancy_stuff\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.26 - C:\Program Files\Git\usr\bin\bash.EXE
  npmPackages:
    @playwright/test: 1.49.1 => 1.49.1
    playwright: ^1.45.1 => 1.49.1
```
