### ISSUE TITLE
[Bug]: Electron fails to launch on ubuntu-latest

### ISSUE THREAD

**Issue by bhbs** [microsoft/playwright#34251]
### Version

1.49.1

### Steps to reproduce

Reproduction: 
  - Run: https://github.com/bhbs/playwright-repro-34251/actions/runs/12670141479
  - Repository: https://github.com/bhbs/playwright-repro-34251

```yaml
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx --yes envinfo --preset playwright
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npx playwright test
```

```js
const { _electron: electron } = require("playwright");
const { test } = require("@playwright/test");

test("LAUNCH", async () => {
  await electron.launch({ args: ["main.js"] });
});
```

```js
const { app, BrowserWindow } = require("electron");

function createWindow() {
  const mainWindow = new BrowserWindow();
  mainWindow.loadFile("index.html");
}

app.whenReady().then(() => {
  createWindow();
});
```

### Expected behavior

Launch successfully

### Actual behavior

`Error: Process failed to launch!`

### Additional context

Following the solution introduced in https://github.com/microsoft/playwright/issues/11932#issuecomment-1033534390 , I am trying to launch Playwright using xvfb-run.
I apologize, as the implementation of Playwright should not be the problem, but I am looking for a new solution.

### Environment

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (2) x64 AMD EPYC 7763 64-Core Processor
    Memory: 6.85 GB / 7.75 GB
    Container: Yes
  Binaries:
    Node: 20.18.1 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.49.1 => 1.49.1 
    playwright: ^1.49.1 => 1.49.1
```
