### ISSUE TITLE
[Bug]: Cannot merge generated blob files from different jobs in Azure DevOps pipeline

### ISSUE THREAD

**Issue by MrGeek14** [microsoft/playwright#35120]
### Version

1.50

### Steps to reproduce

```yaml
- stage: TestExecution
  displayName: "Test Execution"
  condition: or(eq(variables['Build.Reason'], 'Schedule'), eq('${{parameters.scriptName}}', 'All'))
  jobs:
    - job: ScheduledScripts
      displayName: "Critical Business Tests"
      strategy:
        maxParallel: 1  # Ensure sequential execution
        matrix:
          Tags:
            scriptNameMatrix: "xxx"
          
          # Add scripts here as needed for scheduled runs also can config the browser to run and environment
      steps:
        - template: steps.yml
          parameters:
            environment: ${{ parameters.environment }}
            browser: 'Edge'
            tag: "All"
            scriptName: $(scriptNameMatrix)


- stage: MergeReports
  displayName: "Merge Playwright Blob Reports"
  dependsOn:
    - TestExecution
  condition: succeededOrFailed()
  jobs:
    - job: MergeBlobReports
      displayName: "Merge Blob Reports into Consolidated HTML"
      steps:
        # Step 1: Checkout source code
        - checkout: self
 
        # Step 2: Setup Node.js
        - task: NodeTool@0
          inputs:
            versionSpec: "20.x"
          displayName: "Install Node.js"
 
        # Step 3: Restore npm cache
        - task: Cache@2
          inputs:
            key: 'npm | "$(Build.SourcesDirectory)/package-lock.json"'
            restoreKeys: 'npm | "$(Build.SourcesDirectory)"'
            path: './.npm'
          displayName: "Restore npm cache"
 
        # Step 4: Install dependencies
        - script: npm ci --cache .npm --prefer-offline
          displayName: "Install NPM dependencies"
 
        # Step 6: Download all artifacts
        - task: DownloadPipelineArtifact@2
          inputs:
            source: 'current'
            path: '$(System.DefaultWorkingDirectory)/all-blob-reports'
          displayName: "Download all Artifacts"
 
        # Step 7: Merge blob reports and generate HTML
        - script: |
            echo "Merging blob reports..."
            mkdir -p merged-html-report
    
            
            # Find all blob reports directories
            echo "Listind downloaded blob reports..."
            find ./all-blob-reports -type f | sort


            # Generate HTML report
            npx playwright merge-reports --reporter html ./all-blob-reports merged-html-report
          displayName: "Merge Blob Reports and Generate HTML"
 
        # Step 8: Publish the consolidated HTML report
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/merged-html-report'
            artifact: 'ConsolidatedPlaywrightTestReport_${{ parameters.environment }}'
            publishLocation: 'pipeline'
          displayName: "Publish Consolidated HTML Report"
          condition: always()
 ```

### Expected behavior

Merge generated blobs and create a single consolidated html report

### Actual behavior

Merging blob reports...
Listind downloaded blob reports...
./all-blob-reports/BlobReport_Tags_Edge_B99UAT/report-Edge-4005c4e.zip
merging reports from /home/vsts/work/1/s/all-blob-reports
Error: No report files found in /home/vsts/work/1/s/all-blob-reports
    at createMergedReport (/home/vsts/work/1/s/node_modules/playwright/lib/reporters/merge.js:44:38)
    at async mergeReports (/home/vsts/work/1/s/node_modules/playwright/lib/program.js:266:3)
    at async t.<anonymous> (/home/vsts/work/1/s/node_modules/playwright/lib/program.js:151:7)

### Additional context

tried to unzip the blobs and merge also not worked

### Environment

```shell
Azure DevOps pipeline
Node Version:20.x
```
