### ISSUE TITLE
[Bug][chromium]: When enabling tracing with snapshots, the protected HEAD request causes credential dialog to open

### ISSUE THREAD

**Issue by saw-jan** [microsoft/playwright#35891]
### Version

1.52.0

### Steps to reproduce

I couldn't find other way to reproduce this. So, here's my setup:
1. Start [ocis](https://github.com/owncloud/ocis) server. Simple docker compose file
    ```yaml
    services:
      ocis:
        image: owncloud/ocis:latest
        ports:
          - 9200:9200
        environment:
          OCIS_URL: https://localhost:9200
          IDM_ADMIN_PASSWORD: admin
          OCIS_INSECURE: true
          OCIS_LOG_LEVEL: error
        entrypoint: /bin/sh
        command: ['-c', 'ocis init || true; ocis server']
    ```
2. Start the following test in headed mode:
    ```js
    import { test, chromium } from '@playwright/test'

    test('download', async () => {
      const browser = await chromium.launch()
      const context = await browser.newContext()
      await context.tracing.start({ screenshots: false, snapshots: true, sources: false })
      const page = await context.newPage()
      await page.goto('https://localhost:9200')
      await page.locator('#oc-login-username').fill('admin')
      await page.locator('#oc-login-password').fill('admin')
      await Promise.all([
        page.waitForResponse(
          (resp) =>
            resp.url().endsWith('/token') && resp.status() === 200 && resp.request().method() === 'POST'
        ),
        page.locator('button[type="submit"]').click()
      ])
      await page.locator('#web-content').waitFor()
      await page.pause()
      await context.tracing.stop({ path: 'trace.zip' })
    })
    ```
4. From the running ocis UI, upload an image
5. Open the image
6. Download the image
![Image](https://github.com/user-attachments/assets/cba95618-cf23-4b68-a3b1-e08afb92e363)

### Expected behavior

Browser credential dialog should not be opened.

### Actual behavior

Browser credential dialog appears

![Image](https://github.com/user-attachments/assets/446c6861-0e43-4d79-8034-305bd4b37bfe)

### Additional context

>[!NOTE] 
>we should not try to get the body for `HEAD` requests as HEAD request will not send the body (see [rfc](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.2))
>https://github.com/microsoft/playwright/blob/3cf6fa2db4f61fb64e46cdd411b426008608a0de/packages/playwright-core/src/server/chromium/crNetworkManager.ts#L374-L388

This doesn't happen with Firefox and Webkit browsers

For chromium, the solution could be to return empty body early for HEAD requests from `getResponseBody` of `crNetworkManager.ts`
```js
const getResponseBody = async () => { 
  if (request.request.method() === 'HEAD') {
    return Buffer.from('');
  }
...
```

### Environment

```shell
System: `Ubuntu 22.04`
Node: `20.18.1`
```
