### ISSUE TITLE
[BUG] Using the docker image in CircleCI changes the home dir

### ISSUE THREAD

**Issue by eps1lon** [microsoft/playwright#5372]
**Context:**
- Playwright Version: 1.8.0
- Operating System: see "Extra"
- Node.js version: see "Extra"
- Browser: see "Extra"
- Extra: docker image `mcr.microsoft.com/playwright@sha256:713f929b3023bef05ba8ad45cac8466f1d07271a3dcebbb95975cd24b535d70e` (current `mcr.microsoft.com/playwright:bionic`)

**Code Snippet**

reduced CircleCI config:
```yml
- restore_cache:
    keys:
      - v6-yarn-sha-{{ checksum "yarn.lock" }}
      - v6-yarn-sha-
- run:
    name: Set yarn cache folder
    command: |
      yarn config set cache-folder ~/.cache/yarn
      yarn cache dir
      yarn cache list
- restore_cache:
    keys:
      - v1-playwright-{{ arch }}-{{ checksum "yarn.lock" }}
      - v1-playwright-{{ arch }}-
      - v1-playwright-
- run:
    name: Install js dependencies
    command: yarn install --verbose
- save_cache:
    key: v1-playwright-{{ arch }}-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/ms-playwright
- save_cache:
    key: v6-yarn-sha-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
```

**Describe the bug**

`~` i.e. the home dir changes when [using the recommended docker image in CircleCI](https://playwright.dev/docs/ci#circleci).
This means we can't cache paths based on `~` if that cache was persisted with a job using another docker image.

Example workflow run: https://app.circleci.com/pipelines/github/mui-org/material-ui/37818/workflows/ea0d08d5-d4dd-4283-80ee-9dd93e35a207/jobs/223400
"Restore Cache":
```
Found a cache from build 223398 at v6-yarn-sha-YAcvpk7GLmzZbc4fTfsxQJ+CSt2W7iR_3bHwoDLFVkc=
Size: 203 MiB
Cached paths:
  * /home/circleci/.cache/yarn
```

"Set yarn cache folder"
```
yarn config set cache-folder ~/.cache/yarn
yarn config v1.22.4
success Set "cache-folder" to "/root/.cache/yarn".
Done in 0.03s.
```
