### ISSUE TITLE
[REGRESSION]: npm install rights issue with azure containerized jobs

### ISSUE THREAD

**Issue by mackanjansson** [microsoft/playwright#5635]
**Context:**
- Playwright Version: 1.9.1
- Operating System: Linux 
- Node.js version: Whatever is inside Playwright Docker image
- Browser: N/A
- Extra: Azure Containerized job

Im running playwrights tests in the context of azure containerized job. Between Tuesday 23/2 and Wednesday 24/2 it stopped working and what I can see there is a rights issue going on during the npm install step:

UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/ms-playwright/.links/d58e99f5870021ec569c25cde2dfaedc50c87f22'
  
I have been able to work around the issue by setting PLAYWRIGHT_BROWSERS_PATH: 0 as I understand it effectively making the code not trying to access this area/file mentioned in the error message

Steps to reproduce is a simple package.json with just playwright dependancy (1.9.1 e.g.) and a simple azure pipeline definition like this:

```yaml
pool:
  vmImage: ubuntu-20.04

resources:
  containers:
  - container: playwright
    image: mcr.microsoft.com/playwright:focal

jobs:
  - job: "test_job"
    container: playwright
    steps:
      - script: npm install
        displayName: npm install 
```
