### ISSUE TITLE
[BUG] Getting "Please install @playwright/test package to use Playwright Test."

### ISSUE THREAD

**Issue by thecodrr** [microsoft/playwright#6981]
**Context:**
## System:
 - OS: Linux 5.4 Ubuntu 21.04 (Hirsute Hippo)
 - Memory: 502.32 MB / 15.52 GB
 - Container: Yes
## Binaries:
 - Node: 15.14.0 - ~/.volta/tools/image/node/15.14.0/bin/node
 - Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
 - npm: 7.15.0 - ~/.volta/tools/image/npm/7.15.0/bin/npm
## Languages:
 - Bash: 5.1.4 - /usr/bin/bash
## npmPackages:
 - playwright: ^1.12.0 => 1.12.0

**Describe the bug**

I just installed `playwright` version `1.12` to try out the new test runner but I am consistently getting `Please install @playwright/test package to use Playwright Test.` no matter how many times I do `yarn add --dev @playwright/test`.

**Comment by pavelfeldman** [comment]
You don't need `playwright` when using `@playwright/test`:

```bash
yarn init -y
yarn add --dev @playwright/test
npx playwright test
```

**Comment by cyrilletuzi** [comment]
Had the same issue, because previous beta versions of `@playwright/test` did require `playwright`.

Solution:
- `npm rm playwright`
- `npm install @playwright/test -D`

Then it works.

**Comment by cyrilletuzi** [comment]
Note/question: for projects using Playwright for both unit tests and e2e tests, could this be a problem? or is `@playwright/test`-only the way to go in this scenario?

**Comment by mpuertao** [comment]
In my case, 
- Delete playwright, 
- Install @playwright/test
- Reinstall playwright. 

Success!!!

**Comment by thecodrr** [comment]
> You don't need `playwright` when using `@playwright/test`:
> 
> ```shell
> yarn init -y
> yarn add --dev @playwright/test
> npx playwright test
> ```

Yep. This worked.

**Comment by mariusc23** [comment]
I ran into this issue because I had `test` in my `.yarnclean` file. Yarn removed the `lib/test` folder and the entire `node_modules/@playright/test` folder because of this 🤦 

I fixed by adding this to `.yarnclean`:
```
!@playwright/test/**
```

**Comment by nathanchase** [comment]
I've been trying everything I can think of to get testing to work in an Azure Pipeline.

My YAML:
```
resources:
  containers:
  - container: playwright
    image: mcr.microsoft.com/playwright:focal

  repositories:
  - repository: self
    type: git
    ref: refs/heads/develop

jobs:
- job: e2e_testing
  container: playwright
  displayName: E2E Testing

  pool:
    vmImage: ubuntu-latest

  steps:
  - checkout: self

  - script: |
      yarn
      npx playwright test
    displayName: 'Run test'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testRunTitle: 'Test Report'
    displayName: 'Publish Reports'
```
but I get... 
```
Please install @playwright/test package to use Playwright Test.
  npm install -D @playwright/test
##[error]Bash exited with code '1'.
```
If I try to use 'yarn playwright test', then I get...
```
yarn run v1.22.11
$ playwright test
/bin/sh: 1: playwright: not found
error Command failed with exit code 127.
```
What is the magic combination to make this work??
