### ISSUE TITLE
[BUG] [Docker] Husky fail to install on docker image

### ISSUE THREAD

**Issue by Th3S4mur41** [microsoft/playwright#7136]
[Husky](https://github.com/typicode/husky) from @typicode is added as devDependency with a prepare script to install the hooks according to [documentation](https://typicode.github.io/husky/#/?id=install).

The prepare step fails on the `mcr.microsoft.com/playwright:focal` container due to missing permissions.

Github Actions job is configured as follow:
```
  test:
    runs-on: [self-hosted, linux]
    container: mcr.microsoft.com/playwright:focal
    steps:
      - uses: actions/checkout@v2
      - run: npm ci --no-optional --no-audit --prefer-offline --progress=false
      - run: HOME=/root npm run test:playwright
```

This is the error ouptut from the CI:

```
prepare
> husky install

husky - Git hooks failed to install
/__w/project_a/project_a/node_modules/husky/lib/index.js:33
        throw e;
        ^

Error: EACCES: permission denied, mkdir '.husky/_'
    at Object.mkdirSync (node:fs:1324:3)
    at Object.install (/__w/project_a/project_a/node_modules/husky/lib/index.js:23:12)
    at Object.install (/__w/project_a/project_a/node_modules/husky/lib/bin.js:27:41)
    at Object.<anonymous> (/__w/project_a/project_a/node_modules/husky/lib/bin.js:39:22)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '.husky/_'
}
npm ERR! code 1
npm ERR! path /__w/project_a/project_a
npm ERR! command failed
npm ERR! command sh -c husky install
```

The same script runs fine on e.g. `node:lts-buster` container
