### ISSUE TITLE
[BUG] tests not running in Gitlab CI using Next.js

### ISSUE THREAD

**Issue by raptoria** [microsoft/playwright#7380]
**Context:**
- Playwright Version: 1.12.2
- Operating System: Mac
- Node.js version: v16.0.0
- Browser: Chromium
- Extra: 
Using the  jest-playwright plugin:

		"jest": "^26.6.3",
		"jest-playwright-preset": "^1.6.1",
		"playwright": "^1.12.2",

Test:

```javascript

import 'expect-playwright';

describe('Chariot UI', () => {
	beforeEach(async () => {
		page.setDefaultTimeout(10000);
		await page.goto('http://localhost:3000/training-management', {
			waitUntil: 'networkidle'
		});
	});

	it('should be titled "Chariot UI"', async () => {
		await expect(page.title()).resolves.toMatch('Chariot UI');
	});
});
```

This test passes locally but fails in the Gitlab CI. We are using Next.js. It appears to fail when trying to request a Next.js chunk?
If I change the goto to http://localhost:3000/ instead of http://localhost:3000/training-management, then the test passes in the CI.

```
@strive/chariot-web:   ● Chariot UI › should be titled "Chariot UI"
@strive/chariot-web:     Network Error
@strive/chariot-web:       at t.exports (http:/localhost:3000/_next/static/chunks/8fe83bdf6fb8e773a3bc75d81223484fe50e11ed.e99e84c2dcd54ad44df9.js:1:220505)
@strive/chariot-web:       at XMLHttpRequest.p.onerror (http:/localhost:3000/_next/static/chunks/8fe83bdf6fb8e773a3bc75d81223484fe50e11ed.e99e84c2dcd54ad44df9.js:1:11777)
@strive/chariot-web:   ● Chariot UI › should be able to create run
@strive/chariot-web:     expect(received).resolves.toMatch()
@strive/chariot-web:     Received promise rejected instead of resolved
@strive/chariot-web:     Rejected to value: [Error: page.title: Execution context was destroyed, most likely because of a navigation.]
```

CI file:

```
test:
  needs: []
  stage: test
  image: mcr.microsoft.com/playwright:focal
  script:
    - npm install -g lerna
    - npm install typescript -g
    - npm run bootstrap
    - npm run build:chariot
    - npm run test:chariot
  artifacts:
    when: always
```
