### ISSUE TITLE
[BUG] Webfont Loading on Webkit Devices

### ISSUE THREAD

**Issue by subodhpareek18** [microsoft/playwright#7441]
**Context:**
- Playwright Version: "@playwright/test": "^1.12.3"
- Operating System: Windows 10 Pro
- Node.js version: v13.11.0
- Browser: Webkit

I have an issue with rendering webfonts on webkit on windows. Screenshots and further details written below.

**Chromium**
![image](https://user-images.githubusercontent.com/12589797/124228790-52d91580-db2a-11eb-9728-af3e02c3eea7.png)

**Firefox**
![image](https://user-images.githubusercontent.com/12589797/124228846-65534f00-db2a-11eb-89e4-333b6da7e114.png)

**Chromium - Mobile / Pixel 5**
![image](https://user-images.githubusercontent.com/12589797/124228903-7a2fe280-db2a-11eb-8923-baa64f3f1d47.png)

**Webkit**
![image](https://user-images.githubusercontent.com/12589797/124228981-929ffd00-db2a-11eb-8081-0ce229e87d80.png)

**Webkit - iPad 7**
![image](https://user-images.githubusercontent.com/12589797/124229368-1e198e00-db2b-11eb-85ac-59f3e8a6fdf2.png)

**Webkit - iPhone 11**
![image](https://user-images.githubusercontent.com/12589797/124230086-30e09280-db2c-11eb-85a3-7780b5834d40.png)

**Webkit - iPhone 7**
![image](https://user-images.githubusercontent.com/12589797/124229342-11953580-db2b-11eb-9349-22bb811ef43c.png)

To my surprise iPhone 7 is rendering the fonts correctly, but no other tested webkit device is. When I open the webpage on actual physical devices I have access to like various iPhones, iPads and Macs. The fonts load just fine. Wondering what am I missing in my setup. Not only is the font not loading at all, the font weights are not being respected anywhere for the default system font.

My setup involves loading a Google Webfont on my Next.js app. Here is the main _app.js component
```jsx
export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" type="image/x-icon" href="/static/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <GlobalStyles />
      <Component {...pageProps} />
    </>
  );
}
```
And here is the bit in the global styles dealing with the font-family
```css
body, h1, h2, h3, h4, h5, h6, p, ol, ul, button, input, select, textarea {
    margin: 0;
    padding: 0;
    font-weight: normal;
    font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  }
```

**Comment by subodhpareek18** [comment]
I further updated my setup to use self hosted fonts, instead of using google webfonts cdn, hoping that would resolve the issue. But to no avail.

```css
  @font-face {
    font-family: 'Inter';
    font-style:  normal;
    font-weight: 400;
    font-display: swap;
    src: url("static/fonts/Inter-Regular.woff2") format("woff2"),
        url("static/fonts/Inter-Regular.woff2") format("woff");
  }

  @font-face {
    font-family: 'Inter';
    font-style:  normal;
    font-weight: 500;
    font-display: swap;
    src: url("static/fonts/Inter-Medium.woff2") format("woff2"),
        url("static/fonts/Inter-Medium.woff") format("woff");
  }

  @font-face {
    font-family: 'Inter';
    font-style:  normal;
    font-weight: 800;
    font-display: swap;
    src: url("static/fonts/Inter-ExtraBold.woff2") format("woff2"),
        url("static/fonts/Inter-ExtraBold.woff") format("woff");
  }

  body, h1, h2, h3, h4, h5, h6, p, ol, ul, button, input, select, textarea {
    margin: 0;
    padding: 0;
    font-weight: 400;
    font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  }
```

I thing I did not mention earlier is I'm using styled-components in an SSR setup with next.js. Perhaps that could be contributing to the issue. But I'm not sure if others have faced it too.
