### ISSUE TITLE
[Bug]:  Error while running ci

### ISSUE THREAD

**Issue by suedar** [microsoft/playwright#7740]
### Playwright version

1.12.3

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

I want to run the playwright in the gitlab-ci. But I get this error.
<img width="953" alt="截屏2021-07-20 下午6 59 15" src="https://user-images.githubusercontent.com/18492953/126313803-6f9bb163-e11a-4a77-a0eb-d70c23839856.png">

Here is my gitlab-ci.yml.

``` yml
build:
  stage: build
  image: mcr.microsoft.com/playwright:focal
  cache:
    paths:
      - node_modules
  script:
    - apt-get install -y xvfb
    - node -v & npm -v
    - npm install --force
    - npm test
```

I even try `xvfb node example.test.js `. But there are error exist.
