### ISSUE TITLE
[Bug]: Channel installation requires curl/wget on the system

### ISSUE THREAD

**Issue by suedar** [microsoft/playwright#7785]
### Playwright version

1.13.0

### Operating system

MacOS, Linux

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

When i run the `npx playwright test` locally, it went well. But within the ci, I get this error.

Here is my gitlab-ci.ymli config.
``` yml
build:
  stage: build
  image: mcr.microsoft.com/playwright:focal
  cache:
    paths: 
      - node_modules
  script:
    - /etc/init.d/dbus start
    - node -v & npm -v
    - yarn install --force
    - yarn ci-test
```

<img width="1058" alt="截屏2021-07-22 下午6 33 16" src="https://user-images.githubusercontent.com/18492953/126626303-b451f28a-20fc-402d-9a83-8243484d3c40.png">

<img width="1056" alt="截屏2021-07-22 下午6 32 16" src="https://user-images.githubusercontent.com/18492953/126626317-b5d8a02b-4f1b-4637-b2f6-258e85d9b3c3.png">

Appreciate for any reply~
