### ISSUE TITLE
recordVideo does not work when running in CI with xvfb-run option / headful mode

### ISSUE THREAD

**Issue by Phonesis** [microsoft/playwright#8936]
I've been trying to get Playwright to record video of our runs in Github Actions. 

I am using the following workflow 

```
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies and run tests
        run: npm install &&  xvfb-run --auto-servernum -- npm run test-all
        env:
          CUCUMBER_PUBLISH_ENABLED: true
          RECORD_VIDEO: 'true'
      - name: Scenario Recordings
        uses: actions/upload-artifact@v2.2.4
        if: ${{ failure() || success() }}
        with:
          name: Scenario Videos
          path: videos/
```

In my code for the test setup, am passing in: 

```
await global.browser.newContext(
    {recordVideo: { dir: 'videos/' }}
  );
```

When I run this locally, it works fine and videos are generated in the videos folder.

However, in Github Actions no videos appear to generate. I am wondering if this is due to the fact it runs on ubuntu with the following args: 

```
        run: npm install &&  xvfb-run --auto-servernum -- npm run test-all
```

Does video recording work with both headful and headless modes?

**Comment by mxschmitt** [comment]
> Does video recording work with both headful and headless modes?

Yes, it works in headed and headless mode

> However, in Github Actions no videos appear to generate. I

So the `videos/` directory is empty?

Do you have a minimum reproducible which demonstrates it? When recording videos, its important to await the context closing, see [here](https://playwright.dev/docs/videos).

(We also run our tests in headless mode on GitHub Actions with xvfb-run, so in general it should work.)

**Comment by Phonesis** [comment]
Hello again, thanks for response. So not 100% sure how but managed to get it to work now. I think I had to specify the workspace in my workflow and in the recordVideo dir arg:

```
          VIDEO_PATH: ${{ github.workspace }}
      - name: Scenario Recordings
        uses: actions/upload-artifact@v2.2.4
        if: ${{ failure() }}
        with:
          name: Failed Scenario Videos
          path: ${{ github.workspace }}/videos/
```

Then in code: 

```
{ recordVideo: { dir: `${process.env.VIDEO_PATH}/videos/`,}
```

Not sure why I needed to do this when it doesn't make any ref to it in your docs. 

In addition, I also set headless to true and removed the xvfb-run stuff from the script. 

Videos now appear in the folder and save to a zip as expected.
