### ISSUE TITLE
[BUG] PW not working for electron on ubuntu-latest github actions

### ISSUE THREAD

**Issue by lsagetlethias** [microsoft/playwright#9262]
**Context:**
- Playwright Version: 1.15.0
- Operating System: ubuntu-latest (from github action)
- Node.js version: 14
- Browser: Electron
- Extra: github action

**Code Snippet**

I'm using a very simple configuration and setup, yet no success so far:

```typescript
// tests/e2e/app.spec.ts
import type { ElectronApplication, Page } from "@playwright/test";
import { _electron as electron, expect, test } from "@playwright/test";
import path from "path";

test.describe("App e2e", () => {
    let electronApp: ElectronApplication, win: Page;
    test.beforeEach(async () => {
        electronApp = await electron.launch({
            args: [
                "--disable_splash_screen",
                "--disable-extensions",
                "--disable-dev-shm-usage",
                "--no-sandbox",
                path.resolve(__dirname, "..", "..", "dist", "main", "main.js"),
            ],
            env: {
                E2E: "true",
                ELECTRON_ENABLE_LOGGING: "true",
                ELECTRON_ENABLE_STACK_DUMPING: "true",
                NODE_ENV: "test-e2e",
            },
            timeout: 120000,
        });
        await electronApp.evaluate(({ app }) => {
            // This runs in the main Electron process, parameter here is always
            // the result of the require('electron') in the main app script.
            return app.getAppPath();
        });

        win = await electronApp.firstWindow();
        win.on("console", console.log);
        await win.waitForLoadState();
    });

    test.afterEach(async () => {
        await electronApp.close();
    });

    test("should render the application", async () => {
        expect((await win.content()).includes("Hello toto")).toBeTruthy();
    });
});
```

```yml
# .github/workflows/e2e.yml

# [...]
e2e:
    env:
      ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
    name: Run E2E test on ${{ matrix.os }}
    needs: compile
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: ./.github/actions/setup-node
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: electron-dist
          path: dist/

      - name: Test electron
        run: yarn electron -v

      - name: Install Playwright deps
        run: yarn playwright install --with-deps chromium

      - name: Test if XVFB should be used
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          echo ::set-output name=electron_bin::$(yarn bin electron)
          echo ::set-output name=result::$(echo "xvfb-run --auto-servernum  --server-args='-screen 0 1280x960x24' --")
        id: xvfb

      - name: Run Playwright
        timeout-minutes: 15
        run: ${{ steps.xvfb.outputs.result }} yarn test:e2e
```

```javascript
// playwright.config.js
/** @type { import("@playwright/test").PlaywrightTestConfig} */
module.exports = {
    reporter: process.env.CI ? "dot" : "list",
    testDir: "test/e2e/",
    timeout: 120000,
    use: {
        headless: true,
        ignoreHTTPSErrors: true,
    },
};
```

**Describe the bug**
It works locally (macOS), but also on CI with macos-latest and windows-latest.
No error, just a timeout (that's why I tried to up the timeout to 2mins)

Log from step:
```
Run xvfb-run --auto-servernum --server-args='-screen 0 1280x960x24' -- yarn test:e2e
yarn run v1.22.11
$ playwright test
T

  1) app.spec.ts:43:5 › App e2e should render the application ======================================

    Timeout of 120000ms exceeded.

    TypeError: Cannot read property 'close' of undefined

      38 |
      39 |     test.afterEach(async () => {
    > 40 |         await electronApp.close();
         |                           ^
      41 |     });
      42 |
      43 |     test("should render the application", async () => {

        at /home/runner/work/archimail/archimail/test/e2e/app.spec.ts:40:27
        at FixtureRunner.resolveParametersAndRunHookOrTest (/home/runner/work/archimail/archimail/node_modules/@playwright/test/lib/test/fixtures.js:303:12)
        at runNextTicks (internal/process/task_queues.js:60:5)
        at processTimers (internal/timers.js:497:9)
        at WorkerRunner._runHooks (/home/runner/work/archimail/archimail/node_modules/@playwright/test/lib/test/workerRunner.js:510:9)
        at WorkerRunner._runAfterHooks (/home/runner/work/archimail/archimail/node_modules/@playwright/test/lib/test/workerRunner.js:473:34)

  Slow test: app.spec.ts (2m)

  1 failed
    app.spec.ts:43:5 › App e2e should render the application =======================================
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

I obviously did something wrong or forgot something but what?
