### ISSUE TITLE
[BUG] Weired behavior when running tests in Azure DevOps

### ISSUE THREAD

**Issue by erfgypO** [microsoft/playwright#9358]
**Context:**
- Playwright Version: 1.15.2
- Operating System: Ubuntu 20.04
- Node.js version: 14.18
- Browser: All
- Extra: Azure Devops Pipeline

 I get a weired error, whenever i want to run my tests in an azure dev ops pipeline. I get an exit code of 1 and the message `Error: test() can only be called in a test file`. When I ssh into the server and manually execute the tests everything works just fine. Do you guys have any ideas what could be wrong?

My Config:
```js
const config = { 
    testDir: 'tests/e2e',
    reporter: [ ['junit', { outputFile: 'results.xml' }],['json', {  outputFile: 'test-results.json' }] ],
   };
module.exports = config;const config = { 
    testDir: 'tests/e2e',
    reporter: [ ['junit', { outputFile: 'results.xml' }],['json', {  outputFile: 'test-results.json' }] ],
   };

module.exports = config;
```

Spec file:
```js
test('frontend login', async ({page}) => {
  //Startpage
  await page.goto('https://example.com');

  // Click login button to start login process
  await page.click('#main_login')
 
  // Handle privacy popup
  await page.waitForSelector('#login-new-dialog-privacy-closer')
  const isNotHidden = await page.$eval('#login-new-dialog-privacy-closer', (elem) => {
      return window.getComputedStyle(elem).getPropertyValue('display') !== 'none'
  });
  if (isNotHidden) {
      await page.click('#login-new-dialog-privacy-btn-confirm')
  }

  // Login with NEW's SSO
  await page.fill('[type="email"]', USERNAME)
  await page.fill('[type="password"]', PASSWORD)
  await page.click('[type="submit"]')

  //Verify Login
  await page.click('#login-new-avatar-btn');
  const nameNew = await page.innerHTML('title');
  console.log(nameNew)
 
});
```

**Comment by JoelEinbinder** [comment]
It sounds like you are doing `node my-test.spec.js` instead of `npx playwright my-test.spec.js`. Can you provide the code that actually spawns the tests?

**Comment by erfgypO** [comment]
```yml
steps:
- task: Npm@1 #npm install
  displayName: 'npm install'
  inputs:
    verbose: false
- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install -D @playwright/test'
- bash: 'npx playwright install'
  displayName: 'playwright get all browser'
- bash: 'npx playwright test --browser=all'
  displayName: 'run tests'
```

These steps get executed on an macOS-11 agent
