### ISSUE TITLE
[Question] How to run playwright tests with a Netlify setup

### ISSUE THREAD

**Issue by mhatvan** [microsoft/playwright#9971]
I saw that there is `netlify-plugin-cypress`, but unfortunately no `netlify-plugin-playwright`. 

Netlify doesn't seem to offer the user much configuration options for `build` command through `netlify.toml`.

I found https://github.com/microsoft/playwright-github-action, but then we would build the project on Netlify and GitHub, which is not efficient. 

What is the recommended way to run playwright e2e test against a Netlify branch deploy?

**Comment by mxschmitt** [comment]
This should work with Netlify out of the box: https://playwright.dev/docs/ci#github-actions-on-deployment

It will trigger the GitHub Action once the Netlify deployment has finished and passes the baseURL over to the Playwright Test Runner to run the tests on.

**Comment by mhatvan** [comment]
With `github.event.deployment_status.state == 'success'` the whole CI check is simply skipped, how would it be listening for Netlify deployment finish? 
I found https://github.com/JakePartusch/wait-for-netlify-action which I tried so far before opening this issue.

Also, does `PLAYWRIGHT_TEST_BASE_URL` depend on me setting `baseUrl` to `process.env.PLAYWRIGHT_TEST_BASE_URL` in playwright config?

I currently have a `baseUrl` set in the config, which is used for local runs. Would `PLAYWRIGHT_TEST_BASE_URL` overwrite it for the CI run?

**Comment by mxschmitt** [comment]
you need to add to your playwright.config.ts something like this:

`baseURL: process.env.PLAYWRIGHT_TEST_BASE_URL || 'http://localhost:3000'`

It should not get skipped, it should get triggered once Netlify has finished their deployment. I'd recommend to reach out to their support to ask about the GitHub Action integration or ask in the wait-for-netlify action repo.

I tried it back then with Vercel, which should use the same GitHub deployment API under the hood: https://github.com/mxschmitt/vercel-playwright-end-to-end-tests/

**Comment by mhatvan** [comment]
For anyone stumbling upon this issue, this is how I was able to get it running:
```
name: E2E Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Setup Playwright
        run: npx playwright install-deps chromium
      - name: Install dependencies
        run: yarn install
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1.2
        id: waitFor200
        with:
          site_name: "<ENTER_SITE_NAME>"
          max_timeout: 360 # 6 Minutes, depends on your build pipeline duration
      - name: Run E2E Tests on Netlify URL
        run: yarn e2e
        env: 
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitFor200.outputs.url }}
```

Is there a way to skip the unnecessary `yarn install` (takes 10min) and just install playwright? I tried `npx playwright test` but it gives me `Please install @playwright/test package to use Playwright Test.`

Would `yarn add -g @playwright/test` work?
